/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppWebhooksIndexRouteImport } from './routes/_app/webhooks/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppReferralsIndexRouteImport } from './routes/_app/referrals/index'
import { Route as AppPricingIndexRouteImport } from './routes/_app/pricing/index'
import { Route as AppPlansIndexRouteImport } from './routes/_app/plans/index'
import { Route as AppEventsIndexRouteImport } from './routes/_app/events/index'
import { Route as AppDevelopersIndexRouteImport } from './routes/_app/developers/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as AppWebhooksConfigIdRouteImport } from './routes/_app/webhooks/$configId'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppSettingsProductsRouteImport } from './routes/_app/settings/products'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppReferralsCustomerIdRouteImport } from './routes/_app/referrals/$customerId'
import { Route as AppPricingBookIdRouteImport } from './routes/_app/pricing/$bookId'
import { Route as AppEventsEventIdRouteImport } from './routes/_app/events/$eventId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppTasksKindsKeyRouteImport } from './routes/_app/tasks/kinds/$key'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksIndexRoute = AppWebhooksIndexRouteImport.update({
  id: '/webhooks/',
  path: '/webhooks/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReferralsIndexRoute = AppReferralsIndexRouteImport.update({
  id: '/referrals/',
  path: '/referrals/',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingIndexRoute = AppPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersIndexRoute = AppDevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebhooksConfigIdRoute = AppWebhooksConfigIdRouteImport.update({
  id: '/webhooks/$configId',
  path: '/webhooks/$configId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProductsRoute = AppSettingsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppReferralsCustomerIdRoute = AppReferralsCustomerIdRouteImport.update({
  id: '/referrals/$customerId',
  path: '/referrals/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingBookIdRoute = AppPricingBookIdRouteImport.update({
  id: '/pricing/$bookId',
  path: '/pricing/$bookId',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksKindsKeyRoute = AppTasksKindsKeyRouteImport.update({
  id: '/tasks/kinds/$key',
  path: '/tasks/kinds/$key',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/pricing/$bookId': typeof AppPricingBookIdRoute
  '/referrals/$customerId': typeof AppReferralsCustomerIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/products': typeof AppSettingsProductsRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/webhooks/$configId': typeof AppWebhooksConfigIdRoute
  '/billing/': typeof AppBillingIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/developers/': typeof AppDevelopersIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/plans/': typeof AppPlansIndexRoute
  '/pricing/': typeof AppPricingIndexRoute
  '/referrals/': typeof AppReferralsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/webhooks/': typeof AppWebhooksIndexRoute
  '/tasks/kinds/$key': typeof AppTasksKindsKeyRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AppIndexRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/pricing/$bookId': typeof AppPricingBookIdRoute
  '/referrals/$customerId': typeof AppReferralsCustomerIdRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/products': typeof AppSettingsProductsRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/webhooks/$configId': typeof AppWebhooksConfigIdRoute
  '/billing': typeof AppBillingIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/developers': typeof AppDevelopersIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/plans': typeof AppPlansIndexRoute
  '/pricing': typeof AppPricingIndexRoute
  '/referrals': typeof AppReferralsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/webhooks': typeof AppWebhooksIndexRoute
  '/tasks/kinds/$key': typeof AppTasksKindsKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/pricing/$bookId': typeof AppPricingBookIdRoute
  '/_app/referrals/$customerId': typeof AppReferralsCustomerIdRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/products': typeof AppSettingsProductsRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/webhooks/$configId': typeof AppWebhooksConfigIdRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/developers/': typeof AppDevelopersIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/plans/': typeof AppPlansIndexRoute
  '/_app/pricing/': typeof AppPricingIndexRoute
  '/_app/referrals/': typeof AppReferralsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/webhooks/': typeof AppWebhooksIndexRoute
  '/_app/tasks/kinds/$key': typeof AppTasksKindsKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/settings'
    | '/customers/$customerId'
    | '/events/$eventId'
    | '/pricing/$bookId'
    | '/referrals/$customerId'
    | '/settings/audit'
    | '/settings/billing'
    | '/settings/products'
    | '/settings/team'
    | '/webhooks/$configId'
    | '/billing/'
    | '/customers/'
    | '/developers/'
    | '/events/'
    | '/plans/'
    | '/pricing/'
    | '/referrals/'
    | '/settings/'
    | '/tasks/'
    | '/webhooks/'
    | '/tasks/kinds/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/customers/$customerId'
    | '/events/$eventId'
    | '/pricing/$bookId'
    | '/referrals/$customerId'
    | '/settings/audit'
    | '/settings/billing'
    | '/settings/products'
    | '/settings/team'
    | '/webhooks/$configId'
    | '/billing'
    | '/customers'
    | '/developers'
    | '/events'
    | '/plans'
    | '/pricing'
    | '/referrals'
    | '/settings'
    | '/tasks'
    | '/webhooks'
    | '/tasks/kinds/$key'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/settings'
    | '/_app/'
    | '/_app/customers/$customerId'
    | '/_app/events/$eventId'
    | '/_app/pricing/$bookId'
    | '/_app/referrals/$customerId'
    | '/_app/settings/audit'
    | '/_app/settings/billing'
    | '/_app/settings/products'
    | '/_app/settings/team'
    | '/_app/webhooks/$configId'
    | '/_app/billing/'
    | '/_app/customers/'
    | '/_app/developers/'
    | '/_app/events/'
    | '/_app/plans/'
    | '/_app/pricing/'
    | '/_app/referrals/'
    | '/_app/settings/'
    | '/_app/tasks/'
    | '/_app/webhooks/'
    | '/_app/tasks/kinds/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks/': {
      id: '/_app/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AppWebhooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/referrals/': {
      id: '/_app/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof AppReferralsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/': {
      id: '/_app/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof AppPricingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/': {
      id: '/_app/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof AppDevelopersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/webhooks/$configId': {
      id: '/_app/webhooks/$configId'
      path: '/webhooks/$configId'
      fullPath: '/webhooks/$configId'
      preLoaderRoute: typeof AppWebhooksConfigIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/products': {
      id: '/_app/settings/products'
      path: '/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof AppSettingsProductsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/referrals/$customerId': {
      id: '/_app/referrals/$customerId'
      path: '/referrals/$customerId'
      fullPath: '/referrals/$customerId'
      preLoaderRoute: typeof AppReferralsCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing/$bookId': {
      id: '/_app/pricing/$bookId'
      path: '/pricing/$bookId'
      fullPath: '/pricing/$bookId'
      preLoaderRoute: typeof AppPricingBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/kinds/$key': {
      id: '/_app/tasks/kinds/$key'
      path: '/tasks/kinds/$key'
      fullPath: '/tasks/kinds/$key'
      preLoaderRoute: typeof AppTasksKindsKeyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsProductsRoute: typeof AppSettingsProductsRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsProductsRoute: AppSettingsProductsRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppPricingBookIdRoute: typeof AppPricingBookIdRoute
  AppReferralsCustomerIdRoute: typeof AppReferralsCustomerIdRoute
  AppWebhooksConfigIdRoute: typeof AppWebhooksConfigIdRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDevelopersIndexRoute: typeof AppDevelopersIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppPricingIndexRoute: typeof AppPricingIndexRoute
  AppReferralsIndexRoute: typeof AppReferralsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppWebhooksIndexRoute: typeof AppWebhooksIndexRoute
  AppTasksKindsKeyRoute: typeof AppTasksKindsKeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppPricingBookIdRoute: AppPricingBookIdRoute,
  AppReferralsCustomerIdRoute: AppReferralsCustomerIdRoute,
  AppWebhooksConfigIdRoute: AppWebhooksConfigIdRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDevelopersIndexRoute: AppDevelopersIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppPricingIndexRoute: AppPricingIndexRoute,
  AppReferralsIndexRoute: AppReferralsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppWebhooksIndexRoute: AppWebhooksIndexRoute,
  AppTasksKindsKeyRoute: AppTasksKindsKeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
