# Generated by Django 6.0.1 on 2026-01-30 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_wallettransaction_idempotency_key_and_more'),
        ('tenants', '__first__'),
        ('usage', '0002_billingperiod_idx_billing_period_status_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_micros', models.BigIntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='customers.customer')),
                ('refunded_by_api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenantapikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='tenants.tenant')),
                ('usage_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='usage.usageevent')),
            ],
            options={
                'db_table': 'ubb_refund',
            },
        ),
    ]
