# Generated by Django 6.0.1 on 2026-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_alter_usage_event_idempotency_constraint_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='billed_cost_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='pricing_provenance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='properties',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='provider_cost_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='usage_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
