# Generated by Django 6.0.1 on 2026-02-02 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_wallettransaction_idempotency_key_and_more'),
        ('usage', '0006_add_pricing_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='billingperiod',
            name='idx_billing_period_status_end',
        ),
        migrations.RemoveConstraint(
            model_name='billingperiod',
            name='uq_billing_period',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billing_period',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='top_up_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='customers.topupattempt'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='BillingPeriod',
        ),
    ]
