# Generated by Django 6.0.1 on 2026-02-12 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
        ('usage', '0013_remove_invoice_from_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='runs.run'),
        ),
    ]
