# Generated by Django 6.0.1 on 2026-02-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_arrears_to_min_balance'),
        ('runs', '0001_initial'),
        ('tenants', '0007_rename_arrears_to_min_balance'),
        ('usage', '0014_add_run_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', '-effective_at'], name='idx_usage_tenant_effective'),
        ),
    ]
