# Generated by Django 6.0.1 on 2026-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0015_add_tenant_effective_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usageevent',
            name='group_keys',
        ),
        migrations.AddField(
            model_name='usageevent',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
