# Generated by Django 6.0.1 on 2026-04-14 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_card_slug_group_rate_updates'),
        ('tenants', '0010_tenant_group_label'),
        ('usage', '0016_remove_usageevent_group_keys_usageevent_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='pricing.card'),
        ),
        migrations.CreateModel(
            name='EventBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('added', 'Added'), ('reversed', 'Reversed')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('row_count', models.IntegerField()),
                ('author', models.CharField(max_length=255)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_batches', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_event_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usageevent',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='usage.eventbatch'),
        ),
    ]
