# Generated by Django 6.0.1 on 2026-04-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0017_usage_event_card_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='card_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
