# Generated by Django 6.0.6 on 2026-06-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0018_collapse_cost_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='usage_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
