# Generated by Django 6.0.1 on 2026-04-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0019_backfill_card_snapshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usageevent',
            name='event_type',
        ),
    ]
