# Generated by Django 6.0.6 on 2026-06-09 10:11

from django.db import migrations, models


def _backfill_owner(apps, schema_editor):
    from django.db.models import F
    UsageEvent = apps.get_model("usage", "UsageEvent")
    UsageEvent.objects.filter(billing_owner_id__isnull=True).update(billing_owner_id=F("customer_id"))


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0019_usageevent_usage_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='billing_owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(_backfill_owner, migrations.RunPython.noop),
    ]
