# Generated by Django 6.0.6 on 2026-06-09 15:41

from django.db import migrations, models


def _backfill(apps, schema_editor):
    schema_editor.execute(
        "UPDATE ubb_usage_event SET service_id = COALESCE(tags->>'service','') "
        "WHERE tags IS NOT NULL AND tags ? 'service'")
    schema_editor.execute(
        "UPDATE ubb_usage_event SET agent_id = COALESCE(tags->>'agent','') "
        "WHERE tags IS NOT NULL AND tags ? 'agent'")
    schema_editor.execute(
        "UPDATE ubb_usage_event SET product_id = COALESCE(tags->>'product','') "
        "WHERE product_id = '' AND tags IS NOT NULL AND tags ? 'product'")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('tasks', '0001_initial'),
        ('tenants', '0010_tenant_require_cost_card_coverage'),
        ('usage', '0020_usageevent_billing_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='agent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='service_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', 'product_id', 'service_id', 'agent_id', '-effective_at'], name='idx_usage_attribution'),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
