# Generated by Django 6.0.6 on 2026-06-12 09:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('runs', '0001_initial'),
        ('tenants', '0013_tenant_backfill_window_days'),
        ('usage', '0022_swap_tags_gin_to_jsonb_ops'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackfillDirtyPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
            ],
            options={
                'db_table': 'ubb_backfill_dirty_period',
            },
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='effective_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', 'created_at'], name='idx_usage_tenant_created'),
        ),
        migrations.AddField(
            model_name='backfilldirtyperiod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_dirty_periods', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='backfilldirtyperiod',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_dirty_periods', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='backfilldirtyperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'period_start'), name='uq_backfill_dirty_period'),
        ),
    ]
