# Generated by Django 6.0.1 on 2026-07-03 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('tenants', '0017_tenant_run_stale_seconds'),
        ('usage', '0023_backfilldirtyperiod_alter_usageevent_effective_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_owner_id', models.UUIDField(db_index=True)),
                ('run_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('estimate_micros', models.BigIntegerField(default=0)),
                ('estimate_exact', models.BooleanField(default=False)),
                ('held', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_raw_ingest_event',
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_rawingest_claim')],
            },
        ),
    ]
