# Generated by Django 6.0.1 on 2026-07-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0024_rawingestevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawingestevent',
            name='idempotency_key',
            field=models.CharField(max_length=500),
        ),
    ]
