# Generated by Django 6.0.6 on 2026-07-17 09:24

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('tasks', '0005_subtask_containment'),
        ('tenants', '0018_the_clean_cut_run_to_task'),
        ('usage', '0026_the_clean_cut_run_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='stop_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('stop_context__isnull', False)), fields=['stop_context'], name='idx_usage_stop_context'),
        ),
    ]
