# Generated by Django 6.0.1 on 2026-07-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('work', '0010_task_dim1_task_dim2_task_dim3_task_dim4_task_dim5_and_more'),
        ('tenants', '0022_tenantapikey_role'),
        ('usage', '0027_usageevent_stop_context'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usageevent',
            name='idx_usage_attribution',
        ),
        migrations.AddField(
            model_name='usageevent',
            name='dim1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='dim2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='dim3',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='dim4',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='dim5',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='dim6',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='subtask_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='task_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='provider',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', 'task_type', 'subtask_type', '-effective_at'], name='idx_usage_work_attribution'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['tenant', 'dim1', 'dim2', '-effective_at'], name='idx_usage_dim_attribution'),
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='agent_id',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='usageevent',
            name='service_id',
        ),
    ]
