# UBB integration, generated by ubb-codegen (renderer catalogue version 5).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 1
# sdk_major_version = 3
# target = "python_sdk"
# configuration_fingerprint = "sha256:3fdf63e7a384c45f77d8b3aa9357c840597609d0d13347ec057e6bb1bcdf0036"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "blocked"
# BLOCKED, NOT READY TO RUN. The structure is known, and at least one
# call lacks something it cannot run without. Those calls raise
# UBBIntegrationNotReady; the others run.

# Reported against this integration:

# diagnostic = "constant_measurement_not_renderable" · severity "blocking" · measurement "flat.call:flat_fee" · field "source_kind"
# The constant quantity is valid platform configuration, with its value
# declared. This Code Builder version cannot yet generate code that uses
# it, so the call is blocked until a version that can. Nothing in the
# declaration needs to change.

# Resolved from these declarations:
# task_type = "flat_rate_call"
# event_type = "flat.call" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds. Every one is required:
#   leave one out and Python raises TypeError at the call.
#   os.environ[...] is a credential. UBB withholds it from this file.
# A literal with no configured value, or one this Code Builder version
# cannot yet generate, is a state of a literal, not a fourth kind: it is
# written as a call that raises, saying which.

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from typing import Iterator, NoReturn

from ubb import RecordUsageResponse, StartedTask, UBBClient, UBBStopRequested

__all__ = [
    "UBBEnvironmentNotSet",
    "UBBIntegrationNotReady",
    "start_task",
    "unit_of_work",
    "record_flat_call",
    "backfill_flat_call",
]

_LOGGER = logging.getLogger("ubb_integration")

_CLIENT = None


# What building the client raises when a variable it needs is not set.
class UBBEnvironmentNotSet(RuntimeError):
    pass


# The client is built on first use, so importing this file needs no
# credentials.
def _client() -> UBBClient:
    global _CLIENT
    if _CLIENT is None:
        # Not a secret, and required: the base URL of the UBB API this code
        # calls. This file holds no address of its own.
        base_url = os.environ.get("UBB_BASE_URL")
        if not base_url:
            raise UBBEnvironmentNotSet(
                "UBB_BASE_URL is not set. Set it in the environment this code runs in."
            )
        _CLIENT = UBBClient(
            # A credential. Set it in the environment this code runs in, and never
            # write its value into a file.
            api_key=os.environ["UBB_API_KEY"],
            base_url=base_url,
        )
    return _CLIENT


# What a call raises while it is not ready to run. The header of this
# file says why.
class UBBIntegrationNotReady(RuntimeError):
    pass


def _not_ready(operation, readiness, *reasons) -> NoReturn:
    detail = "".join(f" {reason}" for reason in reasons)
    raise UBBIntegrationNotReady(
        f"{operation} ({readiness}) is not ready to run. The generated file's header says why.{detail}"
    )


def _not_renderable(name) -> NoReturn:
    raise UBBIntegrationNotReady(f"{name} is valid platform configuration that this Code Builder version cannot yet generate: see the blocking diagnostic in this file's header.")


# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is priced event by event, as each one is recorded.
def start_task(
    *,
    customer_id,
    idempotency_key,
) -> StartedTask:
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        # task_type = "flat_rate_call" · task_type "flat_rate_call"
        # task_type.pricing_mode = "event_priced" · task_type "flat_rate_call"
        # task_type.uncapped = true · task_type "flat_rate_call"
        task_type="flat_rate_call",
    )


_start_task = start_task


# The whole piece of work, as one block. Declare how it ended inside the
# block, with complete(), fail(outcome_reason) or cancel().
# This is the one place a stop is caught. The event that carried it was
# recorded and charged: never send it again. The stop is logged and
# raised again, so whatever runs this work can honour its scope.
@contextmanager
def unit_of_work(
    *,
    customer_id,
    idempotency_key,
) -> Iterator[StartedTask]:
    try:
        with _start_task(
            customer_id=customer_id,
            idempotency_key=idempotency_key,
        ) as task:
            yield task
    except UBBStopRequested as stop:
        _LOGGER.warning(
            "UBB requested a stop. The event sent as %r was recorded and must not be sent again: %r",
            stop.idempotency_key,
            stop.result,
        )
        raise


def _send_flat_call(
    *,
    customer_id,
    idempotency_key,
    task_id,
    searches,
    recorded_at,
    stop_behavior,
) -> RecordUsageResponse:
    # This call is not ready to run. See the header of this file.
    _not_ready("api_v1_metering_endpoints_record_usage", "blocked", "measurements.flat_fee is valid platform configuration that this Code Builder version cannot yet generate: see the blocking diagnostic in this file's header.")
    return _client().record_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        # event_type = "flat.call" · event_type "flat.call"
        # event_type.costing_method = "calculated" · event_type "flat.call"
        event_type="flat.call",
        measurements={
            # measurements = "flat_fee" · event_type "flat.call"
            # measurements.flat_fee.value_type = "decimal" · event_type "flat.call"
            # measurements.flat_fee.unit = "call" · event_type "flat.call"
            # measurements.flat_fee.required_for_costing = false · event_type "flat.call"
            "flat_fee": _not_renderable("measurements.flat_fee"),
            # measurements = "searches" · event_type "flat.call"
            # measurements.searches.value_type = "integer" · event_type "flat.call"
            # measurements.searches.unit = "search" · event_type "flat.call"
            # measurements.searches.required_for_costing = false · event_type "flat.call"
            "searches": searches,
        },
        recorded_at=recorded_at,
        stop_behavior=stop_behavior,
    )


# A stop is raised as UBBStopRequested, which is not an Exception, so
# your own `except Exception` cannot swallow it. Nothing here catches it.
def record_flat_call(
    *,
    customer_id,
    idempotency_key,
    task_id,
    searches,
) -> RecordUsageResponse:
    return _send_flat_call(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        searches=searches,
        recorded_at=None,
        stop_behavior="raise",
    )


# For work that has already happened. A stop is returned on the
# acknowledgement and not raised, so the rest of a backlog is still
# recorded. Read `stop` on what this returns.
def backfill_flat_call(
    *,
    customer_id,
    idempotency_key,
    task_id,
    searches,
    recorded_at,
) -> RecordUsageResponse:
    return _send_flat_call(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        searches=searches,
        recorded_at=recorded_at,
        stop_behavior="return",
    )
