# Generated by Django 6.0.1 on 2026-02-01 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_requests_per_minute', models.IntegerField(default=60)),
                ('max_concurrent_requests', models.IntegerField(default=10)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_risk_config',
            },
        ),
    ]
