# Generated by Django 6.0.6 on 2026-06-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gating', '0002_budget_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskconfig',
            name='max_cost_per_task_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
