# Generated by Django 6.0.6 on 2026-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gating', '0004_the_clean_cut_task_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskconfig',
            name='default_subtask_provider_cost_limit_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
