# Generated by Django 6.0.6 on 2026-07-17 14:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gating', '0007_announce_outbox_id'),
        ('tenants', '0019_two_position_enforcement_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('outcome', models.CharField(choices=[('reminted', 'Re-minted announcement'), ('flag_realigned', 'Stop flag re-aligned'), ('sweep_killed', 'Task swept into the kill flow')], max_length=20)),
                ('count', models.BigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_outcomes', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_patrol_outcome',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day', 'outcome'), name='uq_patrol_outcome_tenant_day')],
            },
        ),
    ]
