# UBB integration, generated by ubb-codegen (renderer catalogue version 5).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 1
# sdk_major_version = 3
# target = "python_sdk"
# configuration_fingerprint = "sha256:02829957644d3e567651bd1f34b3ed57845264d58d20c3b0989581cd843b2c52"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "scaffold"
# SCAFFOLD, NOT READY TO RUN. A kind of work or an Event Type is not
# selected or not declared. This file shows the shape of the lifecycle;
# the calls that are not ready raise UBBIntegrationNotReady.

# Reported against this integration:

# diagnostic = "task_type_not_selected" · severity "blocking" · task_type null · field null
# No kind of work is selected. Select one in the Code Builder.

# diagnostic = "event_type_not_selected" · severity "blocking" · event_type null · field null
# No Event Type is selected. Select at least one in the Code Builder.

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds. Every one is required:
#   leave one out and Python raises TypeError at the call.
#   os.environ[...] is a credential. UBB withholds it from this file.
# A literal with no configured value, or one this Code Builder version
# cannot yet generate, is a state of a literal, not a fourth kind: it is
# written as a call that raises, saying which.

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from typing import Iterator, NoReturn

from ubb import RecordUsageResponse, StartedTask, UBBClient, UBBStopRequested

__all__ = [
    "UBBEnvironmentNotSet",
    "UBBIntegrationNotReady",
    "start_task",
    "unit_of_work",
    "record_usage",
    "backfill_usage",
]

_LOGGER = logging.getLogger("ubb_integration")

_CLIENT = None


# What building the client raises when a variable it needs is not set.
class UBBEnvironmentNotSet(RuntimeError):
    pass


# The client is built on first use, so importing this file needs no
# credentials.
def _client() -> UBBClient:
    global _CLIENT
    if _CLIENT is None:
        # Not a secret, and required: the base URL of the UBB API this code
        # calls. This file holds no address of its own.
        base_url = os.environ.get("UBB_BASE_URL")
        if not base_url:
            raise UBBEnvironmentNotSet(
                "UBB_BASE_URL is not set. Set it in the environment this code runs in."
            )
        _CLIENT = UBBClient(
            # A credential. Set it in the environment this code runs in, and never
            # write its value into a file.
            api_key=os.environ["UBB_API_KEY"],
            base_url=base_url,
        )
    return _CLIENT


# What a call raises while it is not ready to run. The header of this
# file says why.
class UBBIntegrationNotReady(RuntimeError):
    pass


def _not_ready(operation, readiness, *reasons) -> NoReturn:
    detail = "".join(f" {reason}" for reason in reasons)
    raise UBBIntegrationNotReady(
        f"{operation} ({readiness}) is not ready to run. The generated file's header says why.{detail}"
    )


def _not_configured(name) -> NoReturn:
    raise UBBIntegrationNotReady(f"{name} has no configured value.")


# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
def start_task(
    *,
    customer_id,
    idempotency_key,
) -> StartedTask:
    # This call is not ready to run. See the header of this file.
    _not_ready("api_v1_task_endpoints_start_task", "scaffold", "task_type has no configured value.")
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_type=_not_configured("task_type"),
    )


_start_task = start_task


# The whole piece of work, as one block. Declare how it ended inside the
# block, with complete(), fail(outcome_reason) or cancel().
# This is the one place a stop is caught. The event that carried it was
# recorded and charged: never send it again. The stop is logged and
# raised again, so whatever runs this work can honour its scope.
@contextmanager
def unit_of_work(
    *,
    customer_id,
    idempotency_key,
) -> Iterator[StartedTask]:
    try:
        with _start_task(
            customer_id=customer_id,
            idempotency_key=idempotency_key,
        ) as task:
            yield task
    except UBBStopRequested as stop:
        _LOGGER.warning(
            "UBB requested a stop. The event sent as %r was recorded and must not be sent again: %r",
            stop.idempotency_key,
            stop.result,
        )
        raise


def _send_usage(
    *,
    customer_id,
    idempotency_key,
    task_id,
    recorded_at,
    stop_behavior,
) -> RecordUsageResponse:
    # This call is not ready to run. See the header of this file.
    _not_ready("api_v1_metering_endpoints_record_usage", "scaffold", "event_type has no configured value.")
    return _client().record_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        event_type=_not_configured("event_type"),
        recorded_at=recorded_at,
        stop_behavior=stop_behavior,
    )


# A stop is raised as UBBStopRequested, which is not an Exception, so
# your own `except Exception` cannot swallow it. Nothing here catches it.
def record_usage(
    *,
    customer_id,
    idempotency_key,
    task_id,
) -> RecordUsageResponse:
    return _send_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        recorded_at=None,
        stop_behavior="raise",
    )


# For work that has already happened. A stop is returned on the
# acknowledgement and not raised, so the rest of a backlog is still
# recorded. Read `stop` on what this returns.
def backfill_usage(
    *,
    customer_id,
    idempotency_key,
    task_id,
    recorded_at,
) -> RecordUsageResponse:
    return _send_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        recorded_at=recorded_at,
        stop_behavior="return",
    )
