# Generated by Django 6.0.1 on 2026-07-27 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('tenants', '0022_tenantapikey_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('access_fee_micros', models.BigIntegerField(default=0)),
                ('per_seat_micros', models.BigIntegerField(default=0)),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=5)),
                ('markup_percentage_micros', models.BigIntegerField(default=0)),
                ('fixed_uplift_micros', models.BigIntegerField(default=0)),
                ('stripe_access_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_access_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_seat_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_seat_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('pricing_version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_plan',
            },
        ),
        migrations.CreateModel(
            name='CustomerPlanAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_assignments', to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='plans.plan')),
            ],
            options={
                'db_table': 'ubb_customer_plan_assignment',
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uq_plan_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='customerplanassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer'), name='uq_plan_assignment_customer'),
        ),
    ]
