# Generated by Django 6.0.6 on 2026-07-16 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # App label moved 'tasks' -> 'work' (#196); see 0001_initial for why
    # this replaces its predecessor rather than re-running it.
    replaces = [("tasks", "0005_subtask_containment")]

    dependencies = [
        ('work', '0004_the_clean_cut_run_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='work.task'),
        ),
    ]
