# Generated by Django 6.0.1 on 2026-07-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    # App label moved 'tasks' -> 'work' (#196); see 0001_initial for why
    # this replaces its predecessor rather than re-running it.
    replaces = [("tasks", "0009_task_subtask_type_task_task_type_and_more")]

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('work', '0008_tasktype'),
        ('tenants', '0022_tenantapikey_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subtask_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'task_type', '-created_at'], name='idx_task_type_created'),
        ),
    ]
