# Generated by Django 6.0.1 on 2026-07-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    # App label moved 'tasks' -> 'work' (#196); see 0001_initial for why
    # this replaces its predecessor rather than re-running it.
    replaces = [("tasks", "0010_task_dim1_task_dim2_task_dim3_task_dim4_task_dim5_and_more")]

    dependencies = [
        ('work', '0009_task_subtask_type_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dim1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='dim2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='dim3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='dim4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='dim5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='dim6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
