# UBB integration, generated by ubb-codegen (renderer catalogue version 1).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 1
# sdk_major_version = 3
# target = "python_sdk"
# configuration_fingerprint = "sha256:8b6f61d8ce9f787f7338d19166d1eb6874716c12471a4b9f568f269b191127bf"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "complete"
# COMPLETE. Every call has what it needs to run.

# Reported against this integration:

# diagnostic = "source_path_convention_mismatch" · severity "advisory" · measurement "gemini.generate:candidate_tokens" · field "source_path"
# A declared path is spelled against the naming of its response shape.
# It is emitted exactly as declared. Check it against the client you
# call, or correct it with the request below.
# The request that fixes it. UBB never sends it for you:
# remediation_request = {"method":"PUT","route":"/api/v1/event-types/gemini.generate/measurements/candidate_tokens","operation_id":"api_v1_event_type_endpoints_declare_measurement","body":{"display_name":null,"value_type":null,"unit":null,"required_for_costing":null,"source_kind":null,"source_path":null}}

# Resolved from these declarations:
# task_type = "report_generation"
# grouping_field = "environment"
# subtask_type = "summarise"
# grouping_field = "phase"
# event_type = "gemini.generate" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"
# provider = "google"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds. Every one is required:
#   leave one out and Python raises TypeError at the call.
#   os.environ[...] is a credential. UBB withholds it from this file.
# A literal with no configured value is a state of a literal, not a
# fourth kind: it is written as a call that raises, naming what is
# missing.

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from typing import Iterator

from ubb import RecordUsageResponse, StartedTask, UBBClient, UBBStopRequested

__all__ = [
    "start_task",
    "unit_of_work",
    "start_subtask_summarise",
    "record_gemini_generate",
    "backfill_gemini_generate",
]

_LOGGER = logging.getLogger("ubb_integration")

_CLIENT = None


# The client is built on first use, so importing this file needs no
# credentials.
def _client() -> UBBClient:
    global _CLIENT
    if _CLIENT is None:
        _CLIENT = UBBClient(
            # A credential. Set it in the environment this code runs in, and never
            # write its value into a file.
            api_key=os.environ["UBB_API_KEY"],
            # Not a secret. Set it to point this file at another server; unset or
            # empty, the default is used.
            base_url=os.environ.get("UBB_BASE_URL") or "https://api.ubb.dev",
        )
    return _CLIENT


# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is priced event by event, as each one is recorded.
def start_task(
    *,
    customer_id,
    idempotency_key,
    environment,
) -> StartedTask:
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        # task_type = "report_generation" · task_type "report_generation"
        # task_type.pricing_mode = "event_priced" · task_type "report_generation"
        # task_type.uncapped = false · task_type "report_generation"
        # task_type.task_cogs_ceiling_micros = 5000000 · task_type "report_generation"
        task_type="report_generation",
        grouping_fields={
            # grouping_fields = "environment" · grouping_field "environment"
            "environment": environment,
        },
    )


_start_task = start_task


# The whole piece of work, as one block. Declare how it ended inside the
# block, with complete(), fail(outcome_reason) or cancel().
# This is the one place a stop is caught. The event that carried it was
# recorded and charged: never send it again. The stop is logged and
# raised again, so whatever runs this work can honour its scope.
@contextmanager
def unit_of_work(
    *,
    customer_id,
    idempotency_key,
    environment,
) -> Iterator[StartedTask]:
    try:
        with _start_task(
            customer_id=customer_id,
            idempotency_key=idempotency_key,
            environment=environment,
        ) as task:
            yield task
    except UBBStopRequested as stop:
        _LOGGER.warning(
            "UBB requested a stop. The event sent as %r was recorded and must not be sent again: %r",
            stop.idempotency_key,
            stop.result,
        )
        raise


# A Subtask is started only where you say so. UBB never infers one.
def start_subtask_summarise(
    *,
    customer_id,
    idempotency_key,
    parent_task_id,
    phase,
) -> StartedTask:
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        parent_task_id=parent_task_id,
        # task_type = "summarise" · subtask_type "summarise"
        # task_type.pricing_mode = "event_priced" · subtask_type "summarise"
        # task_type.uncapped = true · subtask_type "summarise"
        task_type="summarise",
        grouping_fields={
            # grouping_fields = "phase" · grouping_field "phase"
            "phase": phase,
        },
    )


def _send_gemini_generate(
    *,
    customer_id,
    idempotency_key,
    task_id,
    response,
    recorded_at,
    stop_behavior,
) -> RecordUsageResponse:
    return _client().record_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        # event_type = "gemini.generate" · event_type "gemini.generate"
        # event_type.costing_method = "calculated" · event_type "gemini.generate"
        # event_type.source_shape_id = "google.gemini.rest.v1" · event_type "gemini.generate"
        # event_type.response_shape_representation = "json" · event_type "gemini.generate"
        event_type="gemini.generate",
        # provider = "google" · provider "google"
        provider="google",
        measurements={
            # measurements = "candidate_tokens" · event_type "gemini.generate"
            # measurements.candidate_tokens.value_type = "integer" · event_type "gemini.generate"
            # measurements.candidate_tokens.unit = "token" · event_type "gemini.generate"
            # measurements.candidate_tokens.required_for_costing = true · event_type "gemini.generate"
            # measurements.candidate_tokens.source_path = ["usage_metadata","candidates_token_count"] · event_type "gemini.generate"
            "candidate_tokens": response["usage_metadata"]["candidates_token_count"],
            # measurements = "prompt_tokens" · event_type "gemini.generate"
            # measurements.prompt_tokens.value_type = "integer" · event_type "gemini.generate"
            # measurements.prompt_tokens.unit = "token" · event_type "gemini.generate"
            # measurements.prompt_tokens.required_for_costing = true · event_type "gemini.generate"
            # measurements.prompt_tokens.source_path = ["usageMetadata","promptTokenCount"] · event_type "gemini.generate"
            "prompt_tokens": response["usageMetadata"]["promptTokenCount"],
        },
        recorded_at=recorded_at,
        stop_behavior=stop_behavior,
    )


# A stop is raised as UBBStopRequested, which is not an Exception, so
# your own `except Exception` cannot swallow it. Nothing here catches it.
# This file never calls your supplier. Pass the response you already
# have.
def record_gemini_generate(
    *,
    customer_id,
    idempotency_key,
    task_id,
    response,
) -> RecordUsageResponse:
    return _send_gemini_generate(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        response=response,
        recorded_at=None,
        stop_behavior="raise",
    )


# For work that has already happened. A stop is returned on the
# acknowledgement and not raised, so the rest of a backlog is still
# recorded. Read `stop` on what this returns.
def backfill_gemini_generate(
    *,
    customer_id,
    idempotency_key,
    task_id,
    response,
    recorded_at,
) -> RecordUsageResponse:
    return _send_gemini_generate(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        response=response,
        recorded_at=recorded_at,
        stop_behavior="return",
    )
