# Generated by Django 6.0.1 on 2026-02-07 12:07

import apps.referrals.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_remove_customer_email'),
        ('tenants', '0005_add_products_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code_used', models.CharField(max_length=50)),
                ('attributed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reward_window_ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('snapshot_reward_type', models.CharField(choices=[('flat_fee', 'Flat Fee'), ('revenue_share', 'Revenue Share'), ('profit_share', 'Profit Share')], max_length=20)),
                ('snapshot_reward_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('snapshot_max_reward_micros', models.BigIntegerField(blank=True, null=True)),
                ('snapshot_estimated_cost_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('flat_fee_paid', models.BooleanField(default=False)),
                ('referred_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_referral',
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_type', models.CharField(choices=[('flat_fee', 'Flat Fee'), ('revenue_share', 'Revenue Share'), ('profit_share', 'Profit Share')], max_length=20)),
                ('reward_value', models.DecimalField(decimal_places=6, help_text='Micros for flat_fee, decimal percentage (e.g. 0.50) for share types', max_digits=20)),
                ('attribution_window_days', models.IntegerField(default=30, help_text='How long a referral link stays valid for attribution')),
                ('reward_window_days', models.IntegerField(blank=True, help_text='How long referrer earns from a referral. Null = forever', null=True)),
                ('max_reward_micros', models.BigIntegerField(blank=True, help_text='Optional cap on total earnings per referral', null=True)),
                ('estimated_cost_percentage', models.DecimalField(blank=True, decimal_places=4, help_text="Fallback for profit-share: tenant's cost as fraction of revenue (e.g. 0.20)", max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deactivated', 'Deactivated')], default='active', max_length=15)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_program', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_referral_program',
            },
        ),
        migrations.CreateModel(
            name='ReferralRewardAccumulator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_earned_micros', models.BigIntegerField(default=0)),
                ('total_referred_spend_micros', models.BigIntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_accumulator', to='referrals.referral')),
            ],
            options={
                'db_table': 'ubb_referral_reward_accumulator',
            },
        ),
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.CharField(db_index=True, default=apps.referrals.models._generate_referral_code, max_length=20, unique=True)),
                ('referral_link_token', models.CharField(db_index=True, default=apps.referrals.models._generate_link_token, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrer_profile', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_referrer',
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referrer'),
        ),
        migrations.CreateModel(
            name='ReferralRewardLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('referred_spend_micros', models.BigIntegerField()),
                ('raw_cost_micros', models.BigIntegerField(default=0)),
                ('reward_micros', models.BigIntegerField()),
                ('calculation_method', models.CharField(choices=[('actual_cost', 'Actual Cost'), ('estimated_cost', 'Estimated Cost'), ('flat_fee', 'Flat Fee')], max_length=20)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_ledger', to='referrals.referral')),
            ],
            options={
                'db_table': 'ubb_referral_reward_ledger',
                'indexes': [models.Index(fields=['referral', 'period_start'], name='idx_reward_ledger_referral_period')],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['tenant', 'status'], name='idx_referral_tenant_status'),
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('tenant', 'referred_customer'), name='uq_referral_tenant_referred_customer'),
        ),
    ]
