# Generated by Django 6.0.1 on 2026-02-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralrewardledger',
            new_name='idx_rwdledger_ref_period',
            old_name='idx_reward_ledger_referral_period',
        ),
    ]
