# Generated by Django 6.0.1 on 2026-02-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_rename_idx_reward_ledger_referral_period_idx_rwdledger_ref_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralprogram',
            name='max_referrals_per_day',
            field=models.IntegerField(blank=True, help_text='Maximum referrals per referrer per day. Null = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='min_customer_age_hours',
            field=models.IntegerField(blank=True, help_text='Minimum age of referred customer account in hours. Null = no minimum.', null=True),
        ),
    ]
