# Generated by Django 6.0.1 on 2026-02-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_referralprogram_max_referrals_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrewardaccumulator',
            name='last_payout_amount_micros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralrewardaccumulator',
            name='last_payout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
