# Generated by Django 6.0.1 on 2026-02-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_add_payout_tracking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='referralrewardledger',
            constraint=models.UniqueConstraint(fields=('referral', 'period_start'), name='uq_rwdledger_referral_period'),
        ),
    ]
