# UBB integration, generated by ubb-codegen (renderer catalogue version 7).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 2
# sdk_major_version = null
# target = "shell_http"
# configuration_fingerprint = "sha256:6779c5c2b184b32a1f1eb67fd320aba53b0b46abe85a217e5840452717b81b6f"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "complete"
# COMPLETE. Every call has what it needs to run.

# Nothing is reported against this integration.

# Resolved from these declarations:
# task_type = "report"
# event_type = "reply.sent" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds, passed as name=value.
#   Leave out one a call requires, or pass it empty, and the call returns
#   UBB_EXIT_USAGE before anything is sent, naming it.
#   $UBB_API_KEY is a credential. UBB withholds it from this file.
# A literal with no configured value, or one this Code Builder version
# cannot yet generate, is a state of a literal, not a fourth kind: it is
# written as a call that raises, saying which.

# Source this file from the script that does the work:
#   . ./ubb_integration.sh
# It requires curl and jq, and checks both before the first request. It
# sets no shell option and never exits the shell that sourced it: every
# function returns a status, and you check it. set -e is not relied on.

# The statuses a function returns. A stop has a status of its own, and no
# other failure is ever returned as it. A request that fails returns the
# status curl gave it; every other failure returns one of these.
UBB_EXIT_STOP_REQUESTED=20
UBB_EXIT_USAGE=64
UBB_EXIT_VALUE_REFUSED=65
UBB_EXIT_TOOL_UNAVAILABLE=69
UBB_EXIT_RESPONSE_UNREADABLE=76
UBB_EXIT_NOT_CONFIGURED=78

# What a call leaves behind for the code that called it. They are shell
# variables this file sets, not settings you supply, and it exports none.
# UBB_TASK_ID is the id of the work the last start created.
# UBB_RESPONSE is the response to the most recent call. The next call
# overwrites it.
# UBB_STOP_REQUESTED is the stop the most recent record met, or the Task
# ubb_run_task ran, as one line of JSON. It is empty where none was met:
# each clears it before it does anything else, so a stop is never an
# earlier call's.
# They are set in your shell, so never call a function of this file
# inside $( ) or a pipeline: both run it in a subshell, and what it set is
# lost.
UBB_TASK_ID=
UBB_RESPONSE=
UBB_STOP_REQUESTED=

_ubb_ready=
_ubb_closed=
_ubb_stop_met=

# Checks, once, that jq and curl can do what this file asks of them. It
# contacts nothing and creates nothing.
_ubb_preflight() {
  [ -z "$_ubb_ready" ] || return 0
  command -v jq >/dev/null 2>&1 || {
    printf '%s\n' 'This file requires jq, and none is installed.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  _ubb_probe=0
  jq --null-input --arg probe_text 1 --argjson probe_json 1 --raw-output --compact-output \
    --from-file /dev/stdin >/dev/null 2>&1 <<'UBB_JQ' || _ubb_probe=$?
  # A program of this file's own form: read from standard input, holding
  # comments, passing each option and using each form its programs use, and
  # naming each function they call in a branch that is never taken.
  def probe_definition($first; $second): $first + $second;
  [
    $probe_text,
    $probe_json,
    probe_definition(1; 2),
    (1 as $probe_value | $probe_value),
    (if false then 1 elif false then 2 else 3 end),
    ([foreach (1, 2) as $probe_item (0; . + $probe_item; .)]),
    (if false then [add, empty, endswith("probe"), error("probe"), explode, fromjson, has("probe"), last, length, map(.), range(0; 1), select(true), split("probe"), tojson, type] else 1 end)
  ]
UBB_JQ
  [ "$_ubb_probe" -eq 0 ] || {
    printf '%s\n' 'The installed jq cannot run the programs this file hands it. jq 1.5 or later can.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  command -v curl >/dev/null 2>&1 || {
    printf '%s\n' 'This file requires curl, and none is installed.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  curl --fail-with-body --version >/dev/null 2>&1 || {
    printf '%s\n' 'The installed curl has no --fail-with-body. curl 7.76 or later has it.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  _ubb_ready=1
}

# Both variables are required, and are read each time a request is made.
_ubb_environment() {
  # Not a secret, and required: the base URL of the UBB API this code
  # calls. This file holds no address of its own.
  [ -n "${UBB_BASE_URL:-}" ] || {
    printf '%s\n' 'UBB_BASE_URL is not set. Set it in the environment this code runs in.' >&2
    return "$UBB_EXIT_NOT_CONFIGURED"
  }
  # A credential. Set it in the environment this code runs in, and never
  # write its value into a file.
  [ -n "${UBB_API_KEY:-}" ] || {
    printf '%s\n' 'UBB_API_KEY is not set. Set it in the environment this code runs in.' >&2
    return "$UBB_EXIT_NOT_CONFIGURED"
  }
}

# Sends one request. The credential goes to curl on standard input, so it
# is never an argument another process can list. The response is left in
# UBB_RESPONSE. A response that is not a success is printed, and the
# status curl gave it is returned.
_ubb_post() {
  _ubb_sent=0
  UBB_RESPONSE=$(printf 'Authorization: Bearer %s\n' "$UBB_API_KEY" | curl \
    --silent --show-error --fail-with-body \
    --request POST \
    --header @- \
    --header 'Content-Type: application/json' \
    --data-binary "$2" \
    "${UBB_BASE_URL%/}$1"
  ) || _ubb_sent=$?
  [ "$_ubb_sent" -ne 0 ] || return 0
  [ -z "$UBB_RESPONSE" ] || printf '%s\n' "$UBB_RESPONSE" >&2
  [ "$_ubb_sent" -ne "$UBB_EXIT_STOP_REQUESTED" ] || _ubb_sent=1
  return "$_ubb_sent"
}

# The id of the work a start created is read off the response and left in
# UBB_TASK_ID.
_ubb_jq_task_id() {
  jq --raw-output --null-input \
    --arg response "$UBB_RESPONSE" \
    --from-file /dev/stdin <<'UBB_JQ'
  ($response | fromjson) as $started
  | if ($started | type) != "object" or ($started.task_id | type) != "string"
       or $started.task_id == ""
    then error("the response carries no task_id")
    else $started.task_id end
UBB_JQ
}

_ubb_started() {
  UBB_TASK_ID=$(_ubb_jq_task_id) || {
    printf '%s\n' 'the response is not the acknowledgement this call expects.' >&2
    return "$UBB_EXIT_RESPONSE_UNREADABLE"
  }
}

# A stop arrives on a successful response, so it is read off the
# acknowledgement and never off the HTTP status. The event that carried
# it was recorded and charged: never send it again. Its metadata is left
# in UBB_STOP_REQUESTED and the reserved status is returned.
# The metadata carries the stop's fields as the acknowledgement holds
# them, and works nothing out: what does not apply stays null, and the
# bound and the amount measured against it keep the digits and the sign
# UBB wrote, never the number jq would make of them.
_ubb_jq_stop() {
  jq --raw-output --null-input \
    --arg response "$UBB_RESPONSE" \
    --arg idempotency_key "$1" \
    --from-file /dev/stdin <<'UBB_JQ'
  def ubb_escapes_next:
    if endswith("\\") then
      explode as $c
      | ([range(0; $c | length) | select($c[.] != 92)] | last) as $kept
      | ((($c | length) - (if $kept == null then 0 else $kept + 1 end)) % 2) == 1
    else false end;
  def ubb_inside_flags:
    [foreach .[] as $part ([false, false];
      [.[1], (if .[1] then ($part | ubb_escapes_next) else true end)];
      .[0])];
  def ubb_without($character):
    split($character) | add // "";
  def ubb_marked($character):
    split($character)
    | if length == 0 then ""
      else [.[0], (.[1:][] | ("\u0001" + $character + "\u0001"), .)] | add end;
  def ubb_scalars_quoted:
    ubb_without(" ") | ubb_without("\t") | ubb_without("\n") | ubb_without("\r")
    | ubb_marked(",") | ubb_marked(":") | ubb_marked("[") | ubb_marked("]") | ubb_marked("{") | ubb_marked("}")
    | split("\u0001")
    | map(if . == "" or . == "," or . == ":" or . == "[" or . == "]" or . == "{" or . == "}"
      then . else "\"" + . + "\"" end)
    | add // "";
  def ubb_as_written($parts; $inside):
    [range(0; $parts | length) as $at
      | (if $at > 0 then "\"" else empty end),
        (if $inside[$at] then $parts[$at] else ($parts[$at] | ubb_scalars_quoted) end)]
    | add;
  def ubb_whole:
    explode
    | (if .[0] == 45 then .[1:] else . end)
    | length > 0 and (map(select(. < 48 or . > 57)) | length) == 0
      and (length == 1 or .[0] != 48);
  def ubb_text($acknowledgement; $name):
    if ($acknowledgement | has($name))
       and ($acknowledgement[$name] == null or ($acknowledgement[$name] | type) == "string")
    then $acknowledgement[$name] | tojson
    else error("the acknowledgement holds no text or null at " + $name) end;
  def ubb_figure($acknowledgement; $written; $name):
    if ($acknowledgement | has($name)) and $acknowledgement[$name] == null then "null"
    elif ($acknowledgement | has($name)) and ($acknowledgement[$name] | type) == "number"
         and ($written[$name] | type) == "string" and ($written[$name] | ubb_whole)
    then $written[$name]
    else error("the acknowledgement holds no whole number or null at " + $name) end;
  ($response | fromjson) as $acknowledgement
  | if ($acknowledgement | type) != "object"
       or ($acknowledgement.event_id | type) != "string"
    then error("the acknowledgement carries no event_id")
    elif $acknowledgement.stop == true
    then ($response | split("\"")) as $parts
    | ($parts | ubb_inside_flags) as $inside
    | (ubb_as_written($parts; $inside) | fromjson) as $written
    | "{\"event_id\":" + ($acknowledgement.event_id | tojson)
      + ",\"idempotency_key\":" + ($idempotency_key | tojson)
      + ",\"stop_scope\":" + ($acknowledgement.stop_scope | tojson)
      + ",\"stop_reason\":" + ($acknowledgement.stop_reason | tojson)
      + ",\"trigger_source\":" + ubb_text($acknowledgement; "trigger_source")
      + ",\"stop_bound_micros\":" + ubb_figure($acknowledgement; $written; "stop_bound_micros")
      + ",\"stop_measured_micros\":" + ubb_figure($acknowledgement; $written; "stop_measured_micros")
      + "}"
    else "null" end
UBB_JQ
}

_ubb_acknowledge() {
  _ubb_stop=$(_ubb_jq_stop "$1") || {
    printf '%s\n' 'the response is not the acknowledgement this call expects.' >&2
    return "$UBB_EXIT_RESPONSE_UNREADABLE"
  }
  [ "$_ubb_stop" != null ] || return 0
  UBB_STOP_REQUESTED=$_ubb_stop
  _ubb_stop_met=$_ubb_stop
  return "$UBB_EXIT_STOP_REQUESTED"
}

# What a call prints, before returning UBB_EXIT_USAGE, for a parameter it
# was not given, was given empty, or does not have.
_ubb_missing() {
  printf '%s: %s %s\n' "$1" "$2" 'is required, and was left out or passed empty.' >&2
}

_ubb_unknown() {
  printf '%s: %s %s\n' "$1" "${2%%=*}" 'is not a parameter of this call. Pass each one as name=value.' >&2
}

# A quantity is a whole number, carried exactly or refused as
# UBB_EXIT_VALUE_REFUSED.
_ubb_whole_number() {
  case ${3#-} in
    '' | *[!0-9]* | 0?* | ????????????????*)
      printf '%s: %s %s\n' "$1" "$2" 'is not a whole number of at most 15 digits, which is what is carried exactly.' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
}

# A value written into a URL is one that needs no encoding there, or it
# is refused as UBB_EXIT_VALUE_REFUSED.
_ubb_url_value() {
  case $3 in
    . | .. | *[!A-Za-z0-9._~-]*)
      printf '%s: %s %s\n' "$1" "$2" 'cannot be written into a URL as it stands.' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
}

_ubb_jq_body_start_task() {
  jq --compact-output --null-input \
    --arg p_customer_id "$_ubb_p_customer_id" \
    --arg p_idempotency_key "$_ubb_p_idempotency_key" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "customer_id": $p_customer_id,
    "idempotency_key": $p_idempotency_key,
    # task_type = "report" · task_type "report"
    # task_type.pricing_mode = "fixed" · task_type "report"
    # task_type.uncapped = true · task_type "report"
    "task_type": "report"
  }
UBB_JQ
}

# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is sold whole, at one agreed price. Declaring it
# delivered is what creates the charge, once. A retried start with a new
# idempotency_key is a second piece of work, and a second charge.
ubb_start_task() {
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_customer_id=
  _ubb_p_idempotency_key=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      customer_id=*) _ubb_p_customer_id=${_ubb_argument#customer_id=} ;;
      idempotency_key=*) _ubb_p_idempotency_key=${_ubb_argument#idempotency_key=} ;;
      *)
        _ubb_unknown ubb_start_task "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_customer_id" ] || {
    _ubb_missing ubb_start_task customer_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_idempotency_key" ] || {
    _ubb_missing ubb_start_task idempotency_key
    return "$UBB_EXIT_USAGE"
  }
  _ubb_body=$(_ubb_jq_body_start_task) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/tasks' "$_ubb_body" || return $?
  _ubb_started || return $?
  UBB_STOP_REQUESTED=
  _ubb_stop_met=
}

# The whole of a Task, as one command you name. It is run with the Task's
# task_id as its one argument. Declare how the work ended inside it, with
# ubb_close_task: nothing here declares an outcome for you.
# This is the one place a stop is acted on, and it is acted on whatever
# the work then returned. The event that carried it was recorded and
# charged: never send it again. The stop is logged and the reserved
# status returned, so whatever runs this work can honour its scope.
# Work that returns a failure is not declared failed: a status is not
# evidence of how the work went. Its status is returned as it is, and a
# Task with no outcome declared is left open and said to be. Work that
# returns success having declared none is left open too, and that is
# returned as UBB_EXIT_USAGE.
ubb_run_task() {
  UBB_STOP_REQUESTED=
  _ubb_stop_met=
  [ "$#" -ge 1 ] || {
    printf '%s: %s\n' ubb_run_task 'the first argument is the command that does the work.' >&2
    return "$UBB_EXIT_USAGE"
  }
  _ubb_work=$1
  shift
  ubb_start_task "$@" || return $?
  set -- "$_ubb_work" "$UBB_TASK_ID"
  "$1" "$2" && set -- "$1" "$2" 0 || set -- "$1" "$2" "$?"
  if [ "$3" -eq "$UBB_EXIT_STOP_REQUESTED" ] || [ -n "$_ubb_stop_met" ]; then
    UBB_STOP_REQUESTED=$_ubb_stop_met
    printf '%s\n' 'UBB requested a stop. The event that carried it was recorded and must not be sent again.' >&2
    printf '%s %s\n' stop_requested "${UBB_STOP_REQUESTED:-null}" >&2
    return "$UBB_EXIT_STOP_REQUESTED"
  fi
  case " $_ubb_closed " in
    *" $2 "*) return "$3" ;;
  esac
  if [ "$3" -eq 0 ]; then
    printf '%s: %s\n' ubb_run_task 'the work ended without declaring an outcome, and is left open. Declare one with ubb_close_task.' >&2
    return "$UBB_EXIT_USAGE"
  fi
  printf '%s: %s\n' ubb_run_task 'the work returned a failure and declared no outcome. None was declared for it: the Task is left open.' >&2
  return "$3"
}

_ubb_jq_body_record_reply_sent() {
  jq --compact-output --null-input \
    --arg p_customer_id "$_ubb_p_customer_id" \
    --arg p_idempotency_key "$_ubb_p_idempotency_key" \
    --arg p_task_id "$_ubb_p_task_id" \
    --argjson p_replies "$_ubb_p_replies" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "customer_id": $p_customer_id,
    "idempotency_key": $p_idempotency_key,
    "task_id": $p_task_id,
    # event_type = "reply.sent" · event_type "reply.sent"
    # event_type.costing_method = "calculated" · event_type "reply.sent"
    "event_type": "reply.sent",
    "measurements": {
      # measurements = "replies" · event_type "reply.sent"
      # measurements.replies.value_type = "integer" · event_type "reply.sent"
      # measurements.replies.unit = "reply" · event_type "reply.sent"
      # measurements.replies.required_for_costing = true · event_type "reply.sent"
      "replies": $p_replies
    }
  }
UBB_JQ
}

# A stop is returned as UBB_EXIT_STOP_REQUESTED, with the event recorded.
# Return it from your own code unchanged, up to whatever runs the work.
ubb_record_reply_sent() {
  UBB_STOP_REQUESTED=
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_customer_id=
  _ubb_p_idempotency_key=
  _ubb_p_task_id=
  _ubb_p_replies=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      customer_id=*) _ubb_p_customer_id=${_ubb_argument#customer_id=} ;;
      idempotency_key=*) _ubb_p_idempotency_key=${_ubb_argument#idempotency_key=} ;;
      task_id=*) _ubb_p_task_id=${_ubb_argument#task_id=} ;;
      replies=*) _ubb_p_replies=${_ubb_argument#replies=} ;;
      *)
        _ubb_unknown ubb_record_reply_sent "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_customer_id" ] || {
    _ubb_missing ubb_record_reply_sent customer_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_idempotency_key" ] || {
    _ubb_missing ubb_record_reply_sent idempotency_key
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_task_id" ] || {
    _ubb_missing ubb_record_reply_sent task_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_replies" ] || {
    _ubb_missing ubb_record_reply_sent replies
    return "$UBB_EXIT_USAGE"
  }
  _ubb_whole_number ubb_record_reply_sent replies "$_ubb_p_replies" || return $?
  _ubb_body=$(_ubb_jq_body_record_reply_sent) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/metering/usage' "$_ubb_body" || return $?
  _ubb_acknowledge "$_ubb_p_idempotency_key"
}

_ubb_jq_body_close_task() {
  jq --compact-output --null-input \
    --arg p_outcome "$_ubb_p_outcome" \
    --arg p_outcome_reason "$_ubb_p_outcome_reason" \
    --arg p_reason_detail "$_ubb_p_reason_detail" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "outcome": $p_outcome
  }
  + (if $p_outcome_reason == "" then {} else {"outcome_reason": $p_outcome_reason} end)
  + (if $p_reason_detail == "" then {} else {"reason_detail": $p_reason_detail} end)
UBB_JQ
}

# outcome is delivered, failed or cancelled, and UBB never guesses it. A
# failure also says why: pass outcome_reason, and reason_detail if you
# have a sentence to go with it.
ubb_close_task() {
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_task_id=
  _ubb_p_outcome=
  _ubb_p_outcome_reason=
  _ubb_p_reason_detail=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      task_id=*) _ubb_p_task_id=${_ubb_argument#task_id=} ;;
      outcome=*) _ubb_p_outcome=${_ubb_argument#outcome=} ;;
      outcome_reason=*) _ubb_p_outcome_reason=${_ubb_argument#outcome_reason=} ;;
      reason_detail=*) _ubb_p_reason_detail=${_ubb_argument#reason_detail=} ;;
      *)
        _ubb_unknown ubb_close_task "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_task_id" ] || {
    _ubb_missing ubb_close_task task_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_outcome" ] || {
    _ubb_missing ubb_close_task outcome
    return "$UBB_EXIT_USAGE"
  }
  _ubb_url_value ubb_close_task task_id "$_ubb_p_task_id" || return $?
  _ubb_body=$(_ubb_jq_body_close_task) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/tasks/'"$_ubb_p_task_id"'/close' "$_ubb_body" || return $?
  _ubb_closed="$_ubb_closed $_ubb_p_task_id"
}
