# Generated by Django 6.0.1 on 2026-02-12 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_remove_topup_to_billing'),
        ('tenants', '0006_add_run_hard_stop_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('killed', 'Killed')], db_index=True, default='active', max_length=20)),
                ('total_cost_micros', models.BigIntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('balance_snapshot_micros', models.BigIntegerField()),
                ('cost_limit_micros', models.BigIntegerField(blank=True, null=True)),
                ('hard_stop_balance_micros', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('external_run_id', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_run',
                'indexes': [models.Index(fields=['customer', '-created_at'], name='idx_run_customer_created'), models.Index(fields=['tenant', 'status'], name='idx_run_tenant_status')],
            },
        ),
    ]
