# Generated by Django 6.0.6 on 2026-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('runs', '0002_run_billing_owner_id_run_last_event_at_run_task_id_and_more'),
        ('tenants', '0016_tenant_enforcement_mode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['billing_owner_id', 'status'], name='idx_run_owner_status'),
        ),
    ]
