from enum import Enum

class WebhookDeliveryResponseEventType(str, Enum):
    AUTO_TOP_UP_REQUIRES_ACTION = "auto_top_up.requires_action"
    CREDIT_GRANT_EXPIRED = "credit_grant.expired"
    CREDIT_GRANT_EXPIRING = "credit_grant.expiring"
    CUSTOMER_DELETED = "customer.deleted"
    CUSTOMER_SPEND_POOL_THRESHOLD_REACHED = "customer_spend_pool.threshold_reached"
    CUSTOMER_STOPPED = "customer.stopped"
    CUSTOMER_STOP_CLEARED = "customer.stop_cleared"
    CUSTOMER_SUSPENDED = "customer.suspended"
    CUSTOMER_UNPROFITABLE = "customer.unprofitable"
    INVITATION_CREATED = "invitation.created"
    INVITATION_REVOKED = "invitation.revoked"
    MEMBER_ACTIVATED = "member.activated"
    PROVIDER_COST_SPIKE = "provider.cost_spike"
    REFERRAL_CREATED = "referral.created"
    REFERRAL_EXPIRED = "referral.expired"
    REFERRAL_PAYOUT_DUE = "referral.payout_due"
    REFERRAL_REWARD_EARNED = "referral.reward_earned"
    REFUND_REQUESTED = "refund.requested"
    SANDBOX_RESET_COMPLETED = "sandbox.reset_completed"
    SUBTASK_EXPIRED = "subtask.expired"
    SUBTASK_KILLED = "subtask.killed"
    TASK_EXPIRED = "task.expired"
    TASK_KILLED = "task.killed"
    TENANT_API_KEY_CREATED = "tenant.api_key_created"
    TENANT_API_KEY_REVOKED = "tenant.api_key_revoked"
    TENANT_API_KEY_ROTATED = "tenant.api_key_rotated"
    TOP_UP_REQUESTED = "top_up.requested"
    USAGE_INVOICE_PUSHED = "usage_invoice.pushed"
    USAGE_INVOICE_PUSH_FAILED_PERMANENT = "usage_invoice.push_failed_permanent"
    USAGE_RECORDED = "usage.recorded"
    USAGE_REFUNDED = "usage.refunded"
    WALLET_BALANCE_CRITICAL = "wallet.balance_critical"
    WALLET_BALANCE_LOW = "wallet.balance_low"
    WALLET_BALANCE_OVERAGE = "wallet.balance_overage"
    WALLET_POLICY_SOFT_FLOOR_CLEARED = "wallet_policy.soft_floor_cleared"
    WALLET_POLICY_SOFT_FLOOR_CROSSED = "wallet_policy.soft_floor_crossed"
    WITHDRAWAL_REQUESTED = "withdrawal.requested"

    def __str__(self) -> str:
        return str(self.value)
