# UBB integration, generated by ubb-codegen (renderer catalogue version 1).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 1
# sdk_major_version = 3
# target = "python_sdk"
# configuration_fingerprint = null
# DRAFT PREVIEW. Resolved from draft declarations, not from published
# ones. It is stored nowhere, has no configuration_fingerprint, and cannot
# be verified.

# readiness = "complete"
# COMPLETE. Every call has what it needs to run.

# Nothing is reported against this integration.

# Resolved from these declarations:
# task_type = "report_generation"
# event_type = "chat.completion"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds. Every one is required:
#   leave one out and Python raises TypeError at the call.
#   os.environ[...] is a credential. UBB withholds it from this file.
# A literal with no configured value is a state of a literal, not a
# fourth kind: it is written as a call that raises, naming what is
# missing.

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from typing import Iterator

from ubb import RecordUsageResponse, StartedTask, UBBClient, UBBStopRequested

__all__ = [
    "UBBEnvironmentNotSet",
    "start_task",
    "unit_of_work",
    "record_chat_completion",
    "backfill_chat_completion",
]

_LOGGER = logging.getLogger("ubb_integration")

_CLIENT = None


# What building the client raises when a variable it needs is not set.
class UBBEnvironmentNotSet(RuntimeError):
    pass


# The client is built on first use, so importing this file needs no
# credentials.
def _client() -> UBBClient:
    global _CLIENT
    if _CLIENT is None:
        # Not a secret, and required: the base URL of the UBB API this code
        # calls. This file holds no address of its own.
        base_url = os.environ.get("UBB_BASE_URL")
        if not base_url:
            raise UBBEnvironmentNotSet(
                "UBB_BASE_URL is not set. Set it in the environment this code runs in."
            )
        _CLIENT = UBBClient(
            # A credential. Set it in the environment this code runs in, and never
            # write its value into a file.
            api_key=os.environ["UBB_API_KEY"],
            base_url=base_url,
        )
    return _CLIENT


# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is priced event by event, as each one is recorded.
def start_task(
    *,
    customer_id,
    idempotency_key,
) -> StartedTask:
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        # task_type = "report_generation" · task_type "report_generation"
        # task_type.pricing_mode = "event_priced" · task_type "report_generation"
        # task_type.uncapped = true · task_type "report_generation"
        task_type="report_generation",
    )


_start_task = start_task


# The whole piece of work, as one block. Declare how it ended inside the
# block, with complete(), fail(outcome_reason) or cancel().
# This is the one place a stop is caught. The event that carried it was
# recorded and charged: never send it again. The stop is logged and
# raised again, so whatever runs this work can honour its scope.
@contextmanager
def unit_of_work(
    *,
    customer_id,
    idempotency_key,
) -> Iterator[StartedTask]:
    try:
        with _start_task(
            customer_id=customer_id,
            idempotency_key=idempotency_key,
        ) as task:
            yield task
    except UBBStopRequested as stop:
        _LOGGER.warning(
            "UBB requested a stop. The event sent as %r was recorded and must not be sent again: %r",
            stop.idempotency_key,
            stop.result,
        )
        raise


def _send_chat_completion(
    *,
    customer_id,
    idempotency_key,
    task_id,
    response,
    recorded_at,
    stop_behavior,
) -> RecordUsageResponse:
    return _client().record_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        # event_type = "chat.completion" · event_type "chat.completion"
        # event_type.costing_method = "calculated" · event_type "chat.completion"
        # event_type.source_shape_id = "openai.responses.python.v1" · event_type "chat.completion"
        # event_type.response_shape_representation = "python_object" · event_type "chat.completion"
        event_type="chat.completion",
        measurements={
            # measurements = "input_tokens" · event_type "chat.completion"
            # measurements.input_tokens.value_type = "integer" · event_type "chat.completion"
            # measurements.input_tokens.unit = "token" · event_type "chat.completion"
            # measurements.input_tokens.required_for_costing = true · event_type "chat.completion"
            # measurements.input_tokens.source_path = ["usage","input_tokens"] · event_type "chat.completion"
            "input_tokens": response.usage.input_tokens,
        },
        recorded_at=recorded_at,
        stop_behavior=stop_behavior,
    )


# A stop is raised as UBBStopRequested, which is not an Exception, so
# your own `except Exception` cannot swallow it. Nothing here catches it.
# This file never calls your supplier. Pass the response you already
# have.
def record_chat_completion(
    *,
    customer_id,
    idempotency_key,
    task_id,
    response,
) -> RecordUsageResponse:
    return _send_chat_completion(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        response=response,
        recorded_at=None,
        stop_behavior="raise",
    )


# For work that has already happened. A stop is returned on the
# acknowledgement and not raised, so the rest of a backlog is still
# recorded. Read `stop` on what this returns.
def backfill_chat_completion(
    *,
    customer_id,
    idempotency_key,
    task_id,
    response,
    recorded_at,
) -> RecordUsageResponse:
    return _send_chat_completion(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        response=response,
        recorded_at=recorded_at,
        stop_behavior="return",
    )
