#!/usr/bin/env python3
"""The contract breaking-change gate — cumulative, against an immutable baseline.

Run from the git root (CI's `contract` job runs exactly this):

    python openapi/contract_gate.py                 # the gate
    python openapi/contract_gate.py --baseline main --emit   # authoring

**The gate** compares `api-v1-launch` against the working tree, so every break
since the contract was published is proven to have been reviewed — not merely
that each step was reviewed against the step before it. That distinction is not
academic: #129's `contract` job went red on seven path removals, the pull request
was merged anyway, and no later per-pull-request comparison could ever see them
again, because each one only ever looked one commit back.

**Authoring** a slice's new entries compares previous `main` against the proposal
(`--baseline main --emit`), so a slice does not re-derive every earlier entry.
`--emit` prints the lines to paste, split by the file they belong in. Entries are
generated by running this tool; a hand-typed finding is a defect (§7.2).

Two verdicts fail the gate:

- **unreviewed** — a break no committed entry covers.
- **inert** — a committed entry that covers no finding *at its own level*.
  `--err-ignore` only ever suppresses ERR findings and `--warn-ignore` only WARN
  ones, so a line in the wrong file silently does nothing. That has happened
  here: seven WARN-level lines sat in the ERR file suppressing nothing while two
  ERR findings went unrecorded. An entry that does nothing now turns CI red
  instead of lying quietly — which is also what keeps human metadata on `#`
  comment lines, since prose matches no finding either.

The suppression files cannot reach zero while the baseline is `api-v1-launch`:
the differences from it are real, intentional and permanent until slice 8 tags a
new baseline. That is the opposite of the implementation-rule allowlists, which
shrink every slice and must be empty at slice 8 — see openapi/README.md.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

#: The tag CI compares against. Immutable: slice 8 cuts a *new* tag and points
#: the gate at it rather than moving this one (migration/cutover §7.5).
BASELINE_REF = "api-v1-launch"

#: The single pin. CI reads it from here (`--print-pinned-version`) so the binary
#: it installs cannot drift from the one the entries were generated with.
OASDIFF_VERSION = "1.23.0"

SPEC_PATH = "openapi/v1.json"
ERR_IGNORE_NAME = "oasdiff-err-ignore.txt"
WARN_IGNORE_NAME = "oasdiff-warn-ignore.txt"
SEVERITY_LEVELS_NAME = "oasdiff-severity-levels.txt"

#: oasdiff's `--format json` levels.
LEVEL_ERR = 3
LEVEL_WARN = 2

HTTP_METHODS = frozenset(
    {"GET", "PUT", "POST", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE"})

OPENAPI_DIR = Path(__file__).resolve().parent
GIT_ROOT = OPENAPI_DIR.parent


def entry_for(finding: dict) -> str:
    """The suppression line for one oasdiff finding.

    Operation, path, then oasdiff's own text verbatim — the three parts its
    matcher looks for.
    """
    return f"{finding['operation']} {finding['path']} {finding['text']}"


def suppresses(entry: str, finding: dict) -> bool:
    """Does `entry` cover `finding`? (oasdiff `checker/ignore.go` semantics.)

    The line must contain the operation, the path and the finding text, matched
    case-insensitively — which is why a reviewed block may wrap human metadata
    around a generated finding, but may not paraphrase the finding itself.
    """
    line = entry.lower()
    return (finding["operation"].lower() in line
            and finding["path"].lower() in line
            and finding["text"].lower() in line)


def parse_entries(text: str) -> list[tuple[int, str]]:
    """`(line number, entry)` for every line that is not a comment or blank."""
    entries = []
    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if line and not line.startswith("#"):
            entries.append((lineno, line))
    return entries


@dataclass(frozen=True)
class Report:
    """What the comparison found, and what the committed files did about it."""

    unreviewed: list[dict]
    inert: list[tuple[str, int, str]]

    @property
    def ok(self) -> bool:
        return not self.unreviewed and not self.inert


def review(findings: list[dict],
           err_entries: list[tuple[int, str]],
           warn_entries: list[tuple[int, str]],
           check_entries: bool = True) -> Report:
    """Match findings against the committed entries, at matching levels.

    `check_entries` is False for the authoring comparison: against any baseline
    other than the gate's own, entries that predate it legitimately match
    nothing, so calling them inert would be noise rather than a defect.
    """
    by_level = {
        LEVEL_ERR: (ERR_IGNORE_NAME, err_entries),
        LEVEL_WARN: (WARN_IGNORE_NAME, warn_entries),
    }
    covered = {ERR_IGNORE_NAME: set(), WARN_IGNORE_NAME: set()}

    unreviewed = []
    for finding in findings:
        name, entries = by_level.get(finding["level"], (None, []))
        matched = [lineno for lineno, entry in entries
                   if suppresses(entry, finding)]
        if matched:
            covered[name].update(matched)
        else:
            unreviewed.append(finding)

    inert = [(name, lineno, entry)
             for name, entries in (by_level[LEVEL_ERR], by_level[LEVEL_WARN])
             for lineno, entry in entries
             if lineno not in covered[name]] if check_entries else []

    return Report(unreviewed=unreviewed, inert=inert)


def _fail(message: str) -> None:
    sys.exit(f"contract gate: {message}")


def _oasdiff_binary() -> str:
    binary = os.environ.get("OASDIFF_BIN") or shutil.which("oasdiff")
    if not binary:
        _fail(f"oasdiff not on PATH. Install the pinned v{OASDIFF_VERSION} "
              f"(see openapi/README.md), or set OASDIFF_BIN.")
    found = subprocess.run([binary, "--version"], capture_output=True,
                           text=True).stdout.strip()
    if OASDIFF_VERSION not in found:
        _fail(f"oasdiff version mismatch: need v{OASDIFF_VERSION}, found "
              f"{found!r}. Findings are matched by their reported text, so a "
              f"different version can silently re-word every entry.")
    return binary


def _baseline_spec(baseline: str, into: Path) -> Path:
    """The committed spec at `baseline`, as a file oasdiff can read."""
    result = subprocess.run(
        ["git", "-C", str(GIT_ROOT), "show", f"{baseline}:{SPEC_PATH}"],
        capture_output=True)
    if result.returncode != 0:
        _fail(f"cannot read {SPEC_PATH} at {baseline!r}: "
              f"{result.stderr.decode(errors='replace').strip()}. "
              f"In CI this means the tag was not fetched (`fetch-tags: true`); "
              f"the gate must never be skipped for a missing baseline.")
    path = into / "baseline-v1.json"
    path.write_bytes(result.stdout)
    return path


def _findings(binary: str, baseline_spec: Path, head_spec: Path) -> list[dict]:
    result = subprocess.run(
        [binary, "breaking", "--format", "json",
         "--severity-levels", str(OPENAPI_DIR / SEVERITY_LEVELS_NAME),
         str(baseline_spec), str(head_spec)],
        capture_output=True, text=True)
    if result.returncode not in (0, 1):  # 1 == breaking changes found
        _fail(f"oasdiff failed ({result.returncode}): {result.stderr.strip()}")
    return json.loads(result.stdout or "[]")


def _annotate(message: str) -> None:
    """A GitHub Actions annotation in CI; a plain line everywhere else."""
    if os.environ.get("GITHUB_ACTIONS"):
        print(f"::error file={SPEC_PATH}::{message}")
    else:
        print(f"  {message}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--baseline", default=BASELINE_REF,
        help=f"git ref to compare against (default: {BASELINE_REF}, the "
             f"immutable published contract). Use `main` when authoring a "
             f"slice's own new entries.")
    parser.add_argument(
        "--head", default=str(GIT_ROOT / SPEC_PATH),
        help="the proposed spec (default: the working tree's).")
    parser.add_argument(
        "--emit", action="store_true",
        help="print paste-ready entries for every unreviewed finding, split by "
             "the file each belongs in. Never hand-type an entry.")
    parser.add_argument(
        "--print-pinned-version", action="store_true",
        help="print the pinned oasdiff version and exit (CI installs this).")
    args = parser.parse_args(argv)

    if args.print_pinned_version:
        print(OASDIFF_VERSION)
        return 0

    binary = _oasdiff_binary()
    with tempfile.TemporaryDirectory() as tmp:
        baseline_spec = _baseline_spec(args.baseline, Path(tmp))
        findings = _findings(binary, baseline_spec, Path(args.head))

    report = review(
        findings,
        parse_entries((OPENAPI_DIR / ERR_IGNORE_NAME).read_text("utf-8")),
        parse_entries((OPENAPI_DIR / WARN_IGNORE_NAME).read_text("utf-8")),
        check_entries=args.baseline == BASELINE_REF)

    errs = sum(1 for f in findings if f["level"] == LEVEL_ERR)
    print(f"{args.baseline} -> {args.head}: {len(findings)} breaking changes "
          f"({errs} error, {len(findings) - errs} warning); "
          f"{len(findings) - len(report.unreviewed)} reviewed.")

    if args.emit:
        _emit(report.unreviewed)

    if report.unreviewed:
        print(f"\n{len(report.unreviewed)} break(s) no committed entry covers "
              f"- review, then record with --emit:")
        for finding in report.unreviewed:
            _annotate(f"unreviewed break: {entry_for(finding)}")
    for name, lineno, entry in report.inert:
        _annotate(f"{name}:{lineno} suppresses nothing - an entry filed at the "
                  f"wrong level, or a break that no longer exists: {entry}")

    if report.ok:
        print(f"every break since {args.baseline} is recorded as reviewed.")
    return 0 if report.ok else 1


def _emit(unreviewed: list[dict]) -> None:
    for name, level in ((ERR_IGNORE_NAME, LEVEL_ERR),
                        (WARN_IGNORE_NAME, LEVEL_WARN)):
        lines = sorted(entry_for(f) for f in unreviewed if f["level"] == level)
        if lines:
            print(f"\n# ---- paste into openapi/{name} ----")
            print("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
