#!/usr/bin/env python3
"""The contract breaking-change gate — cumulative, against an immutable baseline.

Run from the git root (CI's `contract` job runs exactly this):

    python openapi/contract_gate.py                 # the gate
    python openapi/contract_gate.py --baseline origin/main --emit   # authoring

**The gate** compares `api-v1-launch` against the working tree, so every break
since the contract was published is proven to have been reviewed — not merely
that each step was reviewed against the step before it. A break that is skipped
rather than reviewed is invisible to a per-pull-request comparison forever after,
which is not hypothetical here (#129).

**Authoring** a slice's new entries compares previous `main` against the proposal
(`--baseline origin/main --emit`), so a slice does not re-derive every earlier
entry. `--emit` prints the lines to paste, split by the file they belong in.
Entries are generated by running this tool; a hand-typed finding is a defect
(§7.2).

Two verdicts fail the gate: **unreviewed**, a break no committed entry covers;
and **inert**, a committed entry that covers no finding at its own level — which
means it silently does nothing, the defect this repo has already shipped once.

openapi/README.md carries the full reasoning, including why the suppression files
cannot reach zero until slice 8 cuts a new baseline, and why that makes them the
opposite of the implementation-rule migration ledgers rather than another one.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import NoReturn

#: The tag CI compares against. Immutable: slice 8 cuts a *new* tag and points
#: the gate at it rather than moving this one (migration/cutover §7.5).
BASELINE_REF = "api-v1-launch"

#: The single pin. CI reads it from here (`--print-pinned-version`) so the binary
#: it installs cannot drift from the one the entries were generated with.
OASDIFF_VERSION = "1.23.0"

SPEC_PATH = "openapi/v1.json"
ERR_IGNORE_NAME = "oasdiff-err-ignore.txt"
WARN_IGNORE_NAME = "oasdiff-warn-ignore.txt"
SEVERITY_LEVELS_NAME = "oasdiff-severity-levels.txt"

#: oasdiff's `--format json` levels, and the file each is suppressed from.
#: `oasdiff breaking` reports nothing below WARN — a check downgraded to `info`
#: by the severity-levels file (the open-enum stance) never reaches us at all —
#: so a finding at any other level is not a breaking change and is skipped.
LEVEL_ERR = 3
LEVEL_WARN = 2
IGNORE_FILE_FOR = {LEVEL_ERR: ERR_IGNORE_NAME, LEVEL_WARN: WARN_IGNORE_NAME}

OPENAPI_DIR = Path(__file__).resolve().parent
GIT_ROOT = OPENAPI_DIR.parent


def located(finding: dict) -> tuple[str, str]:
    """Where a finding says it is — the two parts an entry must name besides text.

    Most findings are about one operation on one path and carry both. A
    COMPONENT-level one carries neither: `webhook-removed` reports
    `{"section": "components", "text": "webhook `x` removed"}`, because a
    webhook is a published event rather than a route a caller invokes. It
    matches on its SECTION where an operation-level finding matches on its
    operation, so that is what fills the slot.

    This is oasdiff's behaviour, not an assumption about it — a line carrying
    only the text suppresses nothing, and one carrying `components` as well
    suppresses exactly its finding. `_cross_check` re-proves it on every run by
    comparing this matcher against oasdiff's own `--err-ignore` pass, which is
    how the first reading here (that a missing part matches anything, as
    `strings.Contains(line, "")` would) was caught rather than shipped.
    """
    return finding.get("operation") or finding.get("section", ""), \
        finding.get("path", "")


def entry_for(finding: dict) -> str:
    """The suppression line for one oasdiff finding.

    Operation, path, then oasdiff's own text verbatim — the three parts its
    matcher looks for. A finding carrying no operation or path contributes only
    its text, rather than a line opening with blanks.
    """
    return " ".join(part for part in (*located(finding), finding["text"]) if part)


def suppresses(entry: str, finding: dict) -> bool:
    """Does `entry` cover `finding`? (oasdiff `checker/ignore.go` semantics.)

    The line must contain the operation, the path and the finding text, matched
    case-insensitively — which is why a reviewed block may wrap human metadata
    around a generated finding, but may not paraphrase the finding itself.
    """
    line = entry.lower()
    operation, path = located(finding)
    return (operation.lower() in line
            and path.lower() in line
            and finding["text"].lower() in line)


def parse_entries(text: str) -> list[tuple[int, str]]:
    """`(line number, entry)` for every line that is not a comment or blank."""
    entries = []
    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if line and not line.startswith("#"):
            entries.append((lineno, line))
    return entries


@dataclass(frozen=True)
class Report:
    """What the comparison found, and what the committed files did about it."""

    unreviewed: list[dict]
    inert: list[tuple[str, int, str]]

    @property
    def ok(self) -> bool:
        return not self.unreviewed and not self.inert


def review(findings: list[dict],
           err_entries: list[tuple[int, str]],
           warn_entries: list[tuple[int, str]],
           report_inert: bool = True) -> Report:
    """Match findings against the committed entries, at matching levels.

    `report_inert` is False for the authoring comparison: against any baseline
    other than the gate's own, entries that predate it legitimately match
    nothing, so calling them inert would be noise rather than a defect.
    """
    entries_for = {ERR_IGNORE_NAME: err_entries, WARN_IGNORE_NAME: warn_entries}
    covered = {name: set() for name in entries_for}

    unreviewed = []
    for finding in findings:
        name = IGNORE_FILE_FOR.get(finding["level"])
        if name is None:  # below WARN: not a breaking change
            continue
        matched = [lineno for lineno, entry in entries_for[name]
                   if suppresses(entry, finding)]
        if matched:
            covered[name].update(matched)
        else:
            unreviewed.append(finding)

    if not report_inert:
        return Report(unreviewed=unreviewed, inert=[])

    return Report(unreviewed=unreviewed, inert=[
        (name, lineno, entry)
        for name, entries in entries_for.items()
        for lineno, entry in entries
        if lineno not in covered[name]])


def _fail(message: str) -> NoReturn:
    sys.exit(f"contract gate: {message}")


def _oasdiff_binary() -> str:
    binary = os.environ.get("OASDIFF_BIN") or shutil.which("oasdiff")
    if not binary:
        _fail(f"oasdiff not on PATH. Install the pinned v{OASDIFF_VERSION} "
              f"(see openapi/README.md), or set OASDIFF_BIN.")
    found = subprocess.run([binary, "--version"], capture_output=True,
                           text=True).stdout.strip()
    if OASDIFF_VERSION not in found:
        _fail(f"oasdiff version mismatch: need v{OASDIFF_VERSION}, found "
              f"{found!r}. Findings are matched by their reported text, so a "
              f"different version can silently re-word every entry.")
    return binary


def _baseline_spec(baseline: str, into: Path) -> Path:
    """The committed spec at `baseline`, as a file oasdiff can read."""
    result = subprocess.run(
        ["git", "-C", str(GIT_ROOT), "show", f"{baseline}:{SPEC_PATH}"],
        capture_output=True)
    if result.returncode != 0:
        _fail(f"cannot read {SPEC_PATH} at {baseline!r}: "
              f"{result.stderr.decode(errors='replace').strip()}. "
              f"In CI this means the tag was not fetched: the "
              f"`actions/checkout` step in the `contract` job that runs this "
              f"gate (.github/workflows/ci.yml) needs `fetch-depth: 0` and its "
              f"tag-fetching input turned on. The gate must never be skipped "
              f"for a missing baseline.")
    path = into / "baseline-v1.json"
    path.write_bytes(result.stdout)
    return path


def _findings(binary: str, baseline_spec: Path, head_spec: Path,
              apply_ignores: bool = False) -> list[dict]:
    command = [binary, "breaking", "--format", "json",
               "--severity-levels", str(OPENAPI_DIR / SEVERITY_LEVELS_NAME)]
    if apply_ignores:
        command += ["--err-ignore", str(OPENAPI_DIR / ERR_IGNORE_NAME),
                    "--warn-ignore", str(OPENAPI_DIR / WARN_IGNORE_NAME)]
    command += [str(baseline_spec), str(head_spec)]

    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode not in (0, 1):  # 1 == breaking changes found
        _fail(f"oasdiff failed ({result.returncode}): {result.stderr.strip()}")
    return json.loads(result.stdout or "[]")


def _cross_check(ours: list[dict], theirs: list[dict]) -> None:
    """Our matcher must agree with oasdiff's own `--err/--warn-ignore` run.

    We match the entries ourselves, because oasdiff can suppress a finding but
    cannot report an entry that suppressed nothing. That only stays honest while
    the two agree — and the files are documented as usable with the raw tool, so
    a divergence would make that documentation false.
    """
    def key(findings):
        return sorted((*located(f), f["text"]) for f in findings)

    if key(ours) != key(theirs):
        _fail("this gate and oasdiff's own --err-ignore/--warn-ignore run "
              "disagree about what the committed entries suppress. The entry "
              "matching here no longer mirrors oasdiff's checker/ignore.go; "
              f"we report {len(ours)} unreviewed, it reports {len(theirs)}.")


def _annotate(message: str) -> None:
    """A GitHub Actions annotation in CI; a plain line everywhere else."""
    if os.environ.get("GITHUB_ACTIONS"):
        print(f"::error file={SPEC_PATH}::{message}")
    else:
        print(f"  {message}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--baseline", default=BASELINE_REF,
        help=f"git ref to compare against (default: {BASELINE_REF}, the "
             f"immutable published contract). Use `main` when authoring a "
             f"slice's own new entries.")
    parser.add_argument(
        "--head", default=str(GIT_ROOT / SPEC_PATH),
        help="the proposed spec (default: the working tree's).")
    parser.add_argument(
        "--emit", action="store_true",
        help="print paste-ready entries for every unreviewed finding, split by "
             "the file each belongs in. Never hand-type an entry.")
    parser.add_argument(
        "--print-pinned-version", action="store_true",
        help="print the pinned oasdiff version and exit (CI installs this).")
    args = parser.parse_args(argv)

    if args.print_pinned_version:
        print(OASDIFF_VERSION)
        return 0

    binary = _oasdiff_binary()
    with tempfile.TemporaryDirectory() as tmp:
        baseline_spec = _baseline_spec(args.baseline, Path(tmp))
        findings = _findings(binary, baseline_spec, Path(args.head))
        suppressed_by_oasdiff = _findings(binary, baseline_spec,
                                          Path(args.head), apply_ignores=True)

    report = review(
        findings,
        parse_entries((OPENAPI_DIR / ERR_IGNORE_NAME).read_text("utf-8")),
        parse_entries((OPENAPI_DIR / WARN_IGNORE_NAME).read_text("utf-8")),
        report_inert=args.baseline == BASELINE_REF)
    _cross_check(report.unreviewed, suppressed_by_oasdiff)

    errs = sum(1 for f in findings if f["level"] == LEVEL_ERR)
    print(f"{args.baseline} -> {args.head}: {len(findings)} breaking changes "
          f"({errs} error, {len(findings) - errs} warning); "
          f"{len(findings) - len(report.unreviewed)} reviewed.")

    if args.emit:
        _emit(report.unreviewed)

    if report.unreviewed:
        print(f"\n{len(report.unreviewed)} break(s) no committed entry covers "
              f"- review, then record with --emit:")
        for finding in report.unreviewed:
            _annotate(f"unreviewed break: {entry_for(finding)}")
    for name, lineno, entry in report.inert:
        _annotate(f"{name}:{lineno} suppresses nothing - an entry filed at the "
                  f"wrong level, or a break that no longer exists: {entry}")

    if report.ok:
        print(f"every break since {args.baseline} is recorded as reviewed.")
    return 0 if report.ok else 1


def _emit(unreviewed: list[dict]) -> None:
    for level, name in IGNORE_FILE_FOR.items():
        lines = sorted(entry_for(f) for f in unreviewed if f["level"] == level)
        if lines:
            print(f"\n# ---- paste into openapi/{name} ----")
            print("\n".join(lines))


if __name__ == "__main__":
    sys.exit(main())
