// Mock fixtures — one coherent story: "Acme AI", a prepaid tenant live since
// March 2026, five team members, a real month of platform-fee history, and an
// audit trail covering config, keys, pricing, and team activity.
//
// The initial tenant config deliberately mirrors the app-level mock in
// @/hooks/use-tenant-config (same query key feeds the nav shell) so the two
// sources never disagree on first paint.

import type {
  AuditRecord,
  BillingPeriod,
  ConnectStatus,
  Invitation,
  Member,
  TenantInvoice,
} from "./types";

/** Money already exists for this tenant, so the currency is locked (CUR-1). */
export const CURRENCY_LOCKED = true;
export const CURRENCY_LOCK_REASON =
  "Wallet transactions already exist for this workspace, so the currency can no longer change.";

/** The tenant DOES have active cost rate cards (coverage toggle can enable). */
export const HAS_ACTIVE_COST_CARDS = true;
/** Stripe Tax is active on the connected account (tax toggle can enable). */
export const STRIPE_TAX_ACTIVE = true;

export const INITIAL_CONNECT_STATUS: ConnectStatus = {
  account_id: "acct_mock123",
  charges_enabled: true,
  onboarded: true,
};

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "mem-priya",
    email: "priya@acme.ai",
    role: "write",
    status: "pending",
    clerk_user_id: "",
    activated_at: null,
    created_at: "2026-07-20T14:02:00Z",
  },
  {
    id: "mem-rob",
    email: "rob@acme.ai",
    role: "read",
    status: "active",
    clerk_user_id: "user_rob",
    activated_at: "2026-06-11T08:20:00Z",
    created_at: "2026-06-10T16:45:00Z",
  },
  {
    id: "mem-sasha",
    email: "sasha@acme.ai",
    role: "write",
    status: "active",
    clerk_user_id: "user_sasha",
    activated_at: "2026-04-03T11:12:00Z",
    created_at: "2026-04-02T09:30:00Z",
  },
  {
    id: "mem-mia",
    email: "mia@acme.ai",
    role: "admin",
    status: "active",
    clerk_user_id: "user_mia",
    activated_at: "2026-03-05T10:01:00Z",
    created_at: "2026-03-04T18:22:00Z",
  },
  {
    id: "mem-dev",
    email: "dev@example.com",
    role: "admin",
    status: "active",
    clerk_user_id: "user_dev",
    activated_at: "2026-03-02T09:00:00Z",
    created_at: "2026-03-02T09:00:00Z",
  },
];

export const INITIAL_INVITATIONS: Invitation[] = [
  {
    id: "inv-priya",
    email: "priya@acme.ai",
    role: "write",
    status: "pending",
    created_at: "2026-07-20T14:02:00Z",
  },
  {
    id: "inv-rob",
    email: "rob@acme.ai",
    role: "read",
    status: "accepted",
    created_at: "2026-06-10T16:45:00Z",
  },
  {
    id: "inv-contractor",
    email: "contractor@freelance.dev",
    role: "write",
    status: "revoked",
    created_at: "2026-05-18T13:37:00Z",
  },
];

export const BILLING_PERIODS: BillingPeriod[] = [
  {
    id: "bp-2026-07",
    period_start: "2026-07-01",
    period_end: "2026-07-31",
    status: "open",
    total_usage_cost_micros: 1_412_380_000,
    event_count: 918_240,
    platform_fee_micros: 70_620_000,
  },
  {
    id: "bp-2026-06",
    period_start: "2026-06-01",
    period_end: "2026-06-30",
    status: "invoiced",
    total_usage_cost_micros: 1_842_550_000,
    event_count: 1_204_118,
    platform_fee_micros: 92_130_000,
  },
  {
    id: "bp-2026-05",
    period_start: "2026-05-01",
    period_end: "2026-05-31",
    status: "invoiced",
    total_usage_cost_micros: 1_260_040_000,
    event_count: 861_772,
    platform_fee_micros: 63_000_000,
  },
  {
    id: "bp-2026-04",
    period_start: "2026-04-01",
    period_end: "2026-04-30",
    status: "closed",
    total_usage_cost_micros: 604_910_000,
    event_count: 402_331,
    platform_fee_micros: 30_250_000,
  },
];

export const TENANT_INVOICES: TenantInvoice[] = [
  {
    id: "ti-2026-06",
    billing_period_id: "bp-2026-06",
    stripe_invoice_id: "in_1PXmc2Acme0601",
    total_amount_micros: 92_130_000,
    status: "finalized",
    created_at: "2026-07-02T00:15:00Z",
  },
  {
    id: "ti-2026-05",
    billing_period_id: "bp-2026-05",
    stripe_invoice_id: "in_1PNqa9Acme0501",
    total_amount_micros: 63_000_000,
    status: "paid",
    created_at: "2026-06-02T00:15:00Z",
  },
  {
    id: "ti-2026-04",
    billing_period_id: "bp-2026-04",
    stripe_invoice_id: "",
    total_amount_micros: 30_250_000,
    status: "draft",
    created_at: "2026-05-02T00:15:00Z",
  },
];

export const AUDIT_RECORDS: AuditRecord[] = [
  {
    id: "aud-18",
    created_at: "2026-07-23T09:41:00Z",
    actor_id: "mem-mia",
    actor_kind: "member",
    actor_display: "mia@acme.ai",
    action: "config.updated",
    resource_type: "tenant_config",
    resource_id: "cfg-acme",
    correlation_id: "corr-9f31",
    metadata: {
      changes: { enforcement_mode: { from: "off", to: "enforcing" } },
    },
  },
  {
    id: "aud-17",
    created_at: "2026-07-22T17:05:00Z",
    actor_id: "key-live-2",
    actor_kind: "api_key",
    actor_display: "ubb_live_k9x2…",
    action: "rate_card.published",
    resource_type: "rate_card",
    resource_id: "rc-openai-price-v4",
    correlation_id: "corr-8ac0",
    metadata: {
      version: 4,
      changes: 3,
      provider: "openai",
      card_type: "price",
    },
  },
  {
    id: "aud-16",
    created_at: "2026-07-20T14:02:00Z",
    actor_id: "mem-dev",
    actor_kind: "member",
    actor_display: "dev@example.com",
    action: "invitation.created",
    resource_type: "invitation",
    resource_id: "inv-priya",
    correlation_id: "corr-77b1",
    metadata: { email: "priya@acme.ai", role: "write" },
  },
  {
    id: "aud-15",
    created_at: "2026-07-18T11:30:00Z",
    actor_id: "mem-mia",
    actor_kind: "member",
    actor_display: "mia@acme.ai",
    action: "credit_grant.created",
    resource_type: "credit_grant",
    resource_id: "grant-72aa",
    correlation_id: "corr-51fe",
    metadata: {
      customer: "cust-batavia-labs",
      kind: "promo",
      amount_micros: 50_000_000,
      expires_in_days: 30,
    },
  },
  {
    id: "aud-14",
    created_at: "2026-07-16T08:12:00Z",
    actor_id: "system",
    actor_kind: "system",
    actor_display: "UBB",
    action: "billing_period.closed",
    resource_type: "billing_period",
    resource_id: "bp-2026-06",
    correlation_id: "corr-4410",
    metadata: {
      period_start: "2026-06-01",
      event_count: 1_204_118,
      platform_fee_micros: 92_130_000,
    },
  },
  {
    id: "aud-13",
    created_at: "2026-07-14T15:48:00Z",
    actor_id: "mem-dev",
    actor_kind: "member",
    actor_display: "dev@example.com",
    action: "webhook_config.updated",
    resource_type: "webhook_config",
    resource_id: "wh-primary",
    correlation_id: "corr-3d92",
    metadata: {
      changes: { event_types: { added: ["soft_floor.crossed"], removed: [] } },
    },
  },
  {
    id: "aud-12",
    created_at: "2026-07-11T10:22:00Z",
    actor_id: "mem-mia",
    actor_kind: "member",
    actor_display: "mia@acme.ai",
    action: "api_key.rotated",
    resource_type: "api_key",
    resource_id: "key-live-2",
    correlation_id: "corr-2b17",
    metadata: { revoked_key_id: "key-live-1", label: "Production (rotated)" },
  },
  {
    id: "aud-11",
    created_at: "2026-07-09T19:03:00Z",
    actor_id: "key-live-2",
    actor_kind: "api_key",
    actor_display: "ubb_live_k9x2…",
    action: "customer.suspended",
    resource_type: "customer",
    resource_id: "cust-vanta-ml",
    correlation_id: "corr-19c4",
    metadata: { reason: "chargeback", balance_micros: -12_400_000 },
  },
  {
    id: "aud-10",
    created_at: "2026-07-07T09:55:00Z",
    actor_id: "mem-dev",
    actor_kind: "member",
    actor_display: "dev@example.com",
    action: "member.role_updated",
    resource_type: "member",
    resource_id: "mem-sasha",
    correlation_id: "corr-0fa8",
    metadata: { from: "read", to: "write" },
  },
  {
    id: "aud-09",
    created_at: "2026-07-04T12:40:00Z",
    actor_id: "operator-1",
    actor_kind: "operator",
    actor_display: "UBB support",
    action: "ingest.backfill_reopened",
    resource_type: "billing_period",
    resource_id: "bp-2026-05",
    correlation_id: "corr-ee02",
    metadata: { window_days: 34, requested_by: "mia@acme.ai" },
  },
  {
    id: "aud-08",
    created_at: "2026-07-02T00:15:00Z",
    actor_id: "system",
    actor_kind: "system",
    actor_display: "UBB",
    action: "invoice.finalized",
    resource_type: "tenant_invoice",
    resource_id: "ti-2026-06",
    correlation_id: "corr-cd55",
    metadata: {
      total_amount_micros: 92_130_000,
      stripe_invoice_id: "in_1PXmc2Acme0601",
    },
  },
  {
    id: "aud-07",
    created_at: "2026-06-28T16:19:00Z",
    actor_id: "mem-mia",
    actor_kind: "member",
    actor_display: "mia@acme.ai",
    action: "markup.updated",
    resource_type: "markup_config",
    resource_id: "markup-default",
    correlation_id: "corr-b7d3",
    metadata: {
      markup_percentage_micros: { from: 15_000_000, to: 20_000_000 },
    },
  },
  {
    id: "aud-06",
    created_at: "2026-06-21T13:08:00Z",
    actor_id: "mem-dev",
    actor_kind: "member",
    actor_display: "dev@example.com",
    action: "sandbox.created",
    resource_type: "tenant",
    resource_id: "tenant-acme-sandbox",
    correlation_id: "corr-a2c9",
    metadata: { key_prefix: "ubb_test_q7ln" },
  },
  {
    id: "aud-05",
    created_at: "2026-06-10T16:45:00Z",
    actor_id: "mem-mia",
    actor_kind: "member",
    actor_display: "mia@acme.ai",
    action: "invitation.created",
    resource_type: "invitation",
    resource_id: "inv-rob",
    correlation_id: "corr-91e0",
    metadata: { email: "rob@acme.ai", role: "read" },
  },
  {
    id: "aud-04",
    created_at: "2026-05-19T09:26:00Z",
    actor_id: "mem-dev",
    actor_kind: "member",
    actor_display: "dev@example.com",
    action: "invitation.revoked",
    resource_type: "invitation",
    resource_id: "inv-contractor",
    correlation_id: "corr-70bb",
    metadata: { email: "contractor@freelance.dev" },
  },
  {
    id: "aud-03",
    created_at: "2026-04-22T10:44:00Z",
    actor_id: "mem-mia",
    actor_kind: "member",
    actor_display: "mia@acme.ai",
    action: "budget.updated",
    resource_type: "budget_config",
    resource_id: "budget-tenant",
    correlation_id: "corr-63f7",
    metadata: {
      cap_micros: 2_000_000_000,
      enforce_mode: "advisory",
      alert_levels: [50, 80, 100],
    },
  },
  {
    id: "aud-02",
    created_at: "2026-03-04T18:22:00Z",
    actor_id: "mem-dev",
    actor_kind: "member",
    actor_display: "dev@example.com",
    action: "invitation.created",
    resource_type: "invitation",
    resource_id: "inv-mia",
    correlation_id: "corr-40a1",
    metadata: { email: "mia@acme.ai", role: "admin" },
  },
  {
    id: "aud-01",
    created_at: "2026-03-02T09:00:00Z",
    actor_id: "system",
    actor_kind: "system",
    actor_display: "UBB",
    action: "tenant.created",
    resource_type: "tenant",
    resource_id: "tenant-acme",
    correlation_id: "corr-0001",
    metadata: { billing_mode: "meter_only", default_currency: "usd" },
  },
];
