# Generated by Django 6.0.1 on 2026-01-30 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('invoiced', 'Invoiced')], db_index=True, default='open', max_length=20)),
                ('total_cost_micros', models.BigIntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('invoice_attempt_number', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_billing_period',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('total_amount_micros', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], db_index=True, default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('billing_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='usage.billingperiod')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_invoice',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(db_index=True, max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, max_length=500)),
                ('cost_micros', models.BigIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('effective_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='usage.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_usage_event',
                'ordering': ['-effective_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'period_start', 'period_end'), name='uq_billing_period'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uq_usage_event_idempotency'),
        ),
    ]
