# Generated by Django 6.0.1 on 2026-01-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_wallettransaction_idx_wallet_txn_wallet_created'),
        ('tenants', '__first__'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='billingperiod',
            index=models.Index(fields=['status', 'period_end'], name='idx_billing_period_status_end'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', 'status'], name='idx_invoice_customer_status'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['customer', '-effective_at'], name='idx_usage_customer_effective'),
        ),
    ]
