# Generated by Django 6.0.1 on 2026-01-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='balance_after_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
