# Generated by Django 6.0.1 on 2026-01-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_wallettransaction_idempotency_key_and_more'),
        ('tenants', '__first__'),
        ('usage', '0004_add_balance_after_micros'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usageevent',
            name='uq_usage_event_idempotency',
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'idempotency_key'), name='uq_usage_event_idempotency_v2'),
        ),
    ]
