# Generated by Django 6.0.1 on 2026-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0009_invoice_top_up_attempt_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='group_keys',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
