# Generated by Django 6.0.1 on 2026-02-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupattempt',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
