# Generated by Django 6.0.6 on 2026-06-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topups', '0002_add_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupattempt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('requires_action', 'Requires Action'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=20),
        ),
    ]
