# Generated by Django 6.0.6 on 2026-07-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('topups', '0003_alter_topupattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='topupattempt',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddConstraint(
            model_name='topupattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('customer', 'idempotency_key'), name='uq_topup_attempt_idempotency'),
        ),
    ]
