# Generated by Django 6.0.1 on 2026-01-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_autotopupconfig_deleted_at_customer_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('wallet', 'idempotency_key'), name='uq_wallet_txn_idempotency'),
        ),
    ]
