# Generated by Django 6.0.1 on 2026-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_wallettransaction_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topupattempt',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto_topup', 'Auto Top-Up'), ('widget', 'Widget')], max_length=20),
        ),
    ]
