# Generated by Django 6.0.1 on 2026-02-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_remove_topup_to_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='arrears_threshold_micros',
            new_name='min_balance_micros',
        ),
    ]
