# Generated by Django 6.0.6 on 2026-06-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_arrears_to_min_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='revenue_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
