# Generated by Django 6.0.6 on 2026-06-09 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customer_revenue_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('seat', 'Seat')], db_index=True, default='individual', max_length=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_topology',
            field=models.CharField(blank=True, choices=[('pooled', 'Pooled'), ('allocated', 'Allocated')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='customers.customer'),
        ),
    ]
