# Generated by Django 6.0.6 on 2026-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_customer_account_type_customer_billing_topology_and_more'),
        ('tenants', '0010_tenant_require_cost_card_coverage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='uq_customer_tenant_external',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'external_id'), name='uq_customer_tenant_external'),
        ),
    ]
