# Generated by Django 6.0.6 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suspension_reason',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
