# Generated by Django 6.0.1 on 2026-02-01 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('dimensions', models.JSONField(default=dict)),
                ('dimensions_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cost_per_unit_micros', models.BigIntegerField()),
                ('unit_quantity', models.BigIntegerField(default=1000000)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ubb_provider_rate',
            },
        ),
        migrations.CreateModel(
            name='TenantMarkup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('markup_percentage_micros', models.BigIntegerField(default=0)),
                ('fixed_uplift_micros', models.BigIntegerField(default=0)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_tenant_markup',
            },
        ),
    ]
