# Generated by Django 6.0.1 on 2026-02-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_add_tenant_to_providerrate'),
        ('tenants', '0005_add_products_field'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='providerrate',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('tenant', 'provider', 'event_type', 'metric_name', 'dimensions_hash'), name='uq_provrate_active_per_tenant'),
        ),
    ]
