# Generated by Django 6.0.1 on 2026-02-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_add_unique_constraint_active_rate'),
        ('tenants', '0007_rename_arrears_to_min_balance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenantmarkup',
            index=models.Index(fields=['tenant', 'event_type', 'provider'], name='idx_markup_tenant_lookup'),
        ),
    ]
