# Generated by Django 6.0.1 on 2026-04-14 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_add_markup_composite_index'),
        ('tenants', '0009_tenantuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('dimensions', models.JSONField(default=dict)),
                ('dimensions_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_cards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_card',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('cost_per_unit_micros', models.BigIntegerField()),
                ('unit_quantity', models.BigIntegerField(default=1000000)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.card')),
            ],
            options={
                'db_table': 'ubb_rate',
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['tenant', 'provider', 'event_type'], name='idx_card_tenant_lookup'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'provider', 'event_type', 'dimensions_hash'), name='uq_card_active_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('card', 'metric_name'), name='uq_rate_active_per_card_metric'),
        ),
    ]
