# Generated by Django 6.0.1 on 2026-04-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_card_rate_card_idx_card_tenant_lookup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantmarkup',
            name='fixed_uplift_micros',
        ),
        migrations.RemoveField(
            model_name='tenantmarkup',
            name='markup_percentage_micros',
        ),
        migrations.AddField(
            model_name='tenantmarkup',
            name='margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target margin %. 0 = pass-through.', max_digits=5),
        ),
    ]
