# Generated by Django 6.0.1 on 2026-04-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_tenantmarkup_fixed_uplift_micros_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='providerrate',
            name='idx_provrate_tenant_lookup',
        ),
        migrations.RemoveConstraint(
            model_name='providerrate',
            name='uq_provrate_active_per_tenant',
        ),
        migrations.DeleteModel(
            name='ProviderRate',
        ),
    ]
