# Generated by Django 6.0.6 on 2026-06-08 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_arrears_to_min_balance'),
        ('pricing', '0006_slim_tenant_markup'),
        ('tenants', '0009_tenant_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(choices=[('cost', 'Cost'), ('price', 'Price')], db_index=True, max_length=10)),
                ('provider', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('metric_name', models.CharField(max_length=100)),
                ('dimensions', models.JSONField(default=dict)),
                ('dimensions_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('pricing_model', models.CharField(choices=[('per_unit', 'Per unit'), ('flat', 'Flat')], default='per_unit', max_length=20)),
                ('rate_per_unit_micros', models.BigIntegerField(default=0)),
                ('unit_quantity', models.BigIntegerField(default=1000000)),
                ('fixed_micros', models.BigIntegerField(default=0)),
                ('tiers', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('product_id', models.CharField(blank=True, default='', max_length=100)),
                ('valid_from', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_rate_card',
                'indexes': [models.Index(fields=['tenant', 'card_type', 'provider', 'event_type', 'metric_name'], name='idx_ratecard_lookup')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('customer__isnull', True), ('valid_to__isnull', True)), fields=('tenant', 'card_type', 'provider', 'event_type', 'metric_name', 'dimensions_hash', 'currency'), name='uq_ratecard_active_tenant'), models.UniqueConstraint(condition=models.Q(('customer__isnull', False), ('valid_to__isnull', True)), fields=('tenant', 'customer', 'card_type', 'provider', 'event_type', 'metric_name', 'dimensions_hash', 'currency'), name='uq_ratecard_active_customer')],
            },
        ),
    ]
