# Generated by Django 6.0.1 on 2026-04-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('pricing', '0007_remove_providerrate_idx_provrate_tenant_lookup_and_more'),
        ('tenants', '0010_tenant_group_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_cards', to='groups.group'),
        ),
        migrations.AddField(
            model_name='card',
            name='pricing_source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rate',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='pricing_type',
            field=models.CharField(choices=[('per_unit', 'Per Unit'), ('flat', 'Flat')], default='per_unit', max_length=20),
        ),
        migrations.AddField(
            model_name='rate',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'draft'])), fields=('tenant', 'slug'), name='uq_card_slug_per_tenant'),
        ),
    ]
