# Generated by Django 6.0.6 on 2026-06-09 15:55

import uuid
from django.db import migrations, models


def _backfill_lineage(apps, schema_editor):
    import uuid
    RateCard = apps.get_model("pricing", "RateCard")
    groups = {}
    for c in RateCard.objects.all().order_by("valid_from"):
        key = (c.tenant_id, c.customer_id, c.card_type, c.provider, c.event_type,
               c.metric_name, c.dimensions_hash, c.currency)
        lid = groups.setdefault(key, uuid.uuid4())
        RateCard.objects.filter(id=c.id).update(lineage_id=lid)


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_ratecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecard',
            name='lineage_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(_backfill_lineage, migrations.RunPython.noop),
    ]
