# Generated by Django 6.0.1 on 2026-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_card_slug_group_rate_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='provider_cost_per_unit_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
