# Generated by Django 6.0.6 on 2026-06-12 07:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('pricing', '0008_ratecard_lineage_id'),
        ('tenants', '0012_backfill_charges_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecard',
            name='pricing_model',
            field=models.CharField(choices=[('per_unit', 'Per unit'), ('flat', 'Flat'), ('graduated', 'Graduated'), ('package', 'Package')], default='per_unit', max_length=20),
        ),
        migrations.CreateModel(
            name='PricingPeriodCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lineage_id', models.UUIDField(db_index=True)),
                ('metric_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('units_total', models.BigIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_period_counters', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_period_counters', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_pricing_period_counter',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer', 'lineage_id', 'period_start'), name='uq_pricing_period_counter')],
            },
        ),
    ]
