# Generated by Django 6.0.1 on 2026-07-03 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('pricing', '0010_rename_ratecard_to_rate'),
        ('tenants', '0017_tenant_run_stale_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='book_version_from',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rate',
            name='book_version_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(choices=[('cost', 'Cost'), ('price', 'Price')], db_index=True, max_length=10)),
                ('provider_key', models.CharField(blank=True, default='', max_length=100)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('key', models.SlugField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_containers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_rate_card_container',
            },
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='pricing.ratecard'),
        ),
        migrations.CreateModel(
            name='RateCardAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_assignments', to='customers.customer')),
                ('rate_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pricing.ratecard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_card_assignments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_rate_card_assignment',
            },
        ),
        migrations.AddConstraint(
            model_name='ratecard',
            constraint=models.UniqueConstraint(fields=('tenant', 'card_type', 'key'), name='uq_ratecard_tenant_key'),
        ),
        migrations.AddConstraint(
            model_name='ratecard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'card_type', 'provider_key', 'currency'), name='uq_ratecard_one_default_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='ratecardassignment',
            constraint=models.UniqueConstraint(fields=('tenant', 'customer', 'currency'), name='uq_assignment_customer_currency'),
        ),
    ]
