# Generated by Django 6.0.1 on 2026-04-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_backfill_rate_provider_cost'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='uq_card_active_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='idx_card_tenant_lookup',
        ),
        migrations.RemoveField(
            model_name='card',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='card',
            name='dimensions_hash',
        ),
        migrations.RemoveField(
            model_name='card',
            name='event_type',
        ),
    ]
