# Generated by Django 6.0.1 on 2026-04-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_drop_card_legacy_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenantmarkup',
            name='idx_markup_tenant_lookup',
        ),
        migrations.DeleteModel(
            name='TenantMarkup',
        ),
    ]
