# Generated by Django 6.0.1 on 2026-07-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('pricing', '0012_backfill_books'),
        ('tenants', '0017_tenant_run_stale_seconds'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rate',
            name='uq_ratecard_active_tenant',
        ),
        migrations.RemoveConstraint(
            model_name='rate',
            name='uq_ratecard_active_customer',
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('rate_card', 'provider', 'event_type', 'metric_name', 'dimensions_hash', 'currency'), name='uq_rate_active_in_book'),
        ),
    ]
