# Generated by Django 6.0.1 on 2026-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('pricing', '0014_delete_tiered_pricing'),
        ('tenants', '0022_tenantapikey_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rate',
            name='uq_rate_active_in_book',
        ),
        migrations.AddField(
            model_name='rate',
            name='dim1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='dim2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='dim3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='dim4',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='dim5',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='dim6',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rate',
            name='subtask_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='rate',
            name='task_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('rate_card', 'metric_name', 'currency', 'provider', 'event_type', 'task_type', 'subtask_type', 'dim1', 'dim2', 'dim3', 'dim4', 'dim5', 'dim6'), name='uq_rate_active_in_book'),
        ),
        migrations.RemoveField(
            model_name='rate',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='dimensions_hash',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='product_id',
        ),
    ]
