# Generated by Django 6.0.1 on 2026-02-05 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_email'),
        ('subscriptions', '0001_create_stripe_subscription_and_invoice'),
        ('tenants', '0005_add_products_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCostAccumulator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_cost_micros', models.BigIntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_accumulators', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_accumulators', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_customer_cost_accumulator',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer', 'period_start'), name='uq_cost_accumulator_tenant_customer_period')],
            },
        ),
        migrations.CreateModel(
            name='CustomerEconomics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('subscription_revenue_micros', models.BigIntegerField(default=0)),
                ('usage_cost_micros', models.BigIntegerField(default=0)),
                ('gross_margin_micros', models.BigIntegerField(default=0)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economics', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_economics', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_customer_economics',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'customer', 'period_start'), name='uq_economics_tenant_customer_period')],
            },
        ),
    ]
