# Generated by Django 6.0.6 on 2026-06-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_margin_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='customereconomics',
            name='revenue_mode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customereconomics',
            name='total_revenue_micros',
            field=models.BigIntegerField(default=0),
        ),
    ]
