# Generated by Django 6.0.6 on 2026-06-09 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('subscriptions', '0004_customereconomics_revenue_mode_and_more'),
        ('tenants', '0012_backfill_charges_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBillingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('access_fee_micros', models.BigIntegerField(default=0)),
                ('per_seat_micros', models.BigIntegerField(default=0)),
                ('interval', models.CharField(default='month', max_length=5)),
                ('usage_mode', models.CharField(default='invoice_item', max_length=12)),
                ('stripe_access_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_access_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_seat_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_seat_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_plans', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_billing_plan',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_item_id', models.CharField(max_length=255, unique=True)),
                ('axis', models.CharField(max_length=8)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('unit_amount_micros', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='customers.customer')),
                ('stripe_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='subscriptions.stripesubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='tenants.tenant')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.tenantbillingplan')),
            ],
            options={
                'db_table': 'ubb_customer_sub_item',
            },
        ),
        migrations.AddConstraint(
            model_name='tenantbillingplan',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uq_billing_plan_tenant_key'),
        ),
    ]
