# Generated by Django 6.0.6 on 2026-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_tenantbillingplan_customersubscriptionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='hosted_invoice_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='invoice_pdf',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
