# Generated by Django 6.0.6 on 2026-06-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscriptioninvoice_hosted_invoice_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='amount_paid_micros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptioninvoice',
            name='period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
