# Generated by Django 6.0.6 on 2026-06-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscriptioninvoice_amount_paid_micros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
