# Generated by Django 6.0.6 on 2026-06-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptioninvoice_payment_failed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantbillingplan',
            name='pricing_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
