# Generated by Django 6.0.1 on 2026-07-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_stripesubscription_cancel_at_period_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantbillingplan',
            name='usage_mode',
        ),
    ]
