# Generated by Django 6.0.1 on 2026-07-27 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('subscriptions', '0010_remove_tenantbillingplan_usage_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenantbillingplan',
            name='uq_billing_plan_tenant_key',
        ),
        migrations.AlterField(
            model_name='customersubscriptionitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan'),
        ),
        migrations.DeleteModel(
            name='TenantBillingPlan',
        ),
    ]
