// src/features/billing/api/mock-data.ts
import type { MarginDashboardData } from "./types";

export const mockMarginData: MarginDashboardData = {
  stats: {
    blendedMargin: 54.2,
    apiCosts30d: 1247,
    customerBillings30d: 1923,
    marginEarned30d: 676,
  },
  hierarchy: [
    {
      id: "default",
      level: "default",
      name: "Default margin",
      marginPct: 50,
      multiplier: 1.5,
      source: "set",
      parentSource: "\u2014",
      billings30d: 1923,
      children: [
        {
          id: "prod-ps",
          level: "product",
          name: "Property search",
          marginPct: 60,
          multiplier: 1.6,
          source: "override",
          parentSource: "Default: 50%",
          billings30d: 1264,
          children: [
            { id: "card-gem", level: "card", name: "Gemini 2.0 Flash", marginPct: 60, multiplier: 1.6, source: "inherited", parentSource: "Product: 60%", billings30d: 1098 },
            { id: "card-places", level: "card", name: "Google Places", marginPct: 60, multiplier: 1.6, source: "inherited", parentSource: "Product: 60%", billings30d: 99 },
            { id: "card-serper", level: "card", name: "Serper", marginPct: 80, multiplier: 1.8, source: "override", parentSource: "Product: 60%", billings30d: 67 },
          ],
        },
        {
          id: "prod-ds",
          level: "product",
          name: "Doc summariser",
          marginPct: 50,
          multiplier: 1.5,
          source: "inherited",
          parentSource: "Default: 50%",
          billings30d: 411,
          children: [
            { id: "card-claude", level: "card", name: "Claude 3.5 Sonnet", marginPct: 50, multiplier: 1.5, source: "inherited", parentSource: "Product: 50%", billings30d: 411 },
          ],
        },
        {
          id: "prod-cg",
          level: "product",
          name: "Content gen",
          marginPct: 50,
          multiplier: 1.5,
          source: "inherited",
          parentSource: "Default: 50%",
          billings30d: 188,
          children: [
            { id: "card-gpt", level: "card", name: "GPT-4o", marginPct: 50, multiplier: 1.5, source: "inherited", parentSource: "Product: 50%", billings30d: 188 },
          ],
        },
      ],
    },
  ],
  changes: [
    {
      id: "ch-1",
      level: "card",
      targetName: "Serper",
      fromPct: 60,
      toPct: 80,
      description: "Margin changed from 60% to 80%",
      reason: "Higher margin on search \u2014 Serper costs are low relative to value delivered.",
      effectiveness: "immediately",
      appliedBy: "j.smith@co",
      createdAt: "2026-03-18T14:30:00Z",
      estimatedImpact: 8,
    },
    {
      id: "ch-2",
      level: "product",
      targetName: "Property search",
      fromPct: 50,
      toPct: 60,
      description: "Margin changed from 50% to 60%",
      reason: "Increasing margin to reflect higher value-add on property search.",
      effectiveness: "immediately",
      appliedBy: "j.smith@co",
      createdAt: "2026-03-15T10:00:00Z",
      estimatedImpact: 85,
    },
    {
      id: "ch-3",
      level: "default",
      targetName: "Default margin",
      fromPct: 40,
      toPct: 50,
      description: "Default margin changed from 40% to 50%",
      reason: "Initial margin setup during onboarding.",
      effectiveness: "immediately",
      appliedBy: "j.smith@co",
      createdAt: "2026-03-01T09:00:00Z",
      estimatedImpact: 0,
    },
  ],
};
