# Generated by Django 6.0.1 on 2026-02-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
