# Generated by Django 6.0.1 on 2026-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='products',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
