# Generated by Django 6.0.1 on 2026-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_add_products_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='hard_stop_balance_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='run_cost_limit_micros',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
