# Generated by Django 6.0.1 on 2026-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_add_run_hard_stop_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='arrears_threshold_micros',
            new_name='min_balance_micros',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='min_balance_micros',
            field=models.BigIntegerField(default=0),
        ),
    ]
