# Generated by Django 6.0.1 on 2026-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_rename_arrears_to_min_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='rate_limit_per_second',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
