# Generated by Django 6.0.6 on 2026-06-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='require_cost_card_coverage',
            field=models.BooleanField(default=False),
        ),
    ]
