# Generated by Django 6.0.1 on 2026-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='group_label',
            field=models.CharField(default='Products', help_text='Display label for groups in the UI.', max_length=100),
        ),
    ]
