# Generated by Django 6.0.1 on 2026-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_group_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='UX default margin % for new cards. 0 = pass-through. Not used at runtime.', max_digits=5),
        ),
    ]
