# Generated by Django 6.0.6 on 2026-06-09 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_require_cost_card_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConnectOAuthState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(db_index=True, max_length=128, unique=True)),
                ('return_url', models.CharField(blank=True, default='', max_length=2000)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_oauth_states', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_connect_oauth_state',
            },
        ),
    ]
