# Generated by Django 6.0.1 on 2026-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_default_margin_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
