# Generated by Django 6.0.6 on 2026-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_backfill_charges_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='backfill_window_days',
            field=models.PositiveIntegerField(default=34),
        ),
    ]
