# Generated by Django 6.0.6 on 2026-06-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_backfill_window_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_sandbox',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='parent_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sandboxes', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sandbox', True)), fields=('parent_tenant',), name='uq_one_sandbox_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_sandbox', True), ('parent_tenant__isnull', False)), models.Q(('is_sandbox', False), ('parent_tenant__isnull', True)), _connector='OR'), name='ck_sandbox_iff_parent'),
        ),
    ]
