# Generated by Django 6.0.6 on 2026-06-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_is_sandbox_tenant_parent_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='automatic_tax_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
