# Generated by Django 6.0.6 on 2026-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_automatic_tax_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='enforcement_mode',
            field=models.CharField(choices=[('off', 'Off'), ('advisory', 'Advisory'), ('enforcing', 'Enforcing')], db_index=True, default='off', max_length=10),
        ),
    ]
