# Generated by Django 6.0.6 on 2026-06-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_tenant_enforcement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='run_stale_seconds',
            field=models.PositiveIntegerField(default=900),
        ),
    ]
