# Generated by Django 6.0.6 on 2026-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_remove_tenant_min_balance_micros'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantapikey',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('write', 'Write'), ('read', 'Read')], default='admin', max_length=10),
        ),
    ]
