# Generated by Django 6.0.1 on 2026-07-27 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0022_tenantapikey_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionDef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('slot', models.CharField(choices=[('dim1', 'dim1'), ('dim2', 'dim2'), ('dim3', 'dim3'), ('dim4', 'dim4'), ('dim5', 'dim5'), ('dim6', 'dim6')], max_length=8)),
                ('scope', models.CharField(choices=[('task', 'Task'), ('subtask', 'Subtask'), ('event', 'Event')], default='event', max_length=8)),
                ('max_cardinality', models.IntegerField(default=100)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_defs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_dimension_def',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_dimension_def_key'), models.UniqueConstraint(fields=('tenant', 'slot'), name='uq_dimension_def_slot')],
            },
        ),
        migrations.CreateModel(
            name='DimensionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_dimension_value',
                'indexes': [models.Index(fields=['tenant', 'key'], name='idx_dimvalue_tenant_key')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key', 'value'), name='uq_dimension_value')],
            },
        ),
    ]
