// src/features/reconciliation/api/mock-data.ts
import type { ReconciliationData } from "./types";

export const mockReconciliationData: ReconciliationData = {
  card: {
    id: "pc-001",
    name: "Gemini 2.0 Flash",
    provider: "Google",
    cardId: "gemini_2_flash",
    status: "active",
  },
  stats: {
    originalTracked: 2385.83,
    reconciledTotal: 2418.23,
    netAdjustments: 32.40,
    adjustmentCount: 3,
    eventCount: 186000,
    currentVersion: "v3",
    since: "12 Jan 2026",
  },
  versions: [
    {
      id: "v1",
      label: "v1",
      status: "superseded",
      startDate: "2026-01-12",
      endDate: "2026-02-03",
      durationDays: 22,
      eventCount: 42150,
      cost: 387,
      dimensions: [
        { key: "input_tokens", type: "per_unit", unitPrice: 0.0000001, displayPrice: "$0.10 / 1M" },
        { key: "output_tokens", type: "per_unit", unitPrice: 0.0000004, displayPrice: "$0.40 / 1M" },
      ],
    },
    {
      id: "v2",
      label: "v2",
      status: "superseded",
      startDate: "2026-02-03",
      endDate: "2026-02-20",
      durationDays: 17,
      eventCount: 38200,
      cost: 449,
      dimensions: [
        { key: "input_tokens", type: "per_unit", unitPrice: 0.00000015, displayPrice: "$0.15 / 1M" },
        { key: "output_tokens", type: "per_unit", unitPrice: 0.0000006, displayPrice: "$0.60 / 1M" },
        { key: "grounding_requests", type: "flat", unitPrice: 0.035, displayPrice: "$0.035 / req" },
      ],
    },
    {
      id: "v2b",
      label: "v2b",
      status: "retroactive",
      startDate: "2026-02-20",
      endDate: "2026-03-18",
      durationDays: 26,
      eventCount: 61294,
      cost: 781,
      dimensions: [
        { key: "input_tokens", type: "per_unit", unitPrice: 0.0000002, displayPrice: "$0.20 / 1M" },
        { key: "output_tokens", type: "per_unit", unitPrice: 0.0000008, displayPrice: "$0.80 / 1M" },
        { key: "grounding_requests", type: "flat", unitPrice: 0.035, displayPrice: "$0.035 / req" },
      ],
    },
    {
      id: "v3",
      label: "v3",
      status: "active",
      startDate: "2026-03-18",
      endDate: null,
      durationDays: 2,
      eventCount: 44356,
      cost: 835,
      dimensions: [
        { key: "input_tokens", type: "per_unit", unitPrice: 0.0000002, displayPrice: "$0.20 / 1M" },
        { key: "output_tokens", type: "per_unit", unitPrice: 0.0000008, displayPrice: "$0.80 / 1M" },
        { key: "grounding_requests", type: "flat", unitPrice: 0.04, displayPrice: "$0.04 / req" },
      ],
    },
  ],
  timeline: {
    originalTrack: [
      { id: "orig-v1", versionId: "v1", label: "v1", cost: 387, flex: 3, color: "#F1EFE8" },
      { id: "orig-v2", versionId: "v2", label: "v2", cost: 1166, flex: 4, color: "#F1EFE8" },
      { id: "orig-v3", versionId: "v3", label: "v3", cost: 835, flex: 1.5, color: "#F1EFE8" },
    ],
    reconciledTrack: [
      { id: "rec-v1", versionId: "v1", label: "v1", cost: 387, flex: 3, color: "#D3D1C7" },
      { id: "rec-v2", versionId: "v2", label: "v2", cost: 449, flex: 2.5, color: "#D3D1C7" },
      { id: "rec-v2b", versionId: "v2b", label: "v2b", cost: 781, flex: 1.5, color: "#85B7EB" },
      { id: "rec-v3", versionId: "v3", label: "v3", cost: 835, flex: 1.5, color: "#5DCAA5" },
    ],
    originalTotal: 2385.83,
    reconciledTotal: 2418.23,
    adjustmentTotal: 32.40,
    dateMarkers: ["12 Jan 2026", "3 Feb", "20 Feb", "18 Mar", "Today"],
  },
  adjustments: [
    {
      id: "adj-1",
      type: "credit_refund",
      amount: -12.80,
      product: "property_search",
      distributionMode: "lump_sum",
      reason: "Google Cloud service disruption credit.",
      evidence: "https://support.google.com/ticket/12345",
      date: "2026-03-10",
    },
  ],
  auditTrail: [
    {
      id: "log-1",
      type: "period_insert",
      title: "Inserted v2b: 20 Feb — 18 Mar",
      description: "input_tokens $0.15→$0.20/1M. Google price increase.",
      metadata: "61,294 events recalculated. 20 Mar by j.smith@co",
      delta: 38.39,
      deltaLabel: "net delta",
    },
    {
      id: "log-2",
      type: "boundary_shift",
      title: "v1/v2 boundary: 3 Feb → 5 Feb",
      description: "Corrected to actual pricing effective date.",
      metadata: "4,102 events reassigned. 19 Mar by j.smith@co",
      delta: 6.81,
      deltaLabel: "net delta",
    },
    {
      id: "log-3",
      type: "credit_recorded",
      title: "Provider credit — 10 Mar (lump sum)",
      description: "Google Cloud service disruption credit.",
      metadata: "15 Mar by j.smith@co",
      delta: -12.80,
      deltaLabel: "credit",
    },
  ],
};
