"""Regenerate the per-code API exception hierarchy (``ubb/_exceptions_generated.py``).

The error-code registry (``openapi/error-codes.json``) is the machine contract
for problem+json responses (#78). This script turns it into a Python exception
hierarchy — status-family parents (``ConflictError``, ``UnprocessableEntityError``,
…) with per-code leaves under them (``InsufficientBalanceError`` under
``ConflictError``) — so a caller can catch a whole family or one exact registry
code with equal ease (decision #65 / issue #84).

Committed under the SAME ratchet as the spec (ADR-002): CI runs this and fails
on any diff, so the exception surface can never drift from the registry.

Run from anywhere (no third-party deps)::

    python ubb-sdk/codegen/generate_exceptions.py
"""

from __future__ import annotations

import json
from pathlib import Path

CODEGEN_DIR = Path(__file__).resolve().parent
SDK_ROOT = CODEGEN_DIR.parent
REPO_ROOT = SDK_ROOT.parent
REGISTRY_PATH = REPO_ROOT / "openapi" / "error-codes.json"
OUTPUT_PATH = SDK_ROOT / "ubb" / "_exceptions_generated.py"

# Canonical class name for each HTTP status family. 401 is deliberately absent:
# the hand-written UBBAuthError owns authentication failures (it predates the
# registry and carries different semantics), so the transport maps 401 to it
# directly and the registry never mints a second 401 representation.
STATUS_FAMILY_NAMES = {
    400: "BadRequestError",
    403: "ForbiddenError",
    404: "NotFoundError",
    405: "MethodNotAllowedError",
    409: "ConflictError",
    410: "GoneError",
    422: "UnprocessableEntityError",
    429: "RateLimitError",
    500: "InternalServerError",
    503: "ServiceUnavailableError",
}
HAND_OWNED_STATUSES = {401}


def _leaf_class_name(code: str) -> str:
    """PascalCase(code) + 'Error', with a trailing '_error' in the code stripped
    so ``pricing_error`` -> ``PricingError`` (not ``PricingErrorError``)."""
    stem = code[:-6] if code.endswith("_error") else code
    return "".join(part.capitalize() for part in stem.split("_")) + "Error"


def build_source(registry: dict) -> str:
    problems = registry["problems"]

    # status -> family class name, restricted to families we actually see.
    used_statuses = sorted(
        {p["status"] for p in problems.values()} - HAND_OWNED_STATUSES
    )
    families: dict[int, str] = {}
    for status in used_statuses:
        name = STATUS_FAMILY_NAMES.get(status)
        if name is None:
            raise SystemExit(
                f"error-codes.json uses status {status} with no family name in "
                f"STATUS_FAMILY_NAMES — add one to codegen/generate_exceptions.py"
            )
        families[status] = name

    # For each code: either it IS its status family (name collides — a generic
    # code like 'conflict'/'not_found'), or it is a leaf under that family.
    family_names = set(families.values())
    leaves: list[tuple[str, str, int, str]] = []  # (class, parent, status, code)
    code_to_class: dict[str, str] = {}
    for code in sorted(problems):
        status = problems[code]["status"]
        if status in HAND_OWNED_STATUSES:
            continue  # 401 -> UBBAuthError, mapped in the transport
        family = families[status]
        leaf = _leaf_class_name(code)
        if leaf in family_names and leaf == family:
            code_to_class[code] = family  # the generic code == its family
        else:
            leaves.append((leaf, family, status, code))
            code_to_class[code] = leaf

    lines: list[str] = []
    w = lines.append
    w("# @generated by ubb-sdk/codegen/generate_exceptions.py — do not edit by hand.")
    w('"""Per-code API exception hierarchy, generated from openapi/error-codes.json.')
    w("")
    w("Status-family parents (ConflictError, UnprocessableEntityError, …) group the")
    w("registry codes by HTTP status; per-code leaves (InsufficientBalanceError …)")
    w("sit under their family. Catch a family to handle every code in it, or one")
    w("leaf to handle exactly one registry code. All extend UBBAPIError, so")
    w("existing ``except UBBAPIError`` handlers keep working (issue #84).")
    w('"""')
    w("")
    w("from __future__ import annotations")
    w("")
    w("from ubb.exceptions import UBBAPIError")
    w("")
    w("")
    w("class _ProblemError(UBBAPIError):")
    w('    """Base for every registry-derived error. ``STATUS`` is the family\'s')
    w('    HTTP status; ``CODE`` is the canonical registry code (the response\'s')
    w('    own ``code`` wins when present)."""')
    w("")
    w("    STATUS: int = 0")
    w("    CODE: str | None = None")
    w("")
    w("    def __init__(self, detail: str = \"\", code: str | None = None) -> None:")
    w("        super().__init__(self.STATUS, detail, code=code if code is not None else self.CODE)")
    w("")

    # Family parents, sorted by status for stable output.
    for status in sorted(families):
        family = families[status]
        generic_code = _generic_code_for(problems, status)
        w("")
        w(f"class {family}(_ProblemError):")
        w(f"    STATUS = {status}")
        w(f"    CODE = {generic_code!r}")
        w("")

    # Leaves, sorted by class name for stable output.
    for leaf, family, status, code in sorted(leaves):
        w("")
        w(f"class {leaf}({family}):")
        w(f"    STATUS = {status}")
        w(f"    CODE = {code!r}")
        w("")

    # Registries + dispatch.
    w("")
    w("STATUS_FAMILIES: dict[int, type[_ProblemError]] = {")
    for status in sorted(families):
        w(f"    {status}: {families[status]},")
    w("}")
    w("")
    w("PROBLEM_CODES: dict[str, type[_ProblemError]] = {")
    for code in sorted(code_to_class):
        w(f"    {code!r}: {code_to_class[code]},")
    w("}")
    w("")
    w("")
    w("def exception_for(status_code: int, code: str | None, detail: str = \"\") -> UBBAPIError:")
    w('    """Map a problem+json (status, code) to the most specific exception.')
    w("")
    w("    Exact registry code wins; else the status family; else a bare")
    w('    UBBAPIError for an undocumented status."""')
    w("    cls = PROBLEM_CODES.get(code) if code else None")
    w("    if cls is None:")
    w("        cls = STATUS_FAMILIES.get(status_code)")
    w("    if cls is None:")
    w("        return UBBAPIError(status_code, detail, code=code)")
    w("    return cls(detail, code=code)")
    w("")
    w("")
    _all = (
        [families[s] for s in sorted(families)]
        + sorted(leaf for leaf, *_ in leaves)
        + ["STATUS_FAMILIES", "PROBLEM_CODES", "exception_for"]
    )
    w("__all__ = [")
    for name in _all:
        w(f"    {name!r},")
    w("]")
    return "\n".join(lines) + "\n"


def _generic_code_for(problems: dict, status: int) -> str | None:
    """The registry code whose leaf name equals its family (e.g. 'conflict' for
    409) — the family's canonical CODE. None if the registry has no generic code
    for that status (then the family carries no default code)."""
    family = STATUS_FAMILY_NAMES[status]
    for code, meta in problems.items():
        if meta["status"] == status and _leaf_class_name(code) == family:
            return code
    return None


def main() -> None:
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    OUTPUT_PATH.write_text(build_source(registry), encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
