"""Regenerate the committed SDK transport+DTO core (``ubb/_core``).

The generated core is the single source of truth for the SDK's DTOs, enums, and
transport — never hand-typed again (issue #84, decision #65). It is committed
in-repo under the same ratchet as ``openapi/v1.json`` (ADR-002): CI runs this
script and fails on any diff, so a surface change that skips regeneration — or a
hand edit to ``ubb/_core`` — turns CI red.

Run from anywhere::

    python ubb-sdk/codegen/generate_core.py

Requires the pinned generator (``pip install -e 'ubb-sdk[codegen]'`` or
``pip install openapi-python-client==0.29.0``). The generator version is the
ONLY input to the committed bytes: the ruff post-hook is disabled in
``config.yaml`` and this script normalizes newlines to LF, so Windows and the
Linux CI runner produce identical output.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
import sys
from pathlib import Path

CODEGEN_DIR = Path(__file__).resolve().parent
SDK_ROOT = CODEGEN_DIR.parent
REPO_ROOT = SDK_ROOT.parent
SPEC_PATH = REPO_ROOT / "openapi" / "v1.json"
CONFIG_PATH = CODEGEN_DIR / "config.yaml"
OUTPUT_PATH = SDK_ROOT / "ubb" / "_core"
STAMP_PATH = SDK_ROOT / "ubb" / "_spec_revision.py"

# The exact generator this core was produced with (issue #84 / decision #65):
# 0.x with breaking minors, so it is pinned exactly here and in pyproject's
# ``codegen`` extra. Bumping it is a deliberate, reviewed PR.
GENERATOR = "openapi-python-client"
GENERATOR_VERSION = "0.29.0"

# A short banner prepended to __init__.py so a reader who lands on the package
# knows it is generated and how to change it. Kept out of every module (it would
# be noise x200); the package docstring is the natural home.
GENERATED_MARKER = "# @generated by ubb-sdk/codegen/generate_core.py — do not edit by hand.\n"


def _to_lf(path: Path) -> None:
    """Rewrite one file with LF line endings (bytes identical across OSes)."""
    raw = path.read_bytes()
    lf = raw.replace(b"\r\n", b"\n")
    if lf != raw:
        path.write_bytes(lf)


def _normalize_newlines(root: Path) -> int:
    """LF-normalize every file under ``root``. Returns the count."""
    n = 0
    for path in sorted(root.rglob("*")):
        if path.is_file():
            _to_lf(path)
            n += 1
    return n


def _write_spec_stamp() -> None:
    """Stamp the exact committed-spec revision this core was generated from.

    Each SDK release is tied to the spec it was cut against (issue #84): the
    sha256 of the committed bytes plus the document's own version. Regenerated
    from the committed spec, so the ratchet's zero-diff gate covers it too.
    """
    spec_bytes = SPEC_PATH.read_bytes()
    sha = hashlib.sha256(spec_bytes).hexdigest()
    version = json.loads(spec_bytes).get("info", {}).get("version", "")
    STAMP_PATH.write_text(
        '# @generated by ubb-sdk/codegen/generate_core.py — do not edit by hand.\n'
        '"""The committed-spec revision this SDK core was generated from (issue #84)."""\n\n'
        f'SPEC_VERSION = {version!r}\n'
        f'SPEC_SHA256 = {sha!r}\n'
        f'GENERATOR = {GENERATOR!r}\n'
        f'GENERATOR_VERSION = {GENERATOR_VERSION!r}\n',
        encoding="utf-8",
    )


def main() -> None:
    if not SPEC_PATH.exists():
        sys.exit(f"spec not found: {SPEC_PATH}")

    # A clean slate: the generator overwrites files it emits but leaves stale
    # ones (e.g. a model dropped from the spec) behind, which would defeat the
    # zero-diff gate. Wipe first so the tree is exactly the generator's output.
    if OUTPUT_PATH.exists():
        shutil.rmtree(OUTPUT_PATH)

    cmd = [
        sys.executable, "-m", "openapi_python_client", "generate",
        "--path", str(SPEC_PATH),
        "--config", str(CONFIG_PATH),
        "--meta", "none",
        "--output-path", str(OUTPUT_PATH),
        "--overwrite",
    ]
    result = subprocess.run(cmd, cwd=str(SDK_ROOT), capture_output=True, text=True)
    # Exit 0 with warnings is normal (e.g. an untyped response the spec leaves
    # open); a real failure is a non-zero exit. Surface stderr either way.
    if result.stderr.strip():
        print(result.stderr, file=sys.stderr)
    if result.returncode != 0:
        sys.exit(f"openapi-python-client failed (exit {result.returncode})")
    if not OUTPUT_PATH.exists():
        sys.exit("generator produced no output package")

    init_path = OUTPUT_PATH / "__init__.py"
    init_text = init_path.read_text(encoding="utf-8")
    if not init_text.startswith(GENERATED_MARKER):
        init_path.write_text(GENERATED_MARKER + init_text, encoding="utf-8")

    _write_spec_stamp()

    files = _normalize_newlines(OUTPUT_PATH)
    _to_lf(STAMP_PATH)
    print(f"regenerated {OUTPUT_PATH.relative_to(REPO_ROOT)}: {files} files (LF-normalized)")
    print(f"stamped {STAMP_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
