# @generated by ubb-sdk/codegen/generate_core.py — do not edit by hand.
"""The committed-spec revision this SDK core was generated from (issue #84)."""

SPEC_VERSION = 'v1'
SPEC_SHA256 = '4de74abb9890f02e416b5bb2d8fb365c9fc63822dda5a80d41d0134c12273c25'
GENERATOR = 'openapi-python-client'
GENERATOR_VERSION = '0.29.0'
