# @generated by ubb-sdk/codegen/generate_core.py — do not edit by hand.
"""The committed-spec revision this SDK core was generated from (issue #84)."""

SPEC_VERSION = 'v1'
SPEC_SHA256 = '071ebc5c8309903be31efd9efff3348f826ca6b2a6e30a2810a5a652b4e1aa5d'
GENERATOR = 'openapi-python-client'
GENERATOR_VERSION = '0.29.0'
