# UBB integration, generated by ubb-codegen (renderer catalogue version 4).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 1
# sdk_major_version = 3
# target = "python_sdk"
# configuration_fingerprint = "sha256:b98edfe9988fe7eb682d1402f1834288d812c2f0a3433aa8bd84294dcf54e0aa"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "complete"
# COMPLETE. Every call has what it needs to run.

# Nothing is reported against this integration.

# Resolved from these declarations:
# task_type = "report-generation"
# event_type = "it's a $5 chat-completion" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"
# provider = "o'reilly & co"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds. Every one is required:
#   leave one out and Python raises TypeError at the call.
#   os.environ[...] is a credential. UBB withholds it from this file.
# A literal with no configured value, or one this Code Builder version
# cannot yet generate, is a state of a literal, not a fourth kind: it is
# written as a call that raises, saying which.

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from typing import Iterator

from ubb import RecordUsageResponse, StartedTask, UBBClient, UBBStopRequested

__all__ = [
    "UBBEnvironmentNotSet",
    "start_task",
    "unit_of_work",
    "record_it_s_a__5_chat_completion",
    "backfill_it_s_a__5_chat_completion",
]

_LOGGER = logging.getLogger("ubb_integration")

_CLIENT = None


# What building the client raises when a variable it needs is not set.
class UBBEnvironmentNotSet(RuntimeError):
    pass


# The client is built on first use, so importing this file needs no
# credentials.
def _client() -> UBBClient:
    global _CLIENT
    if _CLIENT is None:
        # Not a secret, and required: the base URL of the UBB API this code
        # calls. This file holds no address of its own.
        base_url = os.environ.get("UBB_BASE_URL")
        if not base_url:
            raise UBBEnvironmentNotSet(
                "UBB_BASE_URL is not set. Set it in the environment this code runs in."
            )
        _CLIENT = UBBClient(
            # A credential. Set it in the environment this code runs in, and never
            # write its value into a file.
            api_key=os.environ["UBB_API_KEY"],
            base_url=base_url,
        )
    return _CLIENT


# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is priced event by event, as each one is recorded.
def start_task(
    *,
    customer_id,
    idempotency_key,
) -> StartedTask:
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        # task_type = "report-generation" · task_type "report-generation"
        # task_type.pricing_mode = "event_priced" · task_type "report-generation"
        # task_type.uncapped = true · task_type "report-generation"
        task_type="report-generation",
    )


_start_task = start_task


# The whole piece of work, as one block. Declare how it ended inside the
# block, with complete(), fail(outcome_reason) or cancel().
# This is the one place a stop is caught. The event that carried it was
# recorded and charged: never send it again. The stop is logged and
# raised again, so whatever runs this work can honour its scope.
@contextmanager
def unit_of_work(
    *,
    customer_id,
    idempotency_key,
) -> Iterator[StartedTask]:
    try:
        with _start_task(
            customer_id=customer_id,
            idempotency_key=idempotency_key,
        ) as task:
            yield task
    except UBBStopRequested as stop:
        _LOGGER.warning(
            "UBB requested a stop. The event sent as %r was recorded and must not be sent again: %r",
            stop.idempotency_key,
            stop.result,
        )
        raise


def _send_it_s_a__5_chat_completion(
    *,
    customer_id,
    idempotency_key,
    task_id,
    _HOME,
    __whoami_,
    back_slash,
    back_tick,
    _braces_,
    cache_read,
    cache_read_tokens,
    value_class,
    dou_ble,
    it_s,
    na_ve____,
    per_cent_,
    response,
    recorded_at,
    stop_behavior,
) -> RecordUsageResponse:
    return _client().record_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        # event_type = "it's a $5 chat-completion" · event_type "it's a $5 chat-completion"
        # event_type.costing_method = "calculated" · event_type "it's a $5 chat-completion"
        # event_type.source_shape_id = "google.gemini.rest.v1" · event_type "it's a $5 chat-completion"
        # event_type.response_shape_representation = "json" · event_type "it's a $5 chat-completion"
        event_type="it's a $5 chat-completion",
        # provider = "o'reilly & co" · provider "o'reilly & co"
        provider="o'reilly & co",
        measurements={
            # measurements = "$HOME" · event_type "it's a $5 chat-completion"
            # measurements.$HOME.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.$HOME.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.$HOME.required_for_costing = true · event_type "it's a $5 chat-completion"
            "$HOME": _HOME,
            # measurements = "$(whoami)" · event_type "it's a $5 chat-completion"
            # measurements.$(whoami).value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.$(whoami).unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.$(whoami).required_for_costing = true · event_type "it's a $5 chat-completion"
            "$(whoami)": __whoami_,
            # measurements = "back\\slash" · event_type "it's a $5 chat-completion"
            # measurements.back\slash.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.back\slash.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.back\slash.required_for_costing = true · event_type "it's a $5 chat-completion"
            "back\\slash": back_slash,
            # measurements = "back`tick" · event_type "it's a $5 chat-completion"
            # measurements.back`tick.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.back`tick.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.back`tick.required_for_costing = true · event_type "it's a $5 chat-completion"
            "back`tick": back_tick,
            # measurements = "{braces}" · event_type "it's a $5 chat-completion"
            # measurements.{braces}.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.{braces}.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.{braces}.required_for_costing = true · event_type "it's a $5 chat-completion"
            "{braces}": _braces_,
            # measurements = "cache-read" · event_type "it's a $5 chat-completion"
            # measurements.cache-read.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.cache-read.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.cache-read.required_for_costing = true · event_type "it's a $5 chat-completion"
            "cache-read": cache_read,
            # measurements = "cache read tokens" · event_type "it's a $5 chat-completion"
            # measurements.cache read tokens.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.cache read tokens.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.cache read tokens.required_for_costing = true · event_type "it's a $5 chat-completion"
            "cache read tokens": cache_read_tokens,
            # measurements = "class" · event_type "it's a $5 chat-completion"
            # measurements.class.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.class.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.class.required_for_costing = true · event_type "it's a $5 chat-completion"
            "class": value_class,
            # measurements = "dou\"ble" · event_type "it's a $5 chat-completion"
            # measurements.dou"ble.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.dou"ble.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.dou"ble.required_for_costing = true · event_type "it's a $5 chat-completion"
            "dou\"ble": dou_ble,
            # measurements = "it's" · event_type "it's a $5 chat-completion"
            # measurements.it's.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.it's.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.it's.required_for_costing = true · event_type "it's a $5 chat-completion"
            "it's": it_s,
            # measurements = "naïve–日本語" · event_type "it's a $5 chat-completion"
            # measurements.naïve–日本語.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.naïve–日本語.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.naïve–日本語.required_for_costing = true · event_type "it's a $5 chat-completion"
            "naïve–日本語": na_ve____,
            # measurements = "per.cent%" · event_type "it's a $5 chat-completion"
            # measurements.per%2Ecent%25.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.per%2Ecent%25.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.per%2Ecent%25.required_for_costing = true · event_type "it's a $5 chat-completion"
            "per.cent%": per_cent_,
            # measurements = "read off a hyphenated key" · event_type "it's a $5 chat-completion"
            # measurements.read off a hyphenated key.value_type = "integer" · event_type "it's a $5 chat-completion"
            # measurements.read off a hyphenated key.unit = "token" · event_type "it's a $5 chat-completion"
            # measurements.read off a hyphenated key.required_for_costing = true · event_type "it's a $5 chat-completion"
            # measurements.read off a hyphenated key.source_path = ["x-usage","total tokens"] · event_type "it's a $5 chat-completion"
            "read off a hyphenated key": response["x-usage"]["total tokens"],
        },
        recorded_at=recorded_at,
        stop_behavior=stop_behavior,
    )


# A stop is raised as UBBStopRequested, which is not an Exception, so
# your own `except Exception` cannot swallow it. Nothing here catches it.
# This file never calls your supplier. Pass the response you already
# have.
def record_it_s_a__5_chat_completion(
    *,
    customer_id,
    idempotency_key,
    task_id,
    _HOME,
    __whoami_,
    back_slash,
    back_tick,
    _braces_,
    cache_read,
    cache_read_tokens,
    value_class,
    dou_ble,
    it_s,
    na_ve____,
    per_cent_,
    response,
) -> RecordUsageResponse:
    return _send_it_s_a__5_chat_completion(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        _HOME=_HOME,
        __whoami_=__whoami_,
        back_slash=back_slash,
        back_tick=back_tick,
        _braces_=_braces_,
        cache_read=cache_read,
        cache_read_tokens=cache_read_tokens,
        value_class=value_class,
        dou_ble=dou_ble,
        it_s=it_s,
        na_ve____=na_ve____,
        per_cent_=per_cent_,
        response=response,
        recorded_at=None,
        stop_behavior="raise",
    )


# For work that has already happened. A stop is returned on the
# acknowledgement and not raised, so the rest of a backlog is still
# recorded. Read `stop` on what this returns.
def backfill_it_s_a__5_chat_completion(
    *,
    customer_id,
    idempotency_key,
    task_id,
    _HOME,
    __whoami_,
    back_slash,
    back_tick,
    _braces_,
    cache_read,
    cache_read_tokens,
    value_class,
    dou_ble,
    it_s,
    na_ve____,
    per_cent_,
    response,
    recorded_at,
) -> RecordUsageResponse:
    return _send_it_s_a__5_chat_completion(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        _HOME=_HOME,
        __whoami_=__whoami_,
        back_slash=back_slash,
        back_tick=back_tick,
        _braces_=_braces_,
        cache_read=cache_read,
        cache_read_tokens=cache_read_tokens,
        value_class=value_class,
        dou_ble=dou_ble,
        it_s=it_s,
        na_ve____=na_ve____,
        per_cent_=per_cent_,
        response=response,
        recorded_at=recorded_at,
        stop_behavior="return",
    )
