# Generated by Django 6.0.6 on 2026-06-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_postpaid_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusageinvoice',
            name='residual_micros',
            field=models.BigIntegerField(default=0),
        ),
    ]
