# Generated by Django 6.0.6 on 2026-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_customerusageinvoice_residual_micros'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusageinvoice',
            name='hosted_invoice_url',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='invoice_pdf',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerusageinvoice',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
