# Generated by Django 6.0.6 on 2026-06-11 15:14

from django.db import migrations, models

LEGACY_ERROR = (
    "migrated: pre-metadata era — verify in Stripe (customer + period + amount) "
    "before repush"
)


def supersede_pooled_seat_rows(apps, schema_editor):
    """(c) FIRST: pending/failed rows keyed on a POOLED seat. The owner-first
    service re-keys every push on resolve_billing_owner(), so a seat-keyed row
    can never transition again — park it as skipped/seat_superseded."""
    CustomerUsageInvoice = apps.get_model("invoicing", "CustomerUsageInvoice")
    CustomerUsageInvoice.objects.filter(
        status__in=["pending", "failed"],
        customer__account_type="seat",
        customer__parent__isnull=False,
        customer__parent__billing_topology="pooled",
    ).update(status="skipped", skip_reason="seat_superseded")


def fail_legacy_rows(apps, schema_editor):
    """(a) THEN: all remaining legacy pending/failed rows -> failed_permanent.

    Pre-F0.1 code persisted nothing between claim and Phase 3, so an attempted
    'pending' row is indistinguishable from a never-attempted one, its Stripe
    invoice — possibly finalized — carries NO metadata for the recovery lookup
    to find, and the old reconcile refreshed updated_at hourly so such rows are
    typically already past the 24h idempotency-key window. Safe-by-default."""
    CustomerUsageInvoice = apps.get_model("invoicing", "CustomerUsageInvoice")
    CustomerUsageInvoice.objects.filter(status__in=["pending", "failed"]).update(
        status="failed_permanent", last_attempt_error=LEGACY_ERROR)


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_customerusageinvoice_hosted_invoice_url_and_more'),
        ('customers', '0011_customer_account_type_customer_billing_topology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusageinvoice',
            name='first_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='last_attempt_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='push_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerusageinvoice',
            name='push_phase',
            field=models.CharField(blank=True, choices=[('', 'Not started'), ('invoice_created', 'Invoice created'), ('items_pinned', 'Items pinned'), ('finalized', 'Finalized')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerusageinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pushing', 'Pushing'), ('pushed', 'Pushed'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('failed_permanent', 'Failed permanent')], db_index=True, default='pending', max_length=20),
        ),
        # Order matters: seat rule (c) must win over legacy rule (a).
        migrations.RunPython(supersede_pooled_seat_rows, migrations.RunPython.noop),
        migrations.RunPython(fail_legacy_rows, migrations.RunPython.noop),
    ]
