# Generated by Django 6.0.6 on 2026-06-11 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_residual_ledgers(apps, schema_editor):
    """Seed each customer's ledger with the residual_micros of their LATEST
    (max period_start) pushed row — exactly the value the old lock-free chain
    read (latest prior pushed row) would have returned for their next push.
    Customers with no pushed rows have no residual in flight: no ledger row
    (the first push's get_or_create reservation creates it lazily)."""
    CustomerUsageInvoice = apps.get_model("invoicing", "CustomerUsageInvoice")
    PostpaidResidualLedger = apps.get_model("invoicing", "PostpaidResidualLedger")
    seeded, seen = 0, set()
    rows = CustomerUsageInvoice.objects.filter(status="pushed").order_by(
        "customer_id", "-period_start").iterator()
    for row in rows:  # first row per customer = the latest pushed period
        if row.customer_id in seen:
            continue
        seen.add(row.customer_id)
        _, created = PostpaidResidualLedger.objects.get_or_create(
            customer_id=row.customer_id,
            defaults={"tenant_id": row.tenant_id, "balance_micros": row.residual_micros})
        seeded += int(created)
    print(f"invoicing.0006: seeded {seeded} residual ledger(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('invoicing', '0005_bounded_resumable_push'),
        ('tenants', '0012_backfill_charges_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusageinvoice',
            name='carry_in_micros',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PostpaidResidualLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_micros', models.BigIntegerField(default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residual_ledger', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residual_ledgers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_postpaid_residual_ledger',
            },
        ),
        # Reverse is the schema reverse above (drop table + field); the seed
        # data lives in the dropped table so the data reverse is a noop.
        migrations.RunPython(seed_residual_ledgers, migrations.RunPython.noop),
    ]
