# Generated by Django 6.0.6 on 2026-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_residual_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerusageinvoice',
            name='invoice_kind',
            field=models.CharField(choices=[('standalone', 'Standalone'), ('consolidated', 'Consolidated')], default='standalone', max_length=12),
        ),
        migrations.AddField(
            model_name='postpaidusageconfig',
            name='consolidate_with_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
