# UBB integration, generated by ubb-codegen (renderer catalogue version 1).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 1
# sdk_major_version = 3
# target = "python_sdk"
# configuration_fingerprint = "sha256:36af256701e35c0c04a595d3a40f537c399286364e9f614a285bac8e4db9deef"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "complete"
# COMPLETE. Every call has what it needs to run.

# Nothing is reported against this integration.

# Resolved from these declarations:
# task_type = "web_research"
# event_type = "web.search" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"
# provider = "serpapi"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds. Every one is required:
#   leave one out and Python raises TypeError at the call.
#   os.environ[...] is a credential. UBB withholds it from this file.
# A literal with no configured value is a state of a literal, not a
# fourth kind: it is written as a call that raises, naming what is
# missing.

from __future__ import annotations

import logging
import os
from contextlib import contextmanager
from decimal import Decimal, InvalidOperation
from typing import Iterator

from ubb import RecordUsageResponse, StartedTask, UBBClient, UBBStopRequested

__all__ = [
    "ReportedCostNotRepresentable",
    "ReportedCostCurrencyRefused",
    "start_task",
    "unit_of_work",
    "record_web_search",
    "backfill_web_search",
]

_LOGGER = logging.getLogger("ubb_integration")

_CLIENT = None


# The client is built on first use, so importing this file needs no
# credentials.
def _client() -> UBBClient:
    global _CLIENT
    if _CLIENT is None:
        _CLIENT = UBBClient(
            # A credential. Set it in the environment this code runs in, and never
            # write its value into a file.
            api_key=os.environ["UBB_API_KEY"],
            # Not a secret. Set it to point this file at another server; unset or
            # empty, the default is used.
            base_url=os.environ.get("UBB_BASE_URL") or "https://api.ubb.dev",
        )
    return _CLIENT


# A cost a supplier reports is converted to whole micros once, here,
# through Decimal. A binary float is refused. An amount finer than a
# micro is refused, never rounded. A currency other than the declared
# one fails, never converts.
class ReportedCostNotRepresentable(ValueError):
    pass


class ReportedCostCurrencyRefused(ValueError):
    pass


_MICROS_PER_MAJOR_UNIT = 1000000
_MICROS_PER_MINOR_UNIT = {
    "aud": 10000,
    "brl": 10000,
    "cad": 10000,
    "chf": 10000,
    "czk": 10000,
    "dkk": 10000,
    "eur": 10000,
    "gbp": 10000,
    "hkd": 10000,
    "inr": 10000,
    "mxn": 10000,
    "nok": 10000,
    "nzd": 10000,
    "pln": 10000,
    "sek": 10000,
    "sgd": 10000,
    "usd": 10000,
    "zar": 10000,
}
_MICROS_LIMIT = 2 ** 63 - 1
_EXPONENT_LIMIT = 40


def _minor_unit(currency):
    try:
        return _MICROS_PER_MINOR_UNIT[currency.lower()]
    except (AttributeError, KeyError):
        raise ReportedCostCurrencyRefused(
            f"{currency!r} is not a currency UBB holds"
        ) from None


def _pin_currency(declared, reported):
    pinned = (declared or "").strip().lower()
    supplied = (reported or "").strip().lower()
    if not pinned and not supplied:
        raise ReportedCostCurrencyRefused(
            "this cost is denominated in no currency"
        )
    if pinned and supplied and pinned != supplied:
        raise ReportedCostCurrencyRefused(
            f"the supplier reported this cost in another currency than the declared one: {supplied!r}, not {pinned!r}"
        )
    code = pinned or supplied
    _minor_unit(code)
    return code


def _to_micros(amount, representation, currency):
    if representation == "micros":
        multiplier = 1
    elif representation == "minor_units":
        multiplier = _minor_unit(currency)
    elif representation == "major_units_decimal":
        multiplier = _MICROS_PER_MAJOR_UNIT
    else:
        raise ReportedCostNotRepresentable(
            f"{representation!r} is not an amount representation"
        )
    if isinstance(amount, bool):
        raise ReportedCostNotRepresentable(
            f"{amount!r} is a flag, not a reported cost"
        )
    if isinstance(amount, float):
        raise ReportedCostNotRepresentable(
            f"{amount!r} is a binary float, and a reported cost is money: pass its decimal text or an integer"
        )
    if amount is None:
        raise ReportedCostNotRepresentable(
            "no cost was reported, and a missing cost is not a zero"
        )
    try:
        exact = Decimal(amount)
    except (InvalidOperation, TypeError, ValueError):
        raise ReportedCostNotRepresentable(
            f"{amount!r} is not a number"
        ) from None
    if not exact.is_finite():
        raise ReportedCostNotRepresentable(
            f"{amount!r} is not a finite amount"
        )
    sign, digits, exponent = exact.as_tuple()
    digits = list(digits)
    while exponent < 0 and len(digits) > 1 and digits[-1] == 0:
        digits.pop()
        exponent += 1
    unsigned = 0
    for digit in digits:
        unsigned = unsigned * 10 + digit
    if abs(exponent) > _EXPONENT_LIMIT:
        raise ReportedCostNotRepresentable(
            f"{amount!r} is not an amount of money that can be held: its exponent is out of range"
        )
    if exponent >= 0:
        micros = unsigned * 10 ** exponent * multiplier
    else:
        micros, remainder = divmod(unsigned * multiplier, 10 ** -exponent)
        if remainder:
            raise ReportedCostNotRepresentable(
                f"{amount!r} is not a whole number of micros, and a reported cost is never rounded"
            )
    if micros > _MICROS_LIMIT:
        raise ReportedCostNotRepresentable(
            f"{amount!r} is more micros than can be held"
        )
    return -micros if sign else micros


# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is priced event by event, as each one is recorded.
def start_task(
    *,
    customer_id,
    idempotency_key,
) -> StartedTask:
    return _client().start_task(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        # task_type = "web_research" · task_type "web_research"
        # task_type.pricing_mode = "event_priced" · task_type "web_research"
        # task_type.uncapped = true · task_type "web_research"
        task_type="web_research",
    )


_start_task = start_task


# The whole piece of work, as one block. Declare how it ended inside the
# block, with complete(), fail(outcome_reason) or cancel().
# This is the one place a stop is caught. The event that carried it was
# recorded and charged: never send it again. The stop is logged and
# raised again, so whatever runs this work can honour its scope.
@contextmanager
def unit_of_work(
    *,
    customer_id,
    idempotency_key,
) -> Iterator[StartedTask]:
    try:
        with _start_task(
            customer_id=customer_id,
            idempotency_key=idempotency_key,
        ) as task:
            yield task
    except UBBStopRequested as stop:
        _LOGGER.warning(
            "UBB requested a stop. The event sent as %r was recorded and must not be sent again: %r",
            stop.idempotency_key,
            stop.result,
        )
        raise


def _send_web_search(
    *,
    customer_id,
    idempotency_key,
    task_id,
    searches,
    reported_cost,
    recorded_at,
    stop_behavior,
) -> RecordUsageResponse:
    return _client().record_usage(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        # event_type = "web.search" · event_type "web.search"
        # event_type.costing_method = "reported" · event_type "web.search"
        event_type="web.search",
        # provider = "serpapi" · provider "serpapi"
        provider="serpapi",
        measurements={
            # measurements = "searches" · event_type "web.search"
            # measurements.searches.value_type = "integer" · event_type "web.search"
            # measurements.searches.unit = "search" · event_type "web.search"
            # measurements.searches.required_for_costing = false · event_type "web.search"
            "searches": searches,
        },
        # provider_cost_micros.amount_representation = "major_units_decimal" · event_type "web.search"
        provider_cost_micros=_to_micros(reported_cost, "major_units_decimal", _pin_currency("usd", None)),
        # currency = "usd" · event_type "web.search"
        currency="usd",
        recorded_at=recorded_at,
        stop_behavior=stop_behavior,
    )


# A stop is raised as UBBStopRequested, which is not an Exception, so
# your own `except Exception` cannot swallow it. Nothing here catches it.
def record_web_search(
    *,
    customer_id,
    idempotency_key,
    task_id,
    searches,
    reported_cost,
) -> RecordUsageResponse:
    return _send_web_search(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        searches=searches,
        reported_cost=reported_cost,
        recorded_at=None,
        stop_behavior="raise",
    )


# For work that has already happened. A stop is returned on the
# acknowledgement and not raised, so the rest of a backlog is still
# recorded. Read `stop` on what this returns.
def backfill_web_search(
    *,
    customer_id,
    idempotency_key,
    task_id,
    searches,
    reported_cost,
    recorded_at,
) -> RecordUsageResponse:
    return _send_web_search(
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        task_id=task_id,
        searches=searches,
        reported_cost=reported_cost,
        recorded_at=recorded_at,
        stop_behavior="return",
    )
