/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppPricingCardsIndexRouteImport } from './routes/_app/pricing-cards/index'
import { Route as AppExportIndexRouteImport } from './routes/_app/export/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing/index'
import { Route as AppPricingCardsNewRouteImport } from './routes/_app/pricing-cards/new'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingCardsIndexRoute = AppPricingCardsIndexRouteImport.update({
  id: '/pricing-cards/',
  path: '/pricing-cards/',
  getParentRoute: () => AppRoute,
} as any)
const AppExportIndexRoute = AppExportIndexRouteImport.update({
  id: '/export/',
  path: '/export/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingCardsNewRoute = AppPricingCardsNewRouteImport.update({
  id: '/pricing-cards/new',
  path: '/pricing-cards/new',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/pricing-cards/new': typeof AppPricingCardsNewRoute
  '/billing/': typeof AppBillingIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/export/': typeof AppExportIndexRoute
  '/pricing-cards/': typeof AppPricingCardsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AppIndexRoute
  '/pricing-cards/new': typeof AppPricingCardsNewRoute
  '/billing': typeof AppBillingIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/export': typeof AppExportIndexRoute
  '/pricing-cards': typeof AppPricingCardsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/pricing-cards/new': typeof AppPricingCardsNewRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/export/': typeof AppExportIndexRoute
  '/_app/pricing-cards/': typeof AppPricingCardsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/pricing-cards/new'
    | '/billing/'
    | '/customers/'
    | '/export/'
    | '/pricing-cards/'
    | '/products/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/pricing-cards/new'
    | '/billing'
    | '/customers'
    | '/export'
    | '/pricing-cards'
    | '/products'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/'
    | '/_app/pricing-cards/new'
    | '/_app/billing/'
    | '/_app/customers/'
    | '/_app/export/'
    | '/_app/pricing-cards/'
    | '/_app/products/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing-cards/': {
      id: '/_app/pricing-cards/'
      path: '/pricing-cards'
      fullPath: '/pricing-cards/'
      preLoaderRoute: typeof AppPricingCardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export/': {
      id: '/_app/export/'
      path: '/export'
      fullPath: '/export/'
      preLoaderRoute: typeof AppExportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing-cards/new': {
      id: '/_app/pricing-cards/new'
      path: '/pricing-cards/new'
      fullPath: '/pricing-cards/new'
      preLoaderRoute: typeof AppPricingCardsNewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppPricingCardsNewRoute: typeof AppPricingCardsNewRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppExportIndexRoute: typeof AppExportIndexRoute
  AppPricingCardsIndexRoute: typeof AppPricingCardsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppPricingCardsNewRoute: AppPricingCardsNewRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppExportIndexRoute: AppExportIndexRoute,
  AppPricingCardsIndexRoute: AppPricingCardsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
