"""The Charge projects onto exactly one marked posting, and that posting is
what reaches the money (#417, spec §12).

#416 made a delivered unit of work sold at one agreed price produce a canonical
`pricing.Charge` and said in its own module that the projected posting was not
its subject. This is that posting: **billed cost = the amount, provider cost =
zero, no measurement record, Grouping Fields inherited, `kind` = `task_charge`,
and no Event Type at all.**

**WHY A PROJECTION AND NOT A CANONICAL SYSTEM-GENERATED POSTING**, which is what
these cases are ultimately about:

* **Re-derivability.** A wrong posting can be rebuilt from the Charge; a wrong
  canonical event is permanent, because a posting is immutable AND undeletable.
* **The platform-fee effect is an EXPLICIT property of the projection** rather
  than something a synthetic row inherits by accident.
  `TestUbbsOwnFeeIsChargedOnTheProjection` proves what the fee is charged on by
  moving the period total the fee is a percentage of, rather than by reasoning
  from the fee formula.
* **Catalogue compatibility.** The posting is marked system-generated by its own
  discriminator instead of impersonating a recognised tenant Event Type, which
  would be unrecognised at the catalogue and quarantined.

⚠ **THE MONEY KEY IS THE POSTING'S ID, AND IT IS PRESERVED RATHER THAN
REPLACED.** The chain *unit of work → Charge → posting → deduction* is 1:1 at
every hop, so the wallet's `usage_deduction:{id}` key still names exactly one
movement of money, and the amount-mismatch guard in
`wallets/operations.py::draw_down_usage` still protects it.

⚠ **THE TWO ECONOMIC STATES THIS SLICE MAKES REACHABLE ARE NOT BOTH HERE.** This
module proves the `measurements_status` half — a charge posting reads as *not
applicable* rather than as a pruned metered one — because that state becomes
reachable the moment the discriminator lands and the derivation does the rest.
The metered postings UNDER a fixed-price unit of work reading `not_applicable`
rather than zero is #418's, and so is the receipt whose subject is a Charge.

⚠ **THE FIXTURE IS #416's, IMPORTED.** `docs/conventions/testing.md` wants
shared setup in one place, and the shape needed here is exactly the one that
module built — a tenant with a kind of work sold whole and one sold per event, a
wallet, and a close through the real route. Copying it would be two fixtures
free to drift into two ideas of what a priced unit of work is.
"""
import uuid
from dataclasses import asdict
from datetime import timedelta

import pytest
from django.db import IntegrityError, transaction
from django.utils import timezone

from api.v1.tests.test_a_delivered_unit_of_work_is_charged_once import (
    A_GROUPING_KEY, A_GROUPING_VALUE, ChargeTestBase, SOLD_PER_EVENT,
    SOLD_WHOLE, THE_AGREED_PRICE,
)
from api.v1.tests.test_metering_endpoints import declared_grouping_values
from apps.billing.handlers import handle_usage_recorded_billing
from apps.billing.tenant_billing.models import TenantBillingPeriod
from apps.billing.wallets import operations as wallet_ops
from apps.billing.wallets.models import Wallet, WalletTransaction
from apps.metering.pricing.services.charge_projection import project_the_charge
from apps.metering.pricing.services.charge_service import compensate
from apps.metering.queries import get_revenue_analytics
from apps.metering.pricing.tests._helpers import (
    a_price_for_whole_work, a_rule_that_prices_what_it_measures, priced_at,
)
from apps.metering.usage.measurements import (
    measurements_status_for, posting_kind,
)
from apps.metering.usage.models import Posting, PostingMeasurement
from apps.metering.usage.services.usage_service import UsageService
from apps.platform.events.dispatch import dispatch_to_handlers
from apps.platform.events.models import OutboxEvent
from apps.platform.events.schemas import UsageRecorded
from apps.platform.grouping_fields.services import DimensionService
from apps.platform.work.models import Task
from core.vocabulary import (
    COSTING_STATUS_KNOWN, MEASUREMENTS_STATUS_NOT_APPLICABLE,
    OUTCOME_REASON_EXECUTION_FAILED, PRICING_STATUS_KNOWN, TASK_OUTCOME_FAILED,
    USAGE_EVENT_KIND_METERED_USAGE, USAGE_EVENT_KIND_TASK_CHARGE,
)

#: What a supplier charged for a projection: nothing, and settled. Spelled once
#: so a case asserting it says which of the column's two readings it means —
#: NULL is *not resolved* and this is *resolved, and it was exactly nothing*.
NO_SUPPLIER_WORK = 0

#: What one metered sale bills, when a case needs revenue from BOTH kinds and
#: needs them visibly different. Equal amounts would let a total that picked up
#: one of them twice read as correct.
A_METERED_SALE = 2_000_000


class ProjectionTestBase(ChargeTestBase):
    """#416's fixture, plus the readers this module needs on top of it."""

    def _projection_of(self, task_id):
        """The one posting the Charge for ``task_id`` projected onto."""
        return Posting.objects.get(task_id=task_id,
                                   kind=USAGE_EVENT_KIND_TASK_CHARGE)

    def _postings_on(self, task_id):
        return Posting.objects.filter(task_id=task_id)

    def _drain_the_rails(self):
        """Run every recorded posting through the real dispatcher.

        `dispatch_to_handlers` rather than the billing handler by name, because
        the dispatcher is what applies the PRODUCT GATE — and a metering-only
        tenant's rails are exactly the difference that gate makes. Calling the
        handler directly would run a billing lane for a tenant that does not
        have billing, and the one class in this module whose whole subject is
        that posture would have proved nothing.
        """
        for row in OutboxEvent.objects.filter(
                event_type="usage.recorded").order_by("created_at"):
            dispatch_to_handlers(row)

    def _a_metered_sale(self, task_id):
        """One metered posting under ``task_id``, and the posting it produced.

        ⚠ **WHETHER IT BILLS ANYTHING DEPENDS ON THE PIECE OF WORK IT IS UNDER,
        AND THAT IS #418'S RULE ARRIVING HERE.** Under work sold at one agreed
        price this posting's price is `not_applicable`, because the customer
        revenue is the whole piece's; under work priced per event it bills the
        amount below. The cases that need a metered posting merely to sit BESIDE
        a projection pass the fixed-price piece; the one that needs a second
        REVENUE in the tenant's period builds its own event-priced piece of work
        and passes that.
        """
        a_rule_that_prices_what_it_measures(self.tenant,
                                            event_type=SOLD_PER_EVENT)
        recorded = UsageService.record_usage(
            self.tenant, self.customer, f"call-{uuid.uuid4()}",
            event_type=SOLD_PER_EVENT, task_id=task_id,
            measurements=priced_at(A_METERED_SALE))
        return Posting.objects.get(id=recorded["event_id"])


@pytest.mark.django_db
class TestAChargeProjectsOntoExactlyOnePosting(ProjectionTestBase):
    """AC 2 — one posting, and every field of it is the one §12 names."""

    def test_a_delivered_priced_unit_of_work_produces_one_charge_posting(self):
        started = self._priced_work()

        self._close(started)

        assert self._postings_on(started).filter(
            kind=USAGE_EVENT_KIND_TASK_CHARGE).count() == 1

    def test_the_posting_carries_the_amount_as_customer_revenue(self):
        started = self._priced_work()

        self._close(started)

        projection = self._projection_of(started)
        assert projection.billed_cost_micros == THE_AGREED_PRICE
        assert projection.pricing_status == PRICING_STATUS_KNOWN
        assert projection.not_applicable_reason is None

    def test_the_posting_carries_a_settled_supplier_cost_of_nothing(self):
        """⚠ ZERO AND SETTLED, NEVER NULL, and the column's own two readings
        are why.

        `NULL` means UBB has not resolved a supplier cost, and puts the row in
        every recovery queue until it does. There is nothing to resolve here: a
        projection has no supplier behind it, and the supplier work a
        fixed-price unit really did burn is on the metered postings beside this
        one. Zero with `known` says exactly that.
        """
        started = self._priced_work()

        self._close(started)

        projection = self._projection_of(started)
        assert projection.provider_cost_micros == NO_SUPPLIER_WORK
        assert projection.costing_status == COSTING_STATUS_KNOWN
        assert projection.unresolved_reason is None

    def test_the_posting_has_no_measurement_record_at_all(self):
        """§E4's absence, used for the first time by the kind it was reserved
        for.

        `usage_service` writes a measurement record for every metered posting,
        empty bag or not, *"because absence is reserved for the posting kind
        that never had measurements"*. This is that kind, and an empty child
        here would spend the meaning on a bag nobody left out.
        """
        started = self._priced_work()

        self._close(started)

        projection = self._projection_of(started)
        assert not PostingMeasurement.objects.filter(
            posting=projection).exists()
        assert projection.measurements == {}

    def test_the_posting_names_no_event_type_and_no_provider(self):
        """AC 2's *marked system-generated*, stated as what the row does NOT
        carry.

        A synthetic Event Type would be a code no tenant declared — recognised
        by nothing at the catalogue and quarantined for it. The discriminator
        says what this row is instead, so there is no catalogue entry for
        anything to fail to recognise.
        """
        started = self._priced_work()

        self._close(started)

        projection = self._projection_of(started)
        assert projection.event_type == ""
        assert projection.provider == ""
        assert projection.kind == USAGE_EVENT_KIND_TASK_CHARGE

    def test_the_posting_inherits_the_grouping_values_the_work_carried(self):
        """WHAT MAKES THE PROJECTION NEARLY FREE, driven rather than described.

        Inheritance already pushes a unit of work's slot values onto every
        posting under it, so a charge posting carrying the same ten nets this
        revenue against that same unit's COGS in the same bucket — *margin by
        region* keeps working with no new code. The values come off the CHARGE,
        which froze them; what is asserted is that they arrive at the posting
        identical to the ones the metered postings beside it carry, because
        landing in the same bucket is the whole claim.
        """
        DimensionService.declare(self.tenant, key=A_GROUPING_KEY,
                                 slot="grouping_field_1", scope="task")
        a_price_for_whole_work(self.tenant, task_type=SOLD_WHOLE,
                               amount_micros=THE_AGREED_PRICE)
        started = self._start(**declared_grouping_values(
            {A_GROUPING_KEY: A_GROUPING_VALUE}))
        metered = self._a_metered_sale(started)

        self._close(started)

        projection = self._projection_of(started)
        slots = [f"grouping_field_{slot}" for slot in range(1, 11)]
        assert projection.grouping_field_1 == A_GROUPING_VALUE
        assert ([getattr(projection, slot) for slot in slots]
                == [getattr(metered, slot) for slot in slots])

    def test_the_posting_carries_the_kind_of_work_at_the_whole_altitude(self):
        """`task_type` from the unit of work and `subtask_type` empty — which
        is not an omission.

        `ck_task_agreed_price_only_on_a_whole_fixed_unit` admits an agreed price
        only on a WHOLE unit of work, so a Charge's unit never has a parent and
        there is no contained altitude to name. The database is what makes that
        true, rather than this projection's own second reading of the regime.
        """
        started = self._priced_work()

        self._close(started)

        projection = self._projection_of(started)
        assert projection.task_type == SOLD_WHOLE
        assert projection.subtask_type == ""
        assert Task.objects.get(id=started).parent_id is None

    def test_the_posting_carries_the_charges_own_currency(self):
        started = self._priced_work()

        self._close(started)

        charge = self._charges_against(started).get()
        assert self._projection_of(started).currency == charge.currency

    def test_the_posting_is_dated_when_delivery_was_declared(self):
        """The revenue lands in the period the delivery did.

        §11 dates the Charge at delivery so delivered work is always billable;
        `effective_at` is the column every period, every rollup and every report
        windows on, so the projection carrying `charged_at` there is what makes
        that ruling true of the rail rather than only of the record.
        """
        started = self._priced_work()
        Task.objects.filter(id=started).update(
            created_at=timezone.now() - timedelta(days=40))

        self._close(started)

        charge = self._charges_against(started).get()
        assert self._projection_of(started).effective_at == charge.charged_at

    def test_no_other_ending_projects_anything(self):
        """THE CONTROL. Every claim above would be satisfied by a projection
        that fired on any close at all, and that projection would bill a
        customer the full agreed price for work the tenant's own caller said
        could not be delivered."""
        started = self._priced_work()

        self._close(started, outcome=TASK_OUTCOME_FAILED,
                    outcome_reason=OUTCOME_REASON_EXECUTION_FAILED)

        assert not self._postings_on(started).filter(
            kind=USAGE_EVENT_KIND_TASK_CHARGE).exists()


@pytest.mark.django_db
class TestAChargePostingReadsAsOne(ProjectionTestBase):
    """AC 3 — the one function that answers the kind, and what it now answers.

    Until #417 `posting_kind` returned `metered_usage` for every row in the
    repository, from one place, so that the day a column arrived there was one
    line to change. This is the class that says it changed.
    """

    def test_a_charge_posting_reads_as_a_charge_through_the_one_function(self):
        started = self._priced_work()

        self._close(started)

        assert posting_kind(
            self._projection_of(started)) == USAGE_EVENT_KIND_TASK_CHARGE

    def test_a_metered_posting_beside_it_still_reads_as_metered(self):
        """The discriminating half. A function that answered `task_charge` for
        every row would satisfy the case above and be exactly as wrong as the
        constant it replaced."""
        started = self._priced_work()
        metered = self._a_metered_sale(started)

        self._close(started)

        assert posting_kind(metered) == USAGE_EVENT_KIND_METERED_USAGE

    def test_a_charge_posting_is_not_applicable_rather_than_pruned(self):
        """The state becomes producible by the backend for the first time.

        `measurements_status` reads the kind FIRST and never consults the
        record, so a projection answers *not applicable* — never *pruned*, which
        would tell an end customer that detail was removed on schedule when
        there never was any. The registry declared this answer before anything
        could produce it; this is the first row that does.
        """
        started = self._priced_work()

        self._close(started)

        assert measurements_status_for(
            self._projection_of(started)) == MEASUREMENTS_STATUS_NOT_APPLICABLE

    def test_the_detail_response_serves_the_kind_and_the_derived_status(self):
        """Through the real route, which is where a tenant meets both."""
        started = self._priced_work()
        self._close(started)
        projection = self._projection_of(started)

        body = self.client.get(
            f"/api/v1/metering/usage/{projection.id}", **self._auth()).json()

        assert body["kind"] == USAGE_EVENT_KIND_TASK_CHARGE
        assert body["measurements_status"] == MEASUREMENTS_STATUS_NOT_APPLICABLE
        assert body["billed_cost_micros"] == THE_AGREED_PRICE

    def test_the_list_row_tells_the_two_populations_apart(self):
        """The list is where a reader totals a column by eye, so it is where
        being unable to separate the two populations does the damage.

        ⚠ **WHAT THE TWO ROWS CARRY IS NOT WHAT IT WAS (#418).** This used to
        say *one row carrying revenue against no supplier cost and one carrying
        both*; under a piece of work sold at one agreed price the metered row
        carries no customer revenue at all — its price is `not_applicable`,
        because the revenue for it is the agreed price on the row beside it. So
        the two populations are *the charge, which is all the revenue there is*
        and *the metered calls, which are all the COGS there is*, which is a
        sharper reason to be able to tell them apart rather than a softer one.
        """
        started = self._priced_work()
        metered = self._a_metered_sale(started)
        self._close(started)

        body = self.client.get(
            f"/api/v1/metering/customers/{self.customer.id}/usage",
            **self._auth()).json()

        by_id = {row["id"]: row["kind"] for row in body["data"]}
        assert by_id[str(self._projection_of(started).id)] == \
            USAGE_EVENT_KIND_TASK_CHARGE
        assert by_id[str(metered.id)] == USAGE_EVENT_KIND_METERED_USAGE


@pytest.mark.django_db
class TestUbbsOwnFeeIsChargedOnTheProjection(ProjectionTestBase):
    """AC 5 — the platform-fee effect is EXPLICIT, and this is what proves it.

    UBB's fee is a percentage of `TenantBillingPeriod.total_usage_cost_micros`,
    which `TenantBillingService.accumulate_usage` increments with each posting's
    billed cost. So the question *is fixed-price revenue inside UBB's own fee
    basis?* has one answer and it is observable: the period total the fee is
    taken from either moves by the agreed price or it does not.

    ⚠ **THE ASSERTION IS ON THE BASIS AND NOT ON A FEE FIGURE**, deliberately. A
    test computing the fee would be re-implementing `_calculate_fees` beside it,
    and would pass over a projection that never reached the accumulator at all
    as long as its arithmetic agreed with itself. What is asserted is the number
    the fee is charged ON.
    """

    def _fee_basis(self):
        return TenantBillingPeriod.objects.get(
            tenant=self.tenant).total_usage_cost_micros

    def test_the_fee_basis_moves_by_the_agreed_price(self):
        started = self._priced_work()
        self._close(started)

        self._drain_the_rails()

        assert self._fee_basis() == THE_AGREED_PRICE

    def test_the_basis_holds_both_kinds_and_the_projection_is_one_of_them(self):
        """The discriminating fixture: metered revenue AND the charge, at
        different amounts, so a basis that picked up only one of them is
        visibly short rather than merely equal to something.

        ⚠ **THE METERED REVENUE HAS TO COME FROM WORK PRICED PER EVENT (#418),
        AND THAT IS THE FIXTURE ADMITTING A REAL CHANGE RATHER THAN ROUTING
        ROUND ONE.** A metered posting under the fixed-price piece of work bills
        NOTHING now — its price is `not_applicable`, because the revenue for it
        is the agreed price this very case is adding up. Leaving it there would
        have made the two amounts one amount counted twice and the assertion
        below arithmetic about nothing.
        """
        started = self._priced_work()
        priced_per_event = self._start(task_type=SOLD_PER_EVENT)
        metered = self._a_metered_sale(priced_per_event)
        self._close(started)

        self._drain_the_rails()

        assert metered.billed_cost_micros == A_METERED_SALE
        assert self._fee_basis() == THE_AGREED_PRICE + A_METERED_SALE


@pytest.mark.django_db
class TestThePostingsIdIsStillTheExactlyOnceMoneyKey(ProjectionTestBase):
    """AC 6 — the money key is preserved, and a second projection is refused.

    The chain *unit of work → Charge → posting → deduction* is 1:1 at every hop,
    which is what makes the posting's id a sound key for exactly one movement of
    money.
    """

    def test_the_wallet_is_debited_once_under_the_postings_own_id(self):
        started = self._priced_work()
        self._close(started)

        self._drain_the_rails()

        projection = self._projection_of(started)
        debits = WalletTransaction.objects.filter(
            usage_event_id=projection.id, transaction_type="USAGE_DEDUCTION")
        assert debits.count() == 1
        assert debits.get().amount_micros == -THE_AGREED_PRICE

    def test_replaying_the_handler_debits_nothing_further(self):
        """The exactly-once key doing its job.

        ⚠ THE HANDLER IS CALLED DIRECTLY HERE AND THE DISPATCHER IS NOT, on
        purpose: the dispatcher's own checkpoint would refuse the second call
        before the wallet ever saw it, and this case is about the WALLET's key.
        The handler is at-least-once by construction — an outbox retry after a
        lost acknowledgement replays it — so a projection that could be drawn
        down twice would double-charge on an ordinary retry.
        """
        started = self._priced_work()
        self._close(started)
        self._drain_the_rails()
        before = Wallet.objects.get(customer=self.customer).balance_micros
        row = OutboxEvent.objects.filter(event_type="usage.recorded").get()

        handle_usage_recorded_billing(str(row.id), row.payload)

        assert Wallet.objects.get(
            customer=self.customer).balance_micros == before
        assert WalletTransaction.objects.filter(
            usage_event_id=self._projection_of(started).id,
            transaction_type="USAGE_DEDUCTION").count() == 1

    def test_the_amount_mismatch_guard_still_fires_on_a_second_amount(
            self, caplog):
        """⚠ THE GUARD IS THE PART A REPLAY TEST CANNOT SEE. Two replays at one
        amount are indistinguishable from a key nothing checks; what says the
        key is really a claim about an AMOUNT is a second drawdown under it for
        a different one, which is refused and logged rather than applied."""
        started = self._priced_work()
        self._close(started)
        self._drain_the_rails()
        projection = self._projection_of(started)

        with caplog.at_level("ERROR", logger="apps.billing.wallets.operations"):
            result = wallet_ops.draw_down_usage(
                customer_id=self.customer.id, tenant=self.tenant,
                usage_event_id=projection.id,
                billed_cost_micros=THE_AGREED_PRICE + 1)

        assert result.outcome == "replayed"
        assert "ledger.usage_deduction_amount_mismatch" in caplog.text

    def test_a_duplicate_projection_is_a_database_error(self):
        """AC 6's second half, driven at the database.

        The posting takes the Charge's derived key, so
        `uq_usage_event_idempotency_v2` refuses a second projection of one
        Charge. That is the guard that holds when the winning-transition check
        and the partial uniqueness on `ubb_charge` have both been bypassed — and
        it is the only one of the three a caller reaching into this module
        directly cannot go around.
        """
        started = self._priced_work()
        self._close(started)
        charge = self._charges_against(started).get()

        with pytest.raises(IntegrityError):
            with transaction.atomic():
                project_the_charge(charge)


@pytest.mark.django_db
class TestATenantThatDoesNotBillThroughUbbIsProjectedToo(ProjectionTestBase):
    """Map constraint 2's other realization, one hop further along than #416
    proved it.

    For a metering-only tenant the Charge is a recorded revenue and margin fact,
    and it is the PROJECTION that puts that number where a margin report reads
    it. A projection built only on the billing path would leave every gate in
    this repository green — no gate can tell a correct declaration from a wrong
    one — and would leave a metering-only tenant's fixed-price revenue invisible
    to the same analytics that already show their COGS.
    """

    PRODUCTS = ["metering"]
    BILLING_MODE = None

    def test_the_projection_is_written_with_no_wallet_in_sight(self):
        started = self._priced_work()

        self._close(started)

        projection = self._projection_of(started)
        assert projection.billed_cost_micros == THE_AGREED_PRICE
        assert not Wallet.objects.filter(customer=self.customer).exists()

    def test_the_revenue_reaches_the_margin_report(self):
        """What the projection is FOR, for this posture. The same read that
        already showed this tenant their COGS now nets the agreed price against
        it, because the revenue is a posting rather than a record only the
        pricing app can see."""
        started = self._priced_work()
        self._close(started)

        totals = get_revenue_analytics(str(self.tenant.id))
        assert totals["total_billed_cost_micros"] == THE_AGREED_PRICE
        assert totals["total_markup_micros"] == THE_AGREED_PRICE

    def test_nothing_is_collected_for_it(self):
        """A recorded fact rather than a collection, driven through the real
        dispatcher so the PRODUCT GATE is what decides it rather than this
        test's own reading of which lanes apply."""
        started = self._priced_work()
        self._close(started)

        self._drain_the_rails()

        assert not WalletTransaction.objects.filter(
            usage_event_id=self._projection_of(started).id).exists()
        assert not TenantBillingPeriod.objects.filter(
            tenant=self.tenant).exists()


@pytest.mark.django_db
class TestACompensatingChargeIsNotProjected(ProjectionTestBase):
    """⚠ A NAMED RESIDUAL RATHER THAN AN OMISSION.

    `apps/billing/handlers.py` acts only on `billed_cost_micros > 0`, so a
    negative posting reaches the wallet, the period total and the live spend
    counter as nothing at all: a projected correction would look like a
    reversal and move no money. Correcting a charge ON THE RAILS needs a refund
    path rather than a negative posting, and that path is not this ticket's —
    `charge_service.compensate` has no route either, because a correction needs
    an operator surface and a record of who acted (#416).

    So the refusal is loud, and this class is what stops the gap being closed by
    accident: a later ticket that projects a correction has to delete an
    assertion that says why not.
    """

    def _a_correction_to(self, task_id):
        with transaction.atomic():
            return compensate(self._charges_against(task_id).get(),
                              note="the agreed price was wrong")

    def test_a_correction_is_refused_at_the_projection(self):
        started = self._priced_work()
        self._close(started)

        with pytest.raises(ValueError, match="compensating"):
            with transaction.atomic():
                project_the_charge(self._a_correction_to(started))

    def test_the_rails_would_have_ignored_it_anyway(self):
        """The measurement behind the refusal, so the sentence above is a
        finding rather than an opinion. A negative billed amount is below the
        handler's own guard, so nothing downstream of it runs — which is why
        refusing is better than projecting and hoping."""
        started = self._priced_work()
        self._close(started)
        self._drain_the_rails()
        before = Wallet.objects.get(customer=self.customer).balance_micros
        correction = self._a_correction_to(started)

        handle_usage_recorded_billing(str(uuid.uuid4()), asdict(UsageRecorded(
            tenant_id=str(self.tenant.id),
            customer_id=str(self.customer.id),
            event_id=str(uuid.uuid4()),
            cost_micros=correction.amount_micros,
            billed_cost_micros=correction.amount_micros,
            provider_cost_micros=0,
            billing_owner_id=str(self.customer.id))))

        assert correction.amount_micros < 0
        assert Wallet.objects.get(
            customer=self.customer).balance_micros == before
