# Generated by Django 6.0.1 on 2026-02-10 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'ubb_outbox_event',
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='idx_outbox_status_retry'), models.Index(fields=['status', 'created_at'], name='idx_outbox_status_created'), models.Index(fields=['tenant_id', 'event_type', 'created_at'], name='idx_outbox_tenant_type_created')],
            },
        ),
        migrations.CreateModel(
            name='HandlerCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handler_name', models.CharField(max_length=100)),
                ('outbox_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='events.outboxevent')),
            ],
            options={
                'db_table': 'ubb_handler_checkpoint',
                'constraints': [models.UniqueConstraint(fields=('outbox_event', 'handler_name'), name='uq_checkpoint_event_handler')],
            },
        ),
    ]
