# Generated by Django 6.0.1 on 2026-02-10 19:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tenants', '0005_add_products_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebhookConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(help_text='HMAC-SHA256 signing secret', max_length=255)),
                ('event_types', models.JSONField(default=list, help_text='List of event types to deliver, e.g. ["usage.recorded", "referral.reward_earned"]. Empty list = all events.')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_tenant_webhook_config',
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('outbox_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='events.outboxevent')),
                ('webhook_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='events.tenantwebhookconfig')),
            ],
            options={
                'db_table': 'ubb_webhook_delivery_attempt',
            },
        ),
    ]
