# Generated by Django 6.0.6 on 2026-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_webhook_event_types_explicit_optin'),
        ('tenants', '0021_remove_tenant_min_balance_micros'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenantwebhookconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'url'), name='uq_webhook_config_tenant_url'),
        ),
    ]
