# Generated by Django 6.0.6 on 2026-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_webhook_retiring_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
