"""Offline rendering of the committed OpenAPI document (#77, ADR-002).

The one authority for (a) where the committed document lives and (b) the
canonical serialization. The exporter script, CI's drift gate, and the
in-suite drift pin all render through here, so the bytes cannot disagree
by construction.

It is also where the contract acquires its **known-value metadata** (#208). A
schema field says which registry concept it carries and nothing more::

    status: str = Field(json_schema_extra={"x-ubb-concept": "task_status"})

and the values arrive here, from `openapi/known-values.json`, at export time.
So the platform's source never spells a value set the registry owns, and the
agreement is structural rather than a coincidence of spelling. What each kind
becomes — documentation metadata for an `open` concept, a real `enum` for a
`closed` one, and a refusal for everything else — is
:mod:`tools.known_values`'s business, and openapi/README.md carries the rules.
"""
import json
import sys
from pathlib import Path

# ubb-platform/api/v1/openapi_export.py -> the git root
GIT_ROOT = Path(__file__).resolve().parents[3]
COMMITTED_SPEC_PATH = GIT_ROOT / "openapi" / "v1.json"

#: The generated decision document: which concepts the contract may advertise,
#: and what each one's values are. Generated by `python -m tools.vocabulary
#: --write` and committed beside the spec it is applied to.
KNOWN_VALUES_PATH = GIT_ROOT / "openapi" / "known-values.json"


def generated_document_text() -> str:
    """The composed API's OpenAPI document, rendered deterministically:
    sorted keys, 2-space indent, trailing newline (LF — writers must pass
    ``newline="\\n"``). Requires Django to be set up."""
    from api.v1.api import api

    schema = api.get_openapi_schema()
    _refuse_duplicate_operation_ids(schema)
    schema = _apply_known_values(schema)
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _apply_known_values(schema):
    """Give every field that names a registry concept its recognised values.

    The applier lives at the git root beside the registry, the gate manifest
    and the spec itself, because those are the artifacts it holds together and
    none of them belongs to the platform. Reaching it means putting the git
    root on the path, which is why this is a function rather than a module-level
    import: exporting the spec is a build step, and nothing on a request path
    should acquire a sys.path entry as a side effect of importing this module.

    It is stdlib-only by design — no YAML, no registry compiler, no Django — so
    the same code runs here and in the contract suite that proves it correct.
    """
    if str(GIT_ROOT) not in sys.path:
        sys.path.insert(0, str(GIT_ROOT))
    from tools.known_values import apply_known_values, read_decisions

    return apply_known_values(schema, read_decisions(KNOWN_VALUES_PATH))


def _refuse_duplicate_operation_ids(schema) -> None:
    """A duplicate operationId (two same-named view functions in one module)
    would silently corrupt the document for generators — refuse loudly."""
    operation_ids = [
        operation["operationId"]
        for path_item in schema["paths"].values()
        for operation in path_item.values()
        if isinstance(operation, dict) and "operationId" in operation
    ]
    duplicates = sorted(
        {op_id for op_id in operation_ids if operation_ids.count(op_id) > 1}
    )
    if duplicates:
        raise ValueError(
            f"duplicate operationIds in the generated document: {duplicates}"
        )
