"""Offline rendering of the committed OpenAPI document (#77, ADR-002).

The one authority for (a) where the committed document lives and (b) the
canonical serialization. The exporter script, CI's drift gate, and the
in-suite drift pin all render through here, so the bytes cannot disagree
by construction.

It is also where the contract acquires its **known-value metadata** (#208). A
schema field says which registry concept it carries and nothing more::

    status: str = Field(json_schema_extra={"x-ubb-concept": "task_status"})

and the values arrive here, from `openapi/known-values.json`, at export time.
So the platform's source never spells a value set the registry owns, and the
agreement is structural rather than a coincidence of spelling. What each kind
becomes — documentation metadata for an `open` concept, a real `enum` for a
`closed` one, and a refusal for everything else — is
:mod:`tools.known_values`'s business, and openapi/README.md carries the rules.
"""
import json
import sys
from pathlib import Path

# ubb-platform/api/v1/openapi_export.py -> the git root
GIT_ROOT = Path(__file__).resolve().parents[3]
COMMITTED_SPEC_PATH = GIT_ROOT / "openapi" / "v1.json"

#: The generated decision document: which concepts the contract may advertise,
#: and what each one's values are. Generated by `python -m tools.vocabulary
#: --write` and committed beside the spec it is applied to.
KNOWN_VALUES_PATH = GIT_ROOT / "openapi" / "known-values.json"


def generated_document_text() -> str:
    """The composed API's OpenAPI document, rendered deterministically:
    sorted keys, 2-space indent, trailing newline (LF — writers must pass
    ``newline="\\n"``). Requires Django to be set up."""
    from api.v1.api import api

    schema = api.get_openapi_schema()
    _refuse_duplicate_operation_ids(schema)
    schema = _apply_known_values(schema)
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def _apply_known_values(schema: dict) -> dict:
    """Give every field that names a registry concept its recognised values.

    The applier lives at the git root beside the registry, the gate manifest
    and the spec itself, because those are the artifacts it holds together and
    none of them belongs to the platform. Reaching it means putting the git
    root on the path, which is why this is a function rather than a module-level
    import: exporting the spec is a build step, and nothing on a request path
    should acquire a sys.path entry as a side effect of importing this module.
    Appended rather than prepended, so the git root's `apps/`, `tests/` and
    `tools/` never shadow the platform's own for the rest of the process.

    It is stdlib-only by design — no YAML, no registry compiler, no Django — so
    the same code runs here and in the contract suite that proves it correct.

    APPLIED HERE AND NOT AT `api.py`'S SCHEMA SEAM, which is a deliberate
    departure from that seam's stated invariant and is recorded there too.
    `_ProblemDocumentingNinjaAPI.get_openapi_schema` exists so the committed
    document and the served `/api/v1/openapi.json` are identical by
    construction; putting this there would mean a Django request path reading a
    git-root JSON file and acquiring a sys.path entry, which is a coupling the
    platform does not otherwise have. ADR-002 is what makes the trade cheap:
    the COMMITTED document is the single source of truth for the tenant
    surface, and the served one is a development convenience. The divergence
    WAS empty — no concept was advertised — so the first slice to advertise one
    inherited a visible decision rather than a surprise. Slice 1 (#240) is that
    slice; it took the decision this paragraph argues for, and
    :func:`without_known_values` states what the two documents now promise
    each other.
    """
    _known_values_on_path()
    from tools.known_values import apply_known_values, read_decisions

    return apply_known_values(schema, read_decisions(KNOWN_VALUES_PATH))


def without_known_values(document: dict) -> dict:
    """``document`` with #208's metadata removed — the applier's own inverse.

    THE DIVERGENCE #208 LEFT FOR THE FIRST SLICE TO ADVERTISE A CONCEPT IS NOW
    REAL, and this is how it is stated rather than hidden. Slice 1 marks the
    tenant's `products` field, so the committed document carries an `enum` and
    an `x-ubb-concept` the served `/api/v1/openapi.json` does not, and the two
    are no longer byte-identical.

    THE DECISION, inherited from `_apply_known_values` above and from
    `_ProblemDocumentingNinjaAPI`: the divergence stays, and the pin that
    compared the two documents is narrowed to what is actually guaranteed.
    Both of those docstrings argue the same thing in advance — a Django request
    path must not acquire a git-root file read and a `sys.path` entry to serve
    a document ADR-002 says is not the contract — and closing the gap the other
    way would mean overruling them for a route that exists as a development
    convenience. The canonical path a generator uses (`pnpm ui:api:sync`, the
    SDK's codegen, the conformance sweep) reads the COMMITTED file, and
    `pnpm ui:api:check` turns red if anything is generated from anything else.

    So this is not a softening: `strip_known_values` removes exactly what
    `apply_known_values` writes and nothing else, which is the same inverse the
    contract suite uses to prove the committed document is a fixed point of the
    applier. A route added, a schema changed or a hand edit still fails the pin.
    """
    _known_values_on_path()
    from tools.known_values import strip_known_values

    return strip_known_values(document)


def _known_values_on_path() -> None:
    """Put the git root on the path for the two functions above. Appended, so
    its `apps/`, `tests/` and `tools/` never shadow the platform's own."""
    if str(GIT_ROOT) not in sys.path:
        sys.path.append(str(GIT_ROOT))


def _refuse_duplicate_operation_ids(schema) -> None:
    """A duplicate operationId (two same-named view functions in one module)
    would silently corrupt the document for generators — refuse loudly."""
    operation_ids = [
        operation["operationId"]
        for path_item in schema["paths"].values()
        for operation in path_item.values()
        if isinstance(operation, dict) and "operationId" in operation
    ]
    duplicates = sorted(
        {op_id for op_id in operation_ids if operation_ids.count(op_id) > 1}
    )
    if duplicates:
        raise ValueError(
            f"duplicate operationIds in the generated document: {duplicates}"
        )
