# UBB integration, generated by ubb-codegen (renderer catalogue version 6).
# Do not edit this file. When your UBB configuration changes, generate it
# again and replace it whole. Your own code lives at the call sites.

# schema_version = 1
# renderer_contract_version = 2
# sdk_major_version = null
# target = "shell_http"
# configuration_fingerprint = "sha256:97533a7c087603a587c36b9b9824f9b7df048f54297f511722060038f66fb59e"
# The fingerprint identifies exactly what this file was resolved from. A
# different one in the Code Builder means this file is stale.

# readiness = "blocked"
# BLOCKED, NOT READY TO RUN. The structure is known, and at least one
# call lacks something it cannot run without. Those calls return
# UBB_EXIT_NOT_CONFIGURED; the others run.

# Reported against this integration:

# diagnostic = "constant_measurement_not_renderable" · severity "blocking" · measurement "chat.completion:flat_fee" · field "source_kind"
# The constant quantity is valid platform configuration, with its value
# declared. This Code Builder version cannot yet generate code that uses
# it, so the call is blocked until a version that can. Nothing in the
# declaration needs to change.

# diagnostic = "derived_measurement_unsupported" · severity "blocking" · measurement "chat.completion:ratio" · field "source_kind"
# A derived quantity cannot be computed by generated code. Declare the
# quantity another way with the request below.
# The request that fixes it. UBB never sends it for you:
# remediation_request = {"method":"PUT","route":"/api/v1/event-types/chat.completion/measurements/ratio","operation_id":"api_v1_event_type_endpoints_declare_measurement","body":{"display_name":null,"value_type":null,"unit":null,"required_for_costing":null,"source_kind":null,"source_path":null,"constant_value":null}}

# diagnostic = "response_shape_not_readable_by_target" · severity "blocking" · event_type "chat.completion" · field "source_shape_id"
# The declared response shape is one this target cannot read. Declare a
# shape it can with the request below, or generate for another target.
# The request that fixes it. UBB never sends it for you:
# remediation_request = {"method":"PATCH","route":"/api/v1/event-types/chat.completion","operation_id":"api_v1_event_type_endpoints_revise_event_type","body":{"costing_method":null,"provider_key":null,"category_key":null,"source_shape_id":null,"source_shape_label":null}}

# diagnostic = "event_type_not_published" · severity "blocking" · event_type "draft.only" · field "declaration_status"
# The Event Type has no publication to resolve from. Publish it with the
# request below.
# The request that fixes it. UBB never sends it for you:
# remediation_request = {"method":"POST","route":"/api/v1/event-types/draft.only/publish","operation_id":"api_v1_event_type_endpoints_publish_event_type","body":null}

# Resolved from these declarations:
# task_type = "report_generation"
# event_type = "chat.completion" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"
# event_type = "draft.only"
# event_type = "web.search" · published_revision 1 · published_at "2026-09-01T12:00:00+00:00"

# Three kinds of value appear below, and each has its own shape.
#   A literal is a value UBB resolved from what you declared.
#   A parameter is a value only your code holds, passed as name=value.
#   Leave out one a call requires, or pass it empty, and the call returns
#   UBB_EXIT_USAGE before anything is sent, naming it.
#   $UBB_API_KEY is a credential. UBB withholds it from this file.
# A literal with no configured value, or one this Code Builder version
# cannot yet generate, is a state of a literal, not a fourth kind: it is
# written as a call that raises, saying which.

# Source this file from the script that does the work:
#   . ./ubb_integration.sh
# It requires curl and jq, and checks both before the first request. It
# sets no shell option and never exits the shell that sourced it: every
# function returns a status, and you check it. set -e is not relied on.

# The statuses a function returns. A stop has a status of its own, and no
# other failure is ever returned as it. A request that fails returns the
# status curl gave it; every other failure returns one of these.
UBB_EXIT_STOP_REQUESTED=20
UBB_EXIT_USAGE=64
UBB_EXIT_VALUE_REFUSED=65
UBB_EXIT_TOOL_UNAVAILABLE=69
UBB_EXIT_RESPONSE_UNREADABLE=76
UBB_EXIT_NOT_CONFIGURED=78

# What a call leaves behind for the code that called it. They are shell
# variables this file sets, not settings you supply, and it exports none.
# UBB_TASK_ID is the id of the work the last start created.
# UBB_RESPONSE is the response to the most recent call. The next call
# overwrites it.
# UBB_STOP_REQUESTED is the stop the most recent record met, or the Task
# ubb_run_task ran, as one line of JSON. It is empty where none was met:
# each clears it before it does anything else, so a stop is never an
# earlier call's.
# They are set in your shell, so never call a function of this file
# inside $( ) or a pipeline: both run it in a subshell, and what it set is
# lost.
UBB_TASK_ID=
UBB_RESPONSE=
UBB_STOP_REQUESTED=

_ubb_ready=
_ubb_closed=
_ubb_stop_met=

# Checks, once, that jq and curl can do what this file asks of them. It
# contacts nothing and creates nothing.
_ubb_preflight() {
  [ -z "$_ubb_ready" ] || return 0
  command -v jq >/dev/null 2>&1 || {
    printf '%s\n' 'This file requires jq, and none is installed.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  _ubb_probe=0
  jq --null-input --arg probe_text 1 --argjson probe_json 1 --raw-output --compact-output --raw-input --slurp \
    --from-file /dev/stdin >/dev/null 2>&1 <<'UBB_JQ' || _ubb_probe=$?
  # A program of this file's own form: read from standard input, holding
  # comments, passing each option and using each form its programs use, and
  # naming each function they call in a branch that is never taken.
  def probe_definition($first; $second): $first + $second;
  [
    $probe_text,
    $probe_json,
    probe_definition(1; 2),
    (1 as $probe_value | $probe_value),
    (if false then 1 elif false then 2 else 3 end),
    (reduce (1, 2) as $probe_item (0; . + $probe_item)),
    ([foreach (1, 2) as $probe_item (0; . + $probe_item; .)]),
    (try 1 catch 2),
    (if false then [add, empty, endswith("probe"), error("probe"), explode, fromjson, has("probe"), last, length, map(.), not, range(0; 1), select(true), split("probe"), tojson, type] else 1 end)
  ]
UBB_JQ
  [ "$_ubb_probe" -eq 0 ] || {
    printf '%s\n' 'The installed jq cannot run the programs this file hands it. jq 1.5 or later can.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  command -v curl >/dev/null 2>&1 || {
    printf '%s\n' 'This file requires curl, and none is installed.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  curl --fail-with-body --version >/dev/null 2>&1 || {
    printf '%s\n' 'The installed curl has no --fail-with-body. curl 7.76 or later has it.' >&2
    return "$UBB_EXIT_TOOL_UNAVAILABLE"
  }
  _ubb_ready=1
}

# Both variables are required, and are read each time a request is made.
_ubb_environment() {
  # Not a secret, and required: the base URL of the UBB API this code
  # calls. This file holds no address of its own.
  [ -n "${UBB_BASE_URL:-}" ] || {
    printf '%s\n' 'UBB_BASE_URL is not set. Set it in the environment this code runs in.' >&2
    return "$UBB_EXIT_NOT_CONFIGURED"
  }
  # A credential. Set it in the environment this code runs in, and never
  # write its value into a file.
  [ -n "${UBB_API_KEY:-}" ] || {
    printf '%s\n' 'UBB_API_KEY is not set. Set it in the environment this code runs in.' >&2
    return "$UBB_EXIT_NOT_CONFIGURED"
  }
}

# Sends one request. The credential goes to curl on standard input, so it
# is never an argument another process can list. The response is left in
# UBB_RESPONSE. A response that is not a success is printed, and the
# status curl gave it is returned.
_ubb_post() {
  _ubb_sent=0
  UBB_RESPONSE=$(printf 'Authorization: Bearer %s\n' "$UBB_API_KEY" | curl \
    --silent --show-error --fail-with-body \
    --request POST \
    --header @- \
    --header 'Content-Type: application/json' \
    --data-binary "$2" \
    "${UBB_BASE_URL%/}$1"
  ) || _ubb_sent=$?
  [ "$_ubb_sent" -ne 0 ] || return 0
  [ -z "$UBB_RESPONSE" ] || printf '%s\n' "$UBB_RESPONSE" >&2
  [ "$_ubb_sent" -ne "$UBB_EXIT_STOP_REQUESTED" ] || _ubb_sent=1
  return "$_ubb_sent"
}

# The id of the work a start created is read off the response and left in
# UBB_TASK_ID.
_ubb_jq_task_id() {
  jq --raw-output --null-input \
    --arg response "$UBB_RESPONSE" \
    --from-file /dev/stdin <<'UBB_JQ'
  ($response | fromjson) as $started
  | if ($started | type) != "object" or ($started.task_id | type) != "string"
       or $started.task_id == ""
    then error("the response carries no task_id")
    else $started.task_id end
UBB_JQ
}

_ubb_started() {
  UBB_TASK_ID=$(_ubb_jq_task_id) || {
    printf '%s\n' 'the response is not the acknowledgement this call expects.' >&2
    return "$UBB_EXIT_RESPONSE_UNREADABLE"
  }
}

# A stop arrives on a successful response, so it is read off the
# acknowledgement and never off the HTTP status. The event that carried
# it was recorded and charged: never send it again. Its metadata is left
# in UBB_STOP_REQUESTED and the reserved status is returned.
_ubb_jq_stop() {
  jq --raw-output --null-input \
    --arg response "$UBB_RESPONSE" \
    --arg idempotency_key "$1" \
    --from-file /dev/stdin <<'UBB_JQ'
  ($response | fromjson) as $acknowledgement
  | if ($acknowledgement | type) != "object"
       or ($acknowledgement.event_id | type) != "string"
    then error("the acknowledgement carries no event_id")
    elif $acknowledgement.stop == true
    then {
      "event_id": $acknowledgement.event_id,
      "idempotency_key": $idempotency_key,
      "stop_scope": $acknowledgement.stop_scope,
      "stop_reason": $acknowledgement.stop_reason
    } | tojson
    else "null" end
UBB_JQ
}

_ubb_acknowledge() {
  _ubb_stop=$(_ubb_jq_stop "$1") || {
    printf '%s\n' 'the response is not the acknowledgement this call expects.' >&2
    return "$UBB_EXIT_RESPONSE_UNREADABLE"
  }
  [ "$_ubb_stop" != null ] || return 0
  UBB_STOP_REQUESTED=$_ubb_stop
  _ubb_stop_met=$_ubb_stop
  return "$UBB_EXIT_STOP_REQUESTED"
}

# What a call prints, before returning UBB_EXIT_USAGE, for a parameter it
# was not given, was given empty, or does not have.
_ubb_missing() {
  printf '%s: %s %s\n' "$1" "$2" 'is required, and was left out or passed empty.' >&2
}

_ubb_unknown() {
  printf '%s: %s %s\n' "$1" "${2%%=*}" 'is not a parameter of this call. Pass each one as name=value.' >&2
}

# A quantity is a whole number, carried exactly or refused as
# UBB_EXIT_VALUE_REFUSED.
_ubb_whole_number() {
  case ${3#-} in
    '' | *[!0-9]* | 0?* | ????????????????*)
      printf '%s: %s %s\n' "$1" "$2" 'is not a whole number of at most 15 digits, which is what is carried exactly.' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
}

# A value written into a URL is one that needs no encoding there, or it
# is refused as UBB_EXIT_VALUE_REFUSED.
_ubb_url_value() {
  case $3 in
    . | .. | *[!A-Za-z0-9._~-]*)
      printf '%s: %s %s\n' "$1" "$2" 'cannot be written into a URL as it stands.' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
}

# What a call prints, before returning UBB_EXIT_NOT_CONFIGURED, while it
# is not ready to run. The header of this file says why.
_ubb_not_ready() {
  printf '%s (%s) %s' "$1" "$2" 'is not ready to run. The generated file'\''s header says why.' >&2
  shift 2
  for _ubb_reason in "$@"; do
    printf ' %s' "$_ubb_reason" >&2
  done
  printf '\n' >&2
}

# A cost a supplier reports is converted to whole micros once, here, on
# its digits as text: no arithmetic is done on the amount, so nothing can
# round it. An amount finer than a micro is refused, never rounded, as
# UBB_EXIT_VALUE_REFUSED.
_ubb_known_currency() {
  case $1 in
    [Aa][Uu][Dd]) _ubb_currency=aud; _ubb_shift=4 ;;
    [Bb][Rr][Ll]) _ubb_currency=brl; _ubb_shift=4 ;;
    [Cc][Aa][Dd]) _ubb_currency=cad; _ubb_shift=4 ;;
    [Cc][Hh][Ff]) _ubb_currency=chf; _ubb_shift=4 ;;
    [Cc][Zz][Kk]) _ubb_currency=czk; _ubb_shift=4 ;;
    [Dd][Kk][Kk]) _ubb_currency=dkk; _ubb_shift=4 ;;
    [Ee][Uu][Rr]) _ubb_currency=eur; _ubb_shift=4 ;;
    [Gg][Bb][Pp]) _ubb_currency=gbp; _ubb_shift=4 ;;
    [Hh][Kk][Dd]) _ubb_currency=hkd; _ubb_shift=4 ;;
    [Ii][Nn][Rr]) _ubb_currency=inr; _ubb_shift=4 ;;
    [Mm][Xx][Nn]) _ubb_currency=mxn; _ubb_shift=4 ;;
    [Nn][Oo][Kk]) _ubb_currency=nok; _ubb_shift=4 ;;
    [Nn][Zz][Dd]) _ubb_currency=nzd; _ubb_shift=4 ;;
    [Pp][Ll][Nn]) _ubb_currency=pln; _ubb_shift=4 ;;
    [Ss][Ee][Kk]) _ubb_currency=sek; _ubb_shift=4 ;;
    [Ss][Gg][Dd]) _ubb_currency=sgd; _ubb_shift=4 ;;
    [Uu][Ss][Dd]) _ubb_currency=usd; _ubb_shift=4 ;;
    [Zz][Aa][Rr]) _ubb_currency=zar; _ubb_shift=4 ;;
    *)
      printf '%s %s\n' "$1" 'is not a currency UBB holds' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
}

_ubb_trim() {
  _ubb_trimmed=${1#"${1%%[![:space:]]*}"}
  _ubb_trimmed=${_ubb_trimmed%"${_ubb_trimmed##*[![:space:]]}"}
}

_ubb_pin_currency() {
  _ubb_trim "$1"
  _ubb_pinned=$_ubb_trimmed
  _ubb_trim "$2"
  _ubb_supplied=$_ubb_trimmed
  if [ -z "$_ubb_pinned" ] && [ -z "$_ubb_supplied" ]; then
    printf '%s\n' 'this cost is denominated in no currency' >&2
    return "$UBB_EXIT_VALUE_REFUSED"
  fi
  if [ -n "$_ubb_pinned" ]; then
    _ubb_known_currency "$_ubb_pinned" || return $?
    _ubb_pinned=$_ubb_currency
  fi
  if [ -n "$_ubb_supplied" ]; then
    _ubb_known_currency "$_ubb_supplied" || return $?
    _ubb_supplied=$_ubb_currency
  fi
  if [ -n "$_ubb_pinned" ] && [ -n "$_ubb_supplied" ] && [ "$_ubb_pinned" != "$_ubb_supplied" ]; then
    printf '%s: %s, %s\n' 'the supplier reported this cost in another currency than the declared one' "$_ubb_supplied" "$_ubb_pinned" >&2
    return "$UBB_EXIT_VALUE_REFUSED"
  fi
  _ubb_currency=${_ubb_pinned:-$_ubb_supplied}
}

_ubb_to_micros() {
  case $2 in
    micros) _ubb_shift=0 ;;
    minor_units) _ubb_known_currency "$3" || return $? ;;
    major_units_decimal) _ubb_shift=6 ;;
    *)
      printf '%s %s\n' "$2" 'is not an amount representation' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
  _ubb_trim "$1"
  _ubb_text=$_ubb_trimmed
  while :; do
    case $_ubb_text in
      *_*) _ubb_text=${_ubb_text%%_*}${_ubb_text#*_} ;;
      *) break ;;
    esac
  done
  _ubb_sign=
  case $_ubb_text in
    -*) _ubb_sign=-; _ubb_text=${_ubb_text#-} ;;
    +*) _ubb_text=${_ubb_text#+} ;;
  esac
  _ubb_exponent=0
  _ubb_exponent_sign=
  case $_ubb_text in
    *[eE]*)
      _ubb_exponent=${_ubb_text#*[eE]}
      _ubb_text=${_ubb_text%%[eE]*}
      case $_ubb_exponent in
        -*) _ubb_exponent_sign=-; _ubb_exponent=${_ubb_exponent#-} ;;
        +*) _ubb_exponent=${_ubb_exponent#+} ;;
      esac
      ;;
  esac
  case $_ubb_text in
    *.*) _ubb_whole=${_ubb_text%%.*}; _ubb_fraction=${_ubb_text#*.} ;;
    *) _ubb_whole=$_ubb_text; _ubb_fraction= ;;
  esac
  _ubb_digits=$_ubb_whole$_ubb_fraction
  case $_ubb_digits in
    '' | *[!0-9]*)
      printf '%s %s\n' "$1" 'is not a number' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
  case $_ubb_exponent in
    '' | *[!0-9]*)
      printf '%s %s\n' "$1" 'is not a number' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
  while :; do
    case $_ubb_digits in
      0?*) _ubb_digits=${_ubb_digits#0} ;;
      *) break ;;
    esac
  done
  while :; do
    case $_ubb_exponent in
      0?*) _ubb_exponent=${_ubb_exponent#0} ;;
      *) break ;;
    esac
  done
  case $_ubb_exponent in
    ???????*)
      printf '%s %s\n' "$1" 'is not an amount of money that can be held: its exponent is out of range' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
  esac
  _ubb_scale=$((${_ubb_exponent_sign}${_ubb_exponent} - ${#_ubb_fraction}))
  while [ "$_ubb_scale" -lt 0 ]; do
    case $_ubb_digits in
      ?*0) _ubb_digits=${_ubb_digits%0}; _ubb_scale=$((_ubb_scale + 1)) ;;
      *) break ;;
    esac
  done
  if [ "$_ubb_scale" -gt 40 ] || [ "$_ubb_scale" -lt -40 ]; then
    printf '%s %s\n' "$1" 'is not an amount of money that can be held: its exponent is out of range' >&2
    return "$UBB_EXIT_VALUE_REFUSED"
  fi
  _ubb_scale=$((_ubb_scale + _ubb_shift))
  if [ "$_ubb_scale" -lt 0 ] && [ "$_ubb_digits" != 0 ]; then
    printf '%s %s\n' "$1" 'is not a whole number of micros, and a reported cost is never rounded' >&2
    return "$UBB_EXIT_VALUE_REFUSED"
  fi
  while [ "$_ubb_scale" -gt 0 ] && [ "$_ubb_digits" != 0 ]; do
    _ubb_digits=${_ubb_digits}0
    _ubb_scale=$((_ubb_scale - 1))
  done
  case $_ubb_digits in
    ????????????????????*)
      printf '%s %s\n' "$1" 'is more micros than can be held' >&2
      return "$UBB_EXIT_VALUE_REFUSED"
      ;;
    ???????????????????)
      _ubb_low=${_ubb_digits#??????????}
      _ubb_middle=${_ubb_digits#?}
      _ubb_middle=${_ubb_middle%?????????}
      _ubb_high=${_ubb_digits%??????????????????}
      if [ "$_ubb_high" -gt 9 ] ||
        { [ "$_ubb_high" -eq 9 ] && [ "$_ubb_middle" -gt 223372036 ]; } ||
        { [ "$_ubb_high" -eq 9 ] && [ "$_ubb_middle" -eq 223372036 ] && [ "$_ubb_low" -gt 854775807 ]; }; then
        printf '%s %s\n' "$1" 'is more micros than can be held' >&2
        return "$UBB_EXIT_VALUE_REFUSED"
      fi
      ;;
  esac
  [ "$_ubb_digits" != 0 ] || _ubb_sign=
  _ubb_micros=$_ubb_sign$_ubb_digits
}

# A cost read off your supplier's response is read as it is written
# there, never as the number jq would make of it: a JSON string as its
# text, an integer as its digits. A number written with a fraction or an
# exponent is a binary float, and is refused as UBB_EXIT_VALUE_REFUSED:
# read the response's integer or decimal string instead. So is a
# response holding a number Python's json does not read, such as 01, .5
# or nan, wherever it sits.
_ubb_read_amount() {
  case $_ubb_read in
    string:* | integer:*)
      _ubb_amount=${_ubb_read#*:}
      return 0
      ;;
    missing) _ubb_why='is not in the response' ;;
    unreadable) _ubb_why='cannot be read: the response is not JSON' ;;
    null) _ubb_why='is null: no cost was reported, and a missing cost is not a zero' ;;
    flag) _ubb_why='is a flag, not a reported cost' ;;
    float) _ubb_why='is a binary float, and a reported cost is money: read the response'\''s integer or its decimal string instead' ;;
    *) _ubb_why='is not a number' ;;
  esac
  printf '%s: %s read at %s %s\n' "$1" "$2" "$3" "$_ubb_why" >&2
  return "$UBB_EXIT_VALUE_REFUSED"
}

_ubb_jq_body_start_task() {
  jq --compact-output --null-input \
    --arg p_customer_id "$_ubb_p_customer_id" \
    --arg p_idempotency_key "$_ubb_p_idempotency_key" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "customer_id": $p_customer_id,
    "idempotency_key": $p_idempotency_key,
    # task_type = "report_generation" · task_type "report_generation"
    # task_type.pricing_mode = "event_priced" · task_type "report_generation"
    # task_type.uncapped = true · task_type "report_generation"
    "task_type": "report_generation"
  }
UBB_JQ
}

# idempotency_key is your own identifier for this piece of work, and the
# same on every retry. A new value on each attempt starts the work twice.
# This kind of work is priced event by event, as each one is recorded.
ubb_start_task() {
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_customer_id=
  _ubb_p_idempotency_key=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      customer_id=*) _ubb_p_customer_id=${_ubb_argument#customer_id=} ;;
      idempotency_key=*) _ubb_p_idempotency_key=${_ubb_argument#idempotency_key=} ;;
      *)
        _ubb_unknown ubb_start_task "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_customer_id" ] || {
    _ubb_missing ubb_start_task customer_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_idempotency_key" ] || {
    _ubb_missing ubb_start_task idempotency_key
    return "$UBB_EXIT_USAGE"
  }
  _ubb_body=$(_ubb_jq_body_start_task) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/tasks' "$_ubb_body" || return $?
  _ubb_started || return $?
  UBB_STOP_REQUESTED=
  _ubb_stop_met=
}

# The whole of a Task, as one command you name. It is run with the Task's
# task_id as its one argument. Declare how the work ended inside it, with
# ubb_close_task: nothing here declares an outcome for you.
# This is the one place a stop is acted on, and it is acted on whatever
# the work then returned. The event that carried it was recorded and
# charged: never send it again. The stop is logged and the reserved
# status returned, so whatever runs this work can honour its scope.
# Work that returns a failure is not declared failed: a status is not
# evidence of how the work went. Its status is returned as it is, and a
# Task with no outcome declared is left open and said to be. Work that
# returns success having declared none is left open too, and that is
# returned as UBB_EXIT_USAGE.
ubb_run_task() {
  UBB_STOP_REQUESTED=
  _ubb_stop_met=
  [ "$#" -ge 1 ] || {
    printf '%s: %s\n' ubb_run_task 'the first argument is the command that does the work.' >&2
    return "$UBB_EXIT_USAGE"
  }
  _ubb_work=$1
  shift
  ubb_start_task "$@" || return $?
  set -- "$_ubb_work" "$UBB_TASK_ID"
  "$1" "$2" && set -- "$1" "$2" 0 || set -- "$1" "$2" "$?"
  if [ "$3" -eq "$UBB_EXIT_STOP_REQUESTED" ] || [ -n "$_ubb_stop_met" ]; then
    UBB_STOP_REQUESTED=$_ubb_stop_met
    printf '%s\n' 'UBB requested a stop. The event that carried it was recorded and must not be sent again.' >&2
    printf '%s %s\n' stop_requested "${UBB_STOP_REQUESTED:-null}" >&2
    return "$UBB_EXIT_STOP_REQUESTED"
  fi
  case " $_ubb_closed " in
    *" $2 "*) return "$3" ;;
  esac
  if [ "$3" -eq 0 ]; then
    printf '%s: %s\n' ubb_run_task 'the work ended without declaring an outcome, and is left open. Declare one with ubb_close_task.' >&2
    return "$UBB_EXIT_USAGE"
  fi
  printf '%s: %s\n' ubb_run_task 'the work returned a failure and declared no outcome. None was declared for it: the Task is left open.' >&2
  return "$3"
}

_ubb_jq_body_record_chat_completion() {
  jq --compact-output --null-input \
    --arg p_customer_id "$_ubb_p_customer_id" \
    --arg p_idempotency_key "$_ubb_p_idempotency_key" \
    --arg p_task_id "$_ubb_p_task_id" \
    --from-file /dev/stdin <<'UBB_JQ'
  def not_configured($name):
    error($name + " has no configured value.");
  def not_renderable($name):
    error($name + " is valid platform configuration that this Code Builder version cannot yet generate: see the blocking diagnostic in this file's header.");
  {
    "customer_id": $p_customer_id,
    "idempotency_key": $p_idempotency_key,
    "task_id": $p_task_id,
    # event_type = "chat.completion" · event_type "chat.completion"
    # event_type.costing_method = "calculated" · event_type "chat.completion"
    # event_type.source_shape_id = "openai.responses.python.v1" · event_type "chat.completion"
    # event_type.response_shape_representation = "python_object" · event_type "chat.completion"
    "event_type": "chat.completion",
    "measurements": {
      # measurements = "flat_fee" · event_type "chat.completion"
      # measurements.flat_fee.value_type = "integer" · event_type "chat.completion"
      # measurements.flat_fee.unit = "call" · event_type "chat.completion"
      # measurements.flat_fee.required_for_costing = true · event_type "chat.completion"
      "flat_fee": not_renderable("measurements.flat_fee"),
      # measurements = "input_tokens" · event_type "chat.completion"
      # measurements.input_tokens.value_type = "integer" · event_type "chat.completion"
      # measurements.input_tokens.unit = "token" · event_type "chat.completion"
      # measurements.input_tokens.required_for_costing = true · event_type "chat.completion"
      # measurements.input_tokens.source_path = ["usage","input_tokens"] · event_type "chat.completion"
      "input_tokens": not_configured("measurements.input_tokens")
      # measurements = "ratio" · event_type "chat.completion"
      # measurements.ratio.value_type = "decimal" · event_type "chat.completion"
      # measurements.ratio.unit = "token" · event_type "chat.completion"
      # measurements.ratio.required_for_costing = true · event_type "chat.completion"
    }
  }
UBB_JQ
}

# A stop is returned as UBB_EXIT_STOP_REQUESTED, with the event recorded.
# Return it from your own code unchanged, up to whatever runs the work.
ubb_record_chat_completion() {
  UBB_STOP_REQUESTED=
  # This call is not ready to run. See the header of this file.
  _ubb_not_ready 'api_v1_metering_endpoints_record_usage' 'blocked' 'measurements.flat_fee is valid platform configuration that this Code Builder version cannot yet generate: see the blocking diagnostic in this file'\''s header.' 'measurements.input_tokens has no configured value.'
  return "$UBB_EXIT_NOT_CONFIGURED"
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_customer_id=
  _ubb_p_idempotency_key=
  _ubb_p_task_id=
  _ubb_p_response=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      customer_id=*) _ubb_p_customer_id=${_ubb_argument#customer_id=} ;;
      idempotency_key=*) _ubb_p_idempotency_key=${_ubb_argument#idempotency_key=} ;;
      task_id=*) _ubb_p_task_id=${_ubb_argument#task_id=} ;;
      response=*) _ubb_p_response=${_ubb_argument#response=} ;;
      *)
        _ubb_unknown ubb_record_chat_completion "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_customer_id" ] || {
    _ubb_missing ubb_record_chat_completion customer_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_idempotency_key" ] || {
    _ubb_missing ubb_record_chat_completion idempotency_key
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_task_id" ] || {
    _ubb_missing ubb_record_chat_completion task_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_response" ] || {
    _ubb_missing ubb_record_chat_completion response
    return "$UBB_EXIT_USAGE"
  }
  _ubb_body=$(_ubb_jq_body_record_chat_completion) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/metering/usage' "$_ubb_body" || return $?
  _ubb_acknowledge "$_ubb_p_idempotency_key"
}

_ubb_jq_body_record_draft_only() {
  jq --compact-output --null-input \
    --arg p_customer_id "$_ubb_p_customer_id" \
    --arg p_idempotency_key "$_ubb_p_idempotency_key" \
    --arg p_task_id "$_ubb_p_task_id" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "customer_id": $p_customer_id,
    "idempotency_key": $p_idempotency_key,
    "task_id": $p_task_id,
    # event_type = "draft.only" · event_type "draft.only"
    "event_type": "draft.only"
  }
UBB_JQ
}

# A stop is returned as UBB_EXIT_STOP_REQUESTED, with the event recorded.
# Return it from your own code unchanged, up to whatever runs the work.
ubb_record_draft_only() {
  UBB_STOP_REQUESTED=
  # This call is not ready to run. See the header of this file.
  _ubb_not_ready 'api_v1_metering_endpoints_record_usage' 'blocked'
  return "$UBB_EXIT_NOT_CONFIGURED"
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_customer_id=
  _ubb_p_idempotency_key=
  _ubb_p_task_id=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      customer_id=*) _ubb_p_customer_id=${_ubb_argument#customer_id=} ;;
      idempotency_key=*) _ubb_p_idempotency_key=${_ubb_argument#idempotency_key=} ;;
      task_id=*) _ubb_p_task_id=${_ubb_argument#task_id=} ;;
      *)
        _ubb_unknown ubb_record_draft_only "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_customer_id" ] || {
    _ubb_missing ubb_record_draft_only customer_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_idempotency_key" ] || {
    _ubb_missing ubb_record_draft_only idempotency_key
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_task_id" ] || {
    _ubb_missing ubb_record_draft_only task_id
    return "$UBB_EXIT_USAGE"
  }
  _ubb_body=$(_ubb_jq_body_record_draft_only) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/metering/usage' "$_ubb_body" || return $?
  _ubb_acknowledge "$_ubb_p_idempotency_key"
}

_ubb_jq_cost_record_web_search() {
  jq --raw-output --raw-input --slurp \
    --from-file /dev/stdin "$1" <<'UBB_JQ'
  # Reads one value off the response as the response wrote it, and prints
  # what kind of value it is: for a string or an integer, with its text. A
  # response holding a number Python's json does not read is not read, and
  # no number is read for what it is worth, because that loses how it was
  # written.
  def ubb_escapes_next:
    if endswith("\\") then
      explode as $c
      | ([range(0; $c | length) | select($c[.] != 92)] | last) as $kept
      | ((($c | length) - (if $kept == null then 0 else $kept + 1 end)) % 2) == 1
    else false end;
  def ubb_inside_flags:
    [foreach .[] as $part ([false, false];
      [.[1], (if .[1] then ($part | ubb_escapes_next) else true end)];
      .[0])];
  def ubb_without($character):
    split($character) | add // "";
  def ubb_marked($character):
    split($character)
    | if length == 0 then ""
      else [.[0], (.[1:][] | ("\u0001" + $character + "\u0001"), .)] | add end;
  def ubb_scalars_quoted:
    ubb_without(" ") | ubb_without("\t") | ubb_without("\n") | ubb_without("\r")
    | ubb_marked(",") | ubb_marked(":") | ubb_marked("[") | ubb_marked("]") | ubb_marked("{") | ubb_marked("}")
    | split("\u0001")
    | map(if . == "" or . == "," or . == ":" or . == "[" or . == "]" or . == "{" or . == "}"
      then . else "\"" + . + "\"" end)
    | add // "";
  def ubb_as_written($parts; $inside):
    [range(0; $parts | length) as $at
      | (if $at > 0 then "\"" else empty end),
        (if $inside[$at] then $parts[$at] else ($parts[$at] | ubb_scalars_quoted) end)]
    | add;
  def ubb_python_reads($parts; $inside):
    ([range(0; $parts | length) as $at | if $inside[$at] then empty else $parts[$at] end] | add // ""
      | ubb_without(" ") | ubb_without("\t") | ubb_without("\n") | ubb_without("\r")
      | ubb_marked(",") | ubb_marked(":") | ubb_marked("[") | ubb_marked("]") | ubb_marked("{") | ubb_marked("}")
      | "\u0001" + . + "\u0001"
      | ubb_without("\u0001true\u0001") | ubb_without("\u0001false\u0001") | ubb_without("\u0001null\u0001") | ubb_without("\u0001NaN\u0001") | ubb_without("\u0001Infinity\u0001") | ubb_without("\u0001-Infinity\u0001")) as $scalars
    | ([range(0; $parts | length) as $at | if $inside[$at] then $parts[$at] else empty end] | add // "") as $strings
    | ([["a", "b", "c", "d", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "A", "B", "C", "D", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "(", ")", "\u0000", "\ufeff", "\u0001+", "\u0001.", "\u0001-.", ".\u0001", ".e", ".E", "\u000100", "\u0001-00", "\u000101", "\u0001-01", "\u000102", "\u0001-02", "\u000103", "\u0001-03", "\u000104", "\u0001-04", "\u000105", "\u0001-05", "\u000106", "\u0001-06", "\u000107", "\u0001-07", "\u000108", "\u0001-08", "\u000109", "\u0001-09"][]
      | select(. as $pattern | $scalars | split($pattern) | length > 1)] | length) == 0
    and ($strings | split("\u0000") | length) < 2;
  def ubb_at($path):
    reduce $path[] as $segment ({"found": true, "value": .};
      if .found and (.value | type) == "object" and (.value | has($segment))
      then {"found": true, "value": .value[$segment]}
      else {"found": false, "value": null} end);
  def ubb_whole:
    explode
    | (if .[0] == 45 then .[1:] else . end)
    | length > 0 and (map(select(. < 48 or . > 57)) | length) == 0
      and (length == 1 or .[0] != 48);
  . as $text
  | (try [fromjson] catch null) as $parsed
  | if $parsed == null then "unreadable"
    else ($text | split("\"")) as $parts
    | ($parts | ubb_inside_flags) as $inside
    | if (ubb_python_reads($parts; $inside) | not) then "unreadable"
    else ($parsed[0] | ubb_at(["cost","total"])) as $found
    | ($found.value | type) as $type
    | if ($found.found | not) then "missing"
      elif $type == "null" then "null"
      elif $type == "boolean" then "flag"
      elif $type == "string" then
        (if ($found.value | explode | map(select(. == 0)) | length) > 0
         then "other" else "string:" + $found.value end)
      elif $type == "number" then
        (try [ubb_as_written($parts; $inside) | fromjson] catch null) as $copy
        | (if $copy == null then null else ($copy[0] | ubb_at(["cost","total"])).value end) as $token
        | if ($token | type) == "string" and ($token | ubb_whole)
          then "integer:" + $token else "float" end
      else "other" end
    end
  end
UBB_JQ
}

_ubb_jq_body_record_web_search() {
  jq --compact-output --null-input \
    --arg p_customer_id "$_ubb_p_customer_id" \
    --arg p_idempotency_key "$_ubb_p_idempotency_key" \
    --arg p_task_id "$_ubb_p_task_id" \
    --argjson p_searches "$_ubb_p_searches" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "customer_id": $p_customer_id,
    "idempotency_key": $p_idempotency_key,
    "task_id": $p_task_id,
    # event_type = "web.search" · event_type "web.search"
    # event_type.costing_method = "reported" · event_type "web.search"
    # event_type.source_shape_id = "google.gemini.rest.v1" · event_type "web.search"
    # event_type.response_shape_representation = "json" · event_type "web.search"
    "event_type": "web.search",
    "measurements": {
      # measurements = "searches" · event_type "web.search"
      # measurements.searches.value_type = "integer" · event_type "web.search"
      # measurements.searches.unit = "search" · event_type "web.search"
      # measurements.searches.required_for_costing = false · event_type "web.search"
      "searches": $p_searches
    },
    # currency = "usd" · event_type "web.search"
    "currency": "usd"
  }
UBB_JQ
}

# A stop is returned as UBB_EXIT_STOP_REQUESTED, with the event recorded.
# Return it from your own code unchanged, up to whatever runs the work.
# This file never calls your supplier. Pass the path of a file holding
# the response it returned, as JSON. One that does not hold what a
# declared path reads is refused as UBB_EXIT_VALUE_REFUSED: nothing is
# sent, and a missing quantity is never recorded as none.
ubb_record_web_search() {
  UBB_STOP_REQUESTED=
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_customer_id=
  _ubb_p_idempotency_key=
  _ubb_p_task_id=
  _ubb_p_searches=
  _ubb_p_response=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      customer_id=*) _ubb_p_customer_id=${_ubb_argument#customer_id=} ;;
      idempotency_key=*) _ubb_p_idempotency_key=${_ubb_argument#idempotency_key=} ;;
      task_id=*) _ubb_p_task_id=${_ubb_argument#task_id=} ;;
      searches=*) _ubb_p_searches=${_ubb_argument#searches=} ;;
      response=*) _ubb_p_response=${_ubb_argument#response=} ;;
      *)
        _ubb_unknown ubb_record_web_search "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_customer_id" ] || {
    _ubb_missing ubb_record_web_search customer_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_idempotency_key" ] || {
    _ubb_missing ubb_record_web_search idempotency_key
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_task_id" ] || {
    _ubb_missing ubb_record_web_search task_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_searches" ] || {
    _ubb_missing ubb_record_web_search searches
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_response" ] || {
    _ubb_missing ubb_record_web_search response
    return "$UBB_EXIT_USAGE"
  }
  _ubb_whole_number ubb_record_web_search searches "$_ubb_p_searches" || return $?
  # provider_response_cost_micros.source_path = ["cost","total"] · event_type "web.search"
  # provider_response_cost_micros.amount_representation = "major_units_decimal" · event_type "web.search"
  _ubb_read=$(_ubb_jq_cost_record_web_search "$_ubb_p_response") || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_read_amount ubb_record_web_search provider_response_cost_micros '["cost","total"]' || return $?
  _ubb_pin_currency 'usd' '' || return $?
  _ubb_to_micros "$_ubb_amount" 'major_units_decimal' "$_ubb_currency" || return $?
  _ubb_micros_provider_response_cost_micros=$_ubb_micros
  _ubb_body=$(_ubb_jq_body_record_web_search) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_body="{\"provider_response_cost_micros\":$_ubb_micros_provider_response_cost_micros,${_ubb_body#?}"
  _ubb_post '/api/v1/metering/usage' "$_ubb_body" || return $?
  _ubb_acknowledge "$_ubb_p_idempotency_key"
}

_ubb_jq_body_close_task() {
  jq --compact-output --null-input \
    --arg p_outcome "$_ubb_p_outcome" \
    --arg p_outcome_reason "$_ubb_p_outcome_reason" \
    --arg p_reason_detail "$_ubb_p_reason_detail" \
    --from-file /dev/stdin <<'UBB_JQ'
  {
    "outcome": $p_outcome
  }
  + (if $p_outcome_reason == "" then {} else {"outcome_reason": $p_outcome_reason} end)
  + (if $p_reason_detail == "" then {} else {"reason_detail": $p_reason_detail} end)
UBB_JQ
}

# outcome is delivered, failed or cancelled, and UBB never guesses it. A
# failure also says why: pass outcome_reason, and reason_detail if you
# have a sentence to go with it.
ubb_close_task() {
  _ubb_preflight || return $?
  _ubb_environment || return $?
  _ubb_p_task_id=
  _ubb_p_outcome=
  _ubb_p_outcome_reason=
  _ubb_p_reason_detail=
  for _ubb_argument in "$@"; do
    case $_ubb_argument in
      task_id=*) _ubb_p_task_id=${_ubb_argument#task_id=} ;;
      outcome=*) _ubb_p_outcome=${_ubb_argument#outcome=} ;;
      outcome_reason=*) _ubb_p_outcome_reason=${_ubb_argument#outcome_reason=} ;;
      reason_detail=*) _ubb_p_reason_detail=${_ubb_argument#reason_detail=} ;;
      *)
        _ubb_unknown ubb_close_task "$_ubb_argument"
        return "$UBB_EXIT_USAGE"
        ;;
    esac
  done
  [ -n "$_ubb_p_task_id" ] || {
    _ubb_missing ubb_close_task task_id
    return "$UBB_EXIT_USAGE"
  }
  [ -n "$_ubb_p_outcome" ] || {
    _ubb_missing ubb_close_task outcome
    return "$UBB_EXIT_USAGE"
  }
  _ubb_url_value ubb_close_task task_id "$_ubb_p_task_id" || return $?
  _ubb_body=$(_ubb_jq_body_close_task) || return "$UBB_EXIT_VALUE_REFUSED"
  _ubb_post '/api/v1/tasks/'"$_ubb_p_task_id"'/close' "$_ubb_body" || return $?
  _ubb_closed="$_ubb_closed $_ubb_p_task_id"
}
