# Generated by Django 6.0.6 on 2026-08-10 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0023_rename_to_live_counter_maintenance_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_event_category',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_event_category_key')],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_provider',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_provider_key')],
            },
        ),
    ]
