# Generated by Django 6.0.6 on 2026-08-10 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0001_initial'),
        ('tenants', '0023_rename_to_live_counter_maintenance_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('costing_method', models.CharField(max_length=32)),
                ('declaration_status', models.CharField(default='draft', max_length=32)),
                ('source_shape_id', models.CharField(blank=True, default='', max_length=100)),
                ('source_shape_label', models.CharField(blank=True, default='', max_length=200)),
                ('published_revision', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='event_types.eventcategory')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='event_types.provider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_event_type',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_event_type_key'), models.CheckConstraint(condition=models.Q(('costing_method__in', ['calculated', 'reported'])), name='ck_event_type_costing_method'), models.CheckConstraint(condition=models.Q(('declaration_status__in', ['draft', 'published'])), name='ck_event_type_declaration_status'), models.CheckConstraint(condition=models.Q(('source_shape_label', ''), models.Q(('source_shape_id', ''), _negated=True), _connector='OR'), name='ck_event_type_shape_label_needs_a_shape')],
            },
        ),
    ]
