# Generated by Django 6.0.6 on 2026-08-10 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0002_eventtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('value_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal')], default='integer', max_length=16)),
                ('unit', models.CharField(max_length=64)),
                ('required_for_costing', models.BooleanField(default=False)),
                ('source_kind', models.CharField(max_length=32)),
                ('source_path', models.JSONField(blank=True, default=list)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='event_types.eventtype')),
            ],
            options={
                'db_table': 'ubb_measurement',
                'constraints': [models.UniqueConstraint(fields=('event_type', 'code'), name='uq_measurement_code'), models.CheckConstraint(condition=models.Q(('source_kind__in', ['caller_supplied', 'constant', 'derived', 'provider_response'])), name='ck_measurement_source_kind'), models.CheckConstraint(condition=models.Q(('value_type__in', ['decimal', 'integer'])), name='ck_measurement_value_type'), models.CheckConstraint(condition=models.Q(('unit', ''), _negated=True), name='ck_measurement_unit_is_declared')],
            },
        ),
    ]
