# Generated by Django 6.0.6 on 2026-08-10 18:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0003_measurement'),
        ('tenants', '0023_rename_to_live_counter_maintenance_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementConcept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_concepts', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_measurement_concept',
            },
        ),
        migrations.AddField(
            model_name='measurement',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='event_types.measurementconcept'),
        ),
        migrations.AddConstraint(
            model_name='measurementconcept',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='uq_measurement_concept_key'),
        ),
    ]
