# Generated by Django 6.0.6 on 2026-08-10 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0004_measurement_concept'),
        ('tenants', '0023_rename_to_live_counter_maintenance_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantinedKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unrecognised', models.CharField(choices=[('event_type', 'Event Type'), ('measurement_key', 'Measurement key')], max_length=32)),
                ('event_type_key', models.TextField()),
                ('measurement_key', models.TextField(blank=True, default='')),
                ('quantity', models.TextField(blank=True, default='')),
                ('quantities', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('resolution', models.CharField(blank=True, choices=[('', 'Unresolved'), ('mapped', 'Mapped to an existing declaration'), ('registered', 'Registered as a new declaration'), ('dismissed', 'Dismissed as non-economic')], default='', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_key', models.CharField(blank=True, default='', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_keys', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_quarantined_key',
                'indexes': [models.Index(condition=models.Q(('resolution', '')), fields=['tenant', 'occurred_at'], name='ix_quarantined_key_open')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unrecognised__in', ['event_type', 'measurement_key'])), name='ck_quarantined_key_unrecognised'), models.CheckConstraint(condition=models.Q(('resolution__in', ['', 'dismissed', 'mapped', 'registered'])), name='ck_quarantined_key_resolution'), models.CheckConstraint(condition=models.Q(models.Q(('unrecognised', 'measurement_key'), models.Q(('measurement_key', ''), _negated=True)), models.Q(('measurement_key', ''), ('unrecognised', 'event_type')), _connector='OR'), name='ck_quarantined_key_names_what_it_is_about'), models.CheckConstraint(condition=models.Q(models.Q(('quantities', {}), ('unrecognised', 'measurement_key')), models.Q(('quantity', ''), ('unrecognised', 'event_type')), _connector='OR'), name='ck_quarantined_key_holds_its_own_numbers'), models.CheckConstraint(condition=models.Q(models.Q(('resolution', ''), ('resolved_at__isnull', True)), models.Q(models.Q(('resolution', ''), _negated=True), ('resolved_at__isnull', False)), _connector='OR'), name='ck_quarantined_key_resolution_is_dated'), models.CheckConstraint(condition=models.Q(models.Q(('resolution__in', ['mapped', 'registered']), models.Q(('resolved_key', ''), _negated=True)), models.Q(('resolution', 'dismissed'), ('resolved_key', '')), models.Q(('resolution', ''), ('resolved_key', '')), _connector='OR'), name='ck_quarantined_key_resolution_and_key_agree')],
            },
        ),
    ]
