# Generated by Django 6.0.6 on 2026-08-10 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_types', '0005_quarantined_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedCostMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(max_length=32)),
                ('amount_representation', models.CharField(max_length=32)),
                ('source_path', models.JSONField(blank=True, default=list)),
                ('currency_path', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('event_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reported_cost_mapping', to='event_types.eventtype')),
            ],
            options={
                'db_table': 'ubb_reported_cost_mapping',
                'constraints': [models.CheckConstraint(condition=models.Q(('source_kind__in', ['caller_supplied', 'provider_response'])), name='ck_reported_cost_source_kind'), models.CheckConstraint(condition=models.Q(('amount_representation__in', ['major_units_decimal', 'micros', 'minor_units'])), name='ck_reported_cost_amount_representation'), models.CheckConstraint(condition=models.Q(('currency', ''), ('currency_path', []), _connector='XOR'), name='ck_reported_cost_currency_pinned_once')],
            },
        ),
    ]
