# Generated by Django 6.0.1 on 2026-02-01 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('stripe_connected_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('arrears_threshold_micros', models.BigIntegerField(default=5000000)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('branding_config', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'ubb_tenant',
            },
        ),
        migrations.CreateModel(
            name='TenantApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=20)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_tenant_api_key',
            },
        ),
    ]
