# Generated by Django 6.0.1 on 2026-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_backfill_widget_secrets'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
