# Generated by Django 6.0.6 on 2026-07-21 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('actor_kind', models.CharField(default='system', max_length=20)),
                ('actor_id', models.CharField(blank=True, default='', max_length=255)),
                ('actor_display', models.CharField(blank=True, default='', max_length=255)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'ubb_audit_record',
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='idx_audit_tenant_created'), models.Index(fields=['tenant_id', 'resource_type', 'resource_id'], name='idx_audit_tenant_resource')],
            },
        ),
    ]
