# Generated by Django 6.0.1 on 2026-02-02 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBillingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('invoiced', 'Invoiced')], db_index=True, default='open', max_length=20)),
                ('total_usage_cost_micros', models.BigIntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('platform_fee_micros', models.BigIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_periods', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_tenant_billing_period',
            },
        ),
        migrations.CreateModel(
            name='TenantInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('total_amount_micros', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], db_index=True, default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('billing_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='tenant_billing.tenantbillingperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invoices', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_tenant_invoice',
            },
        ),
        migrations.AddIndex(
            model_name='tenantbillingperiod',
            index=models.Index(fields=['status', 'period_end'], name='idx_tbp_status_end'),
        ),
        migrations.AddConstraint(
            model_name='tenantbillingperiod',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_start', 'period_end'), name='uq_tenant_billing_period'),
        ),
        migrations.AddConstraint(
            model_name='tenantbillingperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('tenant',), name='uq_one_open_period_per_tenant'),
        ),
    ]
