# Generated by Django 6.0.1 on 2026-02-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbillingperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('invoicing', 'Invoicing'), ('invoiced', 'Invoiced')], db_index=True, default='open', max_length=20),
        ),
    ]
