# Generated by Django 6.0.1 on 2026-02-10 18:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0002_alter_tenantbillingperiod_status'),
        ('tenants', '0005_add_products_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=100)),
                ('fee_type', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_product_fee_config',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'product'), name='uq_fee_config_tenant_product')],
            },
        ),
    ]
