# Generated by Django 6.0.1 on 2026-02-10 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0003_productfeeconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('amount_micros', models.BigIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='tenant_billing.tenantinvoice')),
            ],
            options={
                'db_table': 'ubb_tenant_invoice_line_item',
            },
        ),
    ]
