# Generated by Django 6.0.1 on 2026-02-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0004_tenantinvoicelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbillingperiod',
            name='event_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
