# Generated by Django 6.0.1 on 2026-03-10 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0005_auto_hardening'),
        ('tenants', '0007_rename_arrears_to_min_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTenantConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('min_balance_micros', models.BigIntegerField(default=0)),
                ('run_cost_limit_micros', models.BigIntegerField(blank=True, null=True)),
                ('hard_stop_balance_micros', models.BigIntegerField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_billing_tenant_config',
            },
        ),
    ]
