# Generated by Django 6.0.1 on 2026-07-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0010_backfill_tenant_min_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtenantconfig',
            name='default_task_floor_snapshot_micros',
        ),
    ]
