# Generated by Django 6.0.6 on 2026-08-05 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_billing', '0011_remove_billingtenantconfig_default_task_floor_snapshot_micros'),
        ('tenants', '0022_tenantapikey_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeCarry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carried_in_micros', models.BigIntegerField(default=0)),
                ('carried_out_micros', models.BigIntegerField(default=0)),
                ('billing_period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_carry', to='tenant_billing.tenantbillingperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_fee_carries', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_platform_fee_carry',
                'constraints': [models.CheckConstraint(condition=models.Q(('carried_in_micros__gte', 0), ('carried_out_micros__gte', 0)), name='ck_platform_fee_carry_non_negative')],
            },
        ),
    ]
