# Generated by Django 6.0.1 on 2026-04-14 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_tenantuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='groups.group')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_group',
                'indexes': [models.Index(fields=['tenant', 'status'], name='idx_group_tenant_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('tenant', 'slug'), name='uq_group_active_tenant_slug')],
            },
        ),
    ]
