# Generated by Django 6.0.1 on 2026-01-30 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('arrears_threshold_micros', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_customer',
            },
        ),
        migrations.CreateModel(
            name='AutoTopUpConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('trigger_threshold_micros', models.BigIntegerField(default=10000000)),
                ('top_up_amount_micros', models.BigIntegerField(default=20000000)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_top_up_config', to='customers.customer')),
            ],
            options={
                'db_table': 'ubb_auto_top_up_config',
            },
        ),
        migrations.CreateModel(
            name='TopUpAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_micros', models.PositiveBigIntegerField()),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('auto_topup', 'Auto Top-Up')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_reason', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_up_attempts', to='customers.customer')),
            ],
            options={
                'db_table': 'ubb_top_up_attempt',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance_micros', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='customers.customer')),
            ],
            options={
                'db_table': 'ubb_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('USAGE_DEDUCTION', 'Usage Deduction'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, max_length=20)),
                ('amount_micros', models.BigIntegerField()),
                ('balance_after_micros', models.BigIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='customers.wallet')),
            ],
            options={
                'db_table': 'ubb_wallet_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_id'), name='uq_customer_tenant_external'),
        ),
        migrations.AddConstraint(
            model_name='topupattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('trigger', 'auto_topup')), fields=('customer',), name='uq_one_pending_auto_topup_per_customer'),
        ),
    ]
