# Generated by Django 6.0.1 on 2026-03-10 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_rename_arrears_to_min_balance'),
        ('wallets', '0002_wallet_model_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_balance_micros', models.BigIntegerField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='customers.customer')),
            ],
            options={
                'db_table': 'ubb_customer_billing_profile',
            },
        ),
    ]
