# Generated by Django 6.0.6 on 2026-06-09 10:11

from django.db import migrations, models


def _backfill_usage_event(apps, schema_editor):
    import uuid
    WalletTransaction = apps.get_model("wallets", "WalletTransaction")
    for tx in WalletTransaction.objects.filter(transaction_type="USAGE_DEDUCTION",
                                               usage_event_id__isnull=True).iterator():
        try:
            tx.usage_event_id = uuid.UUID(str(tx.reference_id))
            tx.save(update_fields=["usage_event_id"])
        except (ValueError, AttributeError, TypeError):
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_customer_billing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='usage_event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(_backfill_usage_event, migrations.RunPython.noop),
    ]
