# Generated by Django 6.0.6 on 2026-06-12 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_backfill_window_days'),
        ('wallets', '0004_wallettransaction_usage_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbillingprofile',
            name='topup_grant_expiry_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top Up'), ('USAGE_DEDUCTION', 'Usage Deduction'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('DISPUTE_DEDUCTION', 'Dispute Deduction'), ('STRIPE_REFUND', 'Stripe Refund'), ('DEBIT', 'Debit'), ('GRANT', 'Credit Grant'), ('GRANT_EXPIRY', 'Credit Grant Expiry'), ('GRANT_VOID', 'Credit Grant Void')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CreditGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('paid', 'Paid'), ('promo', 'Promo')], max_length=10)),
                ('granted_micros', models.BigIntegerField()),
                ('remaining_micros', models.BigIntegerField()),
                ('expired_micros', models.BigIntegerField(default=0)),
                ('voided_micros', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('depleted', 'Depleted'), ('expired', 'Expired'), ('voided', 'Voided')], default='active', max_length=10)),
                ('source', models.CharField(choices=[('checkout', 'Checkout'), ('auto_topup', 'Auto Top-Up'), ('api', 'API'), ('other', 'Other')], default='other', max_length=20)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('source_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_grant', to='wallets.wallettransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_grants', to='tenants.tenant')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_grants', to='wallets.wallet')),
            ],
            options={
                'db_table': 'ubb_credit_grant',
            },
        ),
        migrations.CreateModel(
            name='GrantAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_micros', models.BigIntegerField()),
                ('allocation_type', models.CharField(choices=[('usage', 'Usage'), ('withdrawal', 'Withdrawal'), ('clawback', 'Clawback'), ('overage_recoup', 'Overage Recoup')], max_length=20)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='wallets.creditgrant')),
                ('wallet_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_allocations', to='wallets.wallettransaction')),
            ],
            options={
                'db_table': 'ubb_grant_allocation',
            },
        ),
        migrations.AddIndex(
            model_name='creditgrant',
            index=models.Index(fields=['wallet', 'status', 'expires_at'], name='idx_grant_wallet_status_exp'),
        ),
        migrations.AddIndex(
            model_name='creditgrant',
            index=models.Index(fields=['status', 'expires_at', 'warning_sent_at'], name='idx_grant_status_exp_warn'),
        ),
        migrations.AddConstraint(
            model_name='creditgrant',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_micros__gte', 0), ('remaining_micros__lte', models.F('granted_micros'))), name='ck_grant_remaining_bounds'),
        ),
        migrations.AddConstraint(
            model_name='grantallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_micros__gt', 0)), name='ck_grant_allocation_positive'),
        ),
    ]
