# Generated by Django 6.0.6 on 2026-06-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_customerbillingprofile_topup_grant_expiry_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantallocation',
            name='refunded_micros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='grantallocation',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_micros__gte', 0), ('refunded_micros__lte', models.F('amount_micros'))), name='ck_grant_alloc_refund_bounds'),
        ),
    ]
