# Generated by Django 6.0.6 on 2026-06-12 18:03
#
# CUR-1: currency is lowercase everywhere. Besides flipping the model
# defaults from "USD" to "usd", the data migration normalizes every existing
# Wallet.currency / CreditGrant.currency row (legacy rows were created with
# the hardcoded uppercase "USD").

from django.db import migrations, models
from django.db.models.functions import Lower


def lowercase_currencies(apps, schema_editor):
    Wallet = apps.get_model("wallets", "Wallet")
    CreditGrant = apps.get_model("wallets", "CreditGrant")
    Wallet.objects.update(currency=Lower("currency"))
    CreditGrant.objects.update(currency=Lower("currency"))


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_grantallocation_refunded_micros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditgrant',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        # Lowercasing is idempotent and safe to "reverse" as a no-op: the old
        # code compared nothing on case and the new code reads lowercase.
        migrations.RunPython(lowercase_currencies, migrations.RunPython.noop),
    ]
