# Generated by Django 6.0.1 on 2026-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_alter_creditgrant_currency_alter_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='actor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reason_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
