# Generated by Django 6.0.6 on 2026-07-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0009_customerbillingprofile_soft_min_balance_micros'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='negative_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
