# Generated by Django 6.0.6 on 2026-09-12 09:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('tenants', '0026_the_default_ceilings_for_undeclared_work_come_to_the_kernel'),
        ('wallets', '0010_wallet_negative_since'),
        ('work', '0027_a_stopped_unit_records_the_control_that_fired'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_micros', models.BigIntegerField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('released_by', models.CharField(blank=True, choices=[('terminal_transition', "The unit's terminal transition"), ('backstop_sweep', 'The backstop sweep')], default='', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reservations', to='customers.customer')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='work.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_reservations', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_wallet_reservation',
                'indexes': [models.Index(condition=models.Q(('released_at__isnull', True)), fields=['owner'], name='idx_wallet_reservation_open')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_micros__gte', 0)), name='ck_wallet_reservation_not_negative'), models.CheckConstraint(condition=models.Q(models.Q(('released_at__isnull', True), ('released_by', '')), models.Q(('released_at__isnull', False), models.Q(('released_by', ''), _negated=True)), _connector='OR'), name='ck_wallet_reservation_release_names_its_releaser')],
            },
        ),
    ]
