# Generated by Django 6.0.6 on 2026-06-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_remove_customer_min_balance_micros'),
        ('tasks', '0001_initial'),
        ('tenants', '0016_tenant_enforcement_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='billing_owner_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'last_event_at'], name='idx_run_status_heartbeat'),
        ),
    ]
