# Generated by Django 6.0.6 on 2026-07-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_customer_suspension_reason'),
        ('tasks', '0006_announce_outbox_id'),
        ('tenants', '0019_two_position_enforcement_mode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('provider_cost_limit_micros__isnull', False), ('status', 'active')), fields=['tenant'], name='idx_task_active_limited'),
        ),
    ]
