# Generated by Django 6.0.1 on 2026-07-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_idx_task_active_limited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='floor_snapshot_micros',
        ),
    ]
