# Generated by Django 6.0.6 on 2026-07-27 16:23

from django.db import migrations, models
import django.db.models.deletion
import apps.platform.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_two_position_enforcement_mode'),
        ('tasks', '0007_task_idx_task_active_limited'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.UUIDField(default=None, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=64)),
                ('kind', models.CharField(choices=[('task', 'Task'), ('subtask', 'Subtask')], default='task', max_length=8)),
                ('default_provider_cost_limit_micros', models.BigIntegerField(blank=True, null=True)),
                ('required_dimensions', models.JSONField(blank=True, default=apps.platform.tasks.models._empty_list)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='tenants.tenant')),
            ],
            options={
                'db_table': 'ubb_task_type',
            },
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=['tenant', 'kind', 'key'], name='uq_task_type_key'),
        ),
    ]
