# Generated by Django 6.0.1 on 2026-07-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_dim1_task_dim2_task_dim3_task_dim4_task_dim5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='floor_snapshot_micros',
        ),
    ]
