# @generated by ubb-sdk/codegen/generate_core.py — do not edit by hand.

""" A client library for accessing UBB API """
from .client import AuthenticatedClient, Client

__all__ = (
    "AuthenticatedClient",
    "Client",
)
